/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../src/app/security/user-group/user-group.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../../../../src/app/security/user-group/user-group.service';
import * as import9 from '../../../../../src/app/security/user-role/user-role.service';
import * as import10 from '../../../../../src/app/core/authorization.service';
import * as import11 from '@angular/material/button/button';
import * as import12 from '../../../../node_modules/@angular/material/button/button.ngfactory';
import * as import13 from '@angular/core/src/linker/view_container';
import * as import14 from '@angular/core/src/linker/element_ref';
import * as import15 from '@angular/material/card/card';
import * as import16 from '../../../../node_modules/@angular/material/card/card.ngfactory';
import * as import17 from '../../../../node_modules/@angular/material/core/compatibility/style-compatibility.ngfactory';
import * as import18 from '@angular/material/input/input';
import * as import19 from '../../../../node_modules/@angular/material/input/input.ngfactory';
import * as import20 from '../../../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import21 from '../../../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import22 from '@angular/core/src/linker/query_list';
import * as import23 from '../../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import24 from 'primeng/components/datatable/datatable';
import * as import25 from 'primeng/components/dom/domhandler';
import * as import26 from '../../../../node_modules/primeng/components/datatable/datatable.ngfactory';
import * as import27 from 'primeng/components/common/shared';
import * as import28 from '../../../../node_modules/primeng/components/common/shared.ngfactory';
import * as import29 from '@angular/core/src/linker/template_ref';
import * as import30 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import31 from '@angular/material/core/compatibility/style-compatibility';
import * as import32 from '@angular/forms/src/directives/control_value_accessor';
import * as import33 from '@angular/forms/src/directives/ng_model';
import * as import34 from '@angular/forms/src/directives/ng_control';
import * as import35 from '@angular/forms/src/directives/ng_control_status';
import * as import36 from '@angular/common/src/directives/ng_if';
import * as import37 from '@angular/core/src/change_detection/change_detection_util';
import * as import38 from 'primeng/components/picklist/picklist';
import * as import39 from '../../../../node_modules/primeng/components/picklist/picklist.ngfactory';
import * as import40 from 'primeng/components/growl/growl';
import * as import41 from '../../../../node_modules/primeng/components/growl/growl.ngfactory';
export class Wrapper_UserGroupComponent {
  /*private*/ _eventHandler:Function;
  context:import0.UserGroupComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any,p2:any) {
    this._changed = false;
    this.context = new import0.UserGroupComponent(p0,p1,p2);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_UserGroupComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_UserGroupComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.UserGroupComponent>;
  _UserGroupComponent_0_3:Wrapper_UserGroupComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_UserGroupComponent_Host0,renderType_UserGroupComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'user-group',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_UserGroupComponent0(this.viewUtils,this,0,this._el_0);
    this._UserGroupComponent_0_3 = new Wrapper_UserGroupComponent(this.injectorGet(import8.UserGroupService,this.parentIndex),this.injectorGet(import9.UserRoleService,this.parentIndex),this.injectorGet(import10.AuthorizationService,this.parentIndex));
    this.compView_0.create(this._UserGroupComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._UserGroupComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.UserGroupComponent) && (0 === requestNodeIndex))) { return this._UserGroupComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._UserGroupComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const UserGroupComponentNgFactory:import7.ComponentFactory<import0.UserGroupComponent> = new import7.ComponentFactory<import0.UserGroupComponent>('user-group',View_UserGroupComponent_Host0,import0.UserGroupComponent);
const styles_UserGroupComponent:any[] = ([] as any[]);
class View_UserGroupComponent2 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import11.MdButton>;
  _MdButton_0_3:import12.Wrapper_MdButton;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import13.ViewContainer) {
    super(View_UserGroupComponent2,renderType_UserGroupComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'button',new import3.InlineArray4(4,'color','primary','md-raised-button',''),(null as any));
    this.compView_0 = new import12.View_MdButton0(this.viewUtils,this,0,this._el_0);
    this._MdButton_0_3 = new import12.Wrapper_MdButton(new import14.ElementRef(this._el_0),this.renderer);
    this._text_1 = this.renderer.createText((null as any),'Search',(null as any));
    this.compView_0.create(this._MdButton_0_3.context);
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray8(8,'click',(null as any),'mousedown',(null as any),'focus',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_0));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import11.MdButton) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._MdButton_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = 'primary';
    this._MdButton_0_3.check_color(currVal_0_0_0,throwOnChange,false);
    if (this._MdButton_0_3.ngDoCheck(this,this._el_0,throwOnChange)) { this.compView_0.markAsCheckOnce(); }
    this._MdButton_0_3.checkHost(this,this.compView_0,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 0) && (ngContentIndex == 0))) { cb(this._text_1,ctx); }
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.compView_0.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdButton_0_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.parentView.context.searchUserGroups()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_UserGroupComponent3 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import11.MdButton>;
  _MdButton_0_3:import12.Wrapper_MdButton;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import13.ViewContainer) {
    super(View_UserGroupComponent3,renderType_UserGroupComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'button',new import3.InlineArray4(4,'color','primary','md-raised-button',''),(null as any));
    this.compView_0 = new import12.View_MdButton0(this.viewUtils,this,0,this._el_0);
    this._MdButton_0_3 = new import12.Wrapper_MdButton(new import14.ElementRef(this._el_0),this.renderer);
    this._text_1 = this.renderer.createText((null as any),'Create',(null as any));
    this.compView_0.create(this._MdButton_0_3.context);
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray8(8,'click',(null as any),'mousedown',(null as any),'focus',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_0));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import11.MdButton) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._MdButton_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = 'primary';
    this._MdButton_0_3.check_color(currVal_0_0_0,throwOnChange,false);
    if (this._MdButton_0_3.ngDoCheck(this,this._el_0,throwOnChange)) { this.compView_0.markAsCheckOnce(); }
    this._MdButton_0_3.checkHost(this,this.compView_0,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 0) && (ngContentIndex == 0))) { cb(this._text_1,ctx); }
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.compView_0.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdButton_0_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.parentView.context.createUserGroup()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_UserGroupComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  compView_2:import1.AppView<import15.MdCard>;
  _MdCard_2_3:import16.Wrapper_MdCard;
  _StyleCompatibility_2_4:import17.Wrapper_StyleCompatibility;
  _text_3:any;
  _el_4:any;
  _MdCardTitle_4_3:import16.Wrapper_MdCardTitle;
  _StyleCompatibility_4_4:import17.Wrapper_StyleCompatibility;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _MdCardContent_7_3:import16.Wrapper_MdCardContent;
  _StyleCompatibility_7_4:import17.Wrapper_StyleCompatibility;
  _text_8:any;
  _el_9:any;
  compView_9:import1.AppView<import18.MdInput>;
  _MdInput_9_3:import19.Wrapper_MdInput;
  _NG_VALUE_ACCESSOR_9_4:any[];
  _NgModel_9_5:import20.Wrapper_NgModel;
  _NgControl_9_6:any;
  _NgControlStatus_9_7:import21.Wrapper_NgControlStatus;
  _StyleCompatibility_9_8:import17.Wrapper_StyleCompatibility;
  _query_MdPlaceholder_9_0:import22.QueryList<any>;
  _query_MdHint_9_1:import22.QueryList<any>;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  compView_13:import1.AppView<import18.MdInput>;
  _MdInput_13_3:import19.Wrapper_MdInput;
  _NG_VALUE_ACCESSOR_13_4:any[];
  _NgModel_13_5:import20.Wrapper_NgModel;
  _NgControl_13_6:any;
  _NgControlStatus_13_7:import21.Wrapper_NgControlStatus;
  _StyleCompatibility_13_8:import17.Wrapper_StyleCompatibility;
  _query_MdPlaceholder_13_0:import22.QueryList<any>;
  _query_MdHint_13_1:import22.QueryList<any>;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _MdCardActions_16_3:import16.Wrapper_MdCardActions;
  _StyleCompatibility_16_4:import17.Wrapper_StyleCompatibility;
  _text_17:any;
  _anchor_18:any;
  /*private*/ _vc_18:import13.ViewContainer;
  _TemplateRef_18_5:any;
  _NgIf_18_6:import23.Wrapper_NgIf;
  _text_19:any;
  _el_20:any;
  compView_20:import1.AppView<import11.MdButton>;
  _MdButton_20_3:import12.Wrapper_MdButton;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _el_29:any;
  compView_29:import1.AppView<import24.DataTable>;
  _DomHandler_29_3:import25.DomHandler;
  _DataTable_29_4:import26.Wrapper_DataTable;
  _query_Header_29_0:import22.QueryList<any>;
  _query_Footer_29_1:import22.QueryList<any>;
  _query_PrimeTemplate_29_2:import22.QueryList<any>;
  _query_Column_29_3:import22.QueryList<any>;
  _query_HeaderColumnGroup_29_4:import22.QueryList<any>;
  _query_FooterColumnGroup_29_5:import22.QueryList<any>;
  _text_30:any;
  _el_31:any;
  compView_31:import1.AppView<import27.Header>;
  _Header_31_3:import28.Wrapper_Header;
  _text_32:any;
  _text_33:any;
  _el_34:any;
  compView_34:import1.AppView<import27.Column>;
  _Column_34_3:import28.Wrapper_Column;
  _query_PrimeTemplate_34_0:import22.QueryList<any>;
  _query_TemplateRef_34_1:import22.QueryList<any>;
  _text_35:any;
  _el_36:any;
  compView_36:import1.AppView<import27.Column>;
  _Column_36_3:import28.Wrapper_Column;
  _query_PrimeTemplate_36_0:import22.QueryList<any>;
  _query_TemplateRef_36_1:import22.QueryList<any>;
  _text_37:any;
  _el_38:any;
  compView_38:import1.AppView<import27.Footer>;
  _Footer_38_3:import28.Wrapper_Footer;
  _text_39:any;
  _el_40:any;
  _text_41:any;
  _el_42:any;
  _text_43:any;
  _anchor_44:any;
  /*private*/ _vc_44:import13.ViewContainer;
  _TemplateRef_44_5:any;
  _NgIf_44_6:import23.Wrapper_NgIf;
  _text_45:any;
  _el_46:any;
  compView_46:import1.AppView<import11.MdButton>;
  _MdButton_46_3:import12.Wrapper_MdButton;
  _text_47:any;
  _text_48:any;
  _text_49:any;
  _text_50:any;
  _text_51:any;
  _text_52:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import13.ViewContainer) {
    super(View_UserGroupComponent1,renderType_UserGroupComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'md-card',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_2 = new import16.View_MdCard0(this.viewUtils,this,2,this._el_2);
    this._MdCard_2_3 = new import16.Wrapper_MdCard();
    this._StyleCompatibility_2_4 = new import17.Wrapper_StyleCompatibility(this.renderer,new import14.ElementRef(this._el_2));
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,(null as any),'md-card-title',new import3.InlineArray2(2,'color','primary'),(null as any));
    this._MdCardTitle_4_3 = new import16.Wrapper_MdCardTitle();
    this._StyleCompatibility_4_4 = new import17.Wrapper_StyleCompatibility(this.renderer,new import14.ElementRef(this._el_4));
    this._text_5 = this.renderer.createText(this._el_4,'Search User Groups',(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,(null as any),'md-card-content',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._MdCardContent_7_3 = new import16.Wrapper_MdCardContent();
    this._StyleCompatibility_7_4 = new import17.Wrapper_StyleCompatibility(this.renderer,new import14.ElementRef(this._el_7));
    this._text_8 = this.renderer.createText(this._el_7,'\n      ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_7,'md-input',new import3.InlineArray4(4,'class','col-md-5','placeholder','Name'),(null as any));
    this.compView_9 = new import19.View_MdInput0(this.viewUtils,this,9,this._el_9);
    this._MdInput_9_3 = new import19.Wrapper_MdInput(new import14.ElementRef(this._el_9));
    this._NG_VALUE_ACCESSOR_9_4 = [this._MdInput_9_3.context];
    this._NgModel_9_5 = new import20.Wrapper_NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_9_4);
    this._NgControl_9_6 = this._NgModel_9_5.context;
    this._NgControlStatus_9_7 = new import21.Wrapper_NgControlStatus(this._NgControl_9_6);
    this._StyleCompatibility_9_8 = new import17.Wrapper_StyleCompatibility(this.renderer,new import14.ElementRef(this._el_9));
    this._query_MdPlaceholder_9_0 = new import22.QueryList<any>();
    this._query_MdHint_9_1 = new import22.QueryList<any>();
    this.compView_9.create(this._MdInput_9_3.context);
    this._text_10 = this.renderer.createText(this._el_7,'\n      ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_7,'div',new import3.InlineArray2(2,'class','col-md-2'),(null as any));
    this._text_12 = this.renderer.createText(this._el_7,'\n      ',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,this._el_7,'md-input',new import3.InlineArray4(4,'class','col-md-5','placeholder','Description'),(null as any));
    this.compView_13 = new import19.View_MdInput0(this.viewUtils,this,13,this._el_13);
    this._MdInput_13_3 = new import19.Wrapper_MdInput(new import14.ElementRef(this._el_13));
    this._NG_VALUE_ACCESSOR_13_4 = [this._MdInput_13_3.context];
    this._NgModel_13_5 = new import20.Wrapper_NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_13_4);
    this._NgControl_13_6 = this._NgModel_13_5.context;
    this._NgControlStatus_13_7 = new import21.Wrapper_NgControlStatus(this._NgControl_13_6);
    this._StyleCompatibility_13_8 = new import17.Wrapper_StyleCompatibility(this.renderer,new import14.ElementRef(this._el_13));
    this._query_MdPlaceholder_13_0 = new import22.QueryList<any>();
    this._query_MdHint_13_1 = new import22.QueryList<any>();
    this.compView_13.create(this._MdInput_13_3.context);
    this._text_14 = this.renderer.createText(this._el_7,'\n    ',(null as any));
    this._text_15 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,(null as any),'md-card-actions',new import3.InlineArray2(2,'class','center'),(null as any));
    this._MdCardActions_16_3 = new import16.Wrapper_MdCardActions();
    this._StyleCompatibility_16_4 = new import17.Wrapper_StyleCompatibility(this.renderer,new import14.ElementRef(this._el_16));
    this._text_17 = this.renderer.createText(this._el_16,'\n      ',(null as any));
    this._anchor_18 = this.renderer.createTemplateAnchor(this._el_16,(null as any));
    this._vc_18 = new import13.ViewContainer(18,16,this,this._anchor_18);
    this._TemplateRef_18_5 = new import29.TemplateRef_(this,18,this._anchor_18);
    this._NgIf_18_6 = new import23.Wrapper_NgIf(this._vc_18.vcRef,this._TemplateRef_18_5);
    this._text_19 = this.renderer.createText(this._el_16,'\n      ',(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,this._el_16,'button',new import3.InlineArray4(4,'color','primary','md-raised-button',''),(null as any));
    this.compView_20 = new import12.View_MdButton0(this.viewUtils,this,20,this._el_20);
    this._MdButton_20_3 = new import12.Wrapper_MdButton(new import14.ElementRef(this._el_20),this.renderer);
    this._text_21 = this.renderer.createText((null as any),'Reset',(null as any));
    this.compView_20.create(this._MdButton_20_3.context);
    this._text_22 = this.renderer.createText(this._el_16,'\n    ',(null as any));
    this._text_23 = this.renderer.createText((null as any),'\n  ',(null as any));
    this.compView_2.create(this._MdCard_2_3.context);
    this._text_24 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_25 = import3.createRenderElement(this.renderer,this._el_0,'br',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_26 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_27 = import3.createRenderElement(this.renderer,this._el_0,'br',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_28 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_29 = import3.createRenderElement(this.renderer,this._el_0,'p-dataTable',new import3.InlineArray2(2,'selectionMode','single'),(null as any));
    this.compView_29 = new import26.View_DataTable0(this.viewUtils,this,29,this._el_29);
    this._DomHandler_29_3 = new import25.DomHandler();
    this._DataTable_29_4 = new import26.Wrapper_DataTable(new import14.ElementRef(this._el_29),this._DomHandler_29_3,this.parentView.injectorGet(import30.IterableDiffers,this.parentIndex),this.renderer,this.compView_29.ref);
    this._query_Header_29_0 = new import22.QueryList<any>();
    this._query_Footer_29_1 = new import22.QueryList<any>();
    this._query_PrimeTemplate_29_2 = new import22.QueryList<any>();
    this._query_Column_29_3 = new import22.QueryList<any>();
    this._query_HeaderColumnGroup_29_4 = new import22.QueryList<any>();
    this._query_FooterColumnGroup_29_5 = new import22.QueryList<any>();
    this._text_30 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_31 = import3.createRenderElement(this.renderer,(null as any),'header',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_31 = new import28.View_Header0(this.viewUtils,this,31,this._el_31);
    this._Header_31_3 = new import28.Wrapper_Header();
    this._text_32 = this.renderer.createText((null as any),'User Groups',(null as any));
    this.compView_31.create(this._Header_31_3.context);
    this._text_33 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_34 = import3.createRenderElement(this.renderer,(null as any),'p-column',new import3.InlineArray4(4,'field','groupName','header','Name'),(null as any));
    this.compView_34 = new import28.View_Column0(this.viewUtils,this,34,this._el_34);
    this._Column_34_3 = new import28.Wrapper_Column();
    this._query_PrimeTemplate_34_0 = new import22.QueryList<any>();
    this._query_TemplateRef_34_1 = new import22.QueryList<any>();
    this.compView_34.create(this._Column_34_3.context);
    this._text_35 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_36 = import3.createRenderElement(this.renderer,(null as any),'p-column',new import3.InlineArray4(4,'field','description','header','Description'),(null as any));
    this.compView_36 = new import28.View_Column0(this.viewUtils,this,36,this._el_36);
    this._Column_36_3 = new import28.Wrapper_Column();
    this._query_PrimeTemplate_36_0 = new import22.QueryList<any>();
    this._query_TemplateRef_36_1 = new import22.QueryList<any>();
    this.compView_36.create(this._Column_36_3.context);
    this._text_37 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_38 = import3.createRenderElement(this.renderer,(null as any),'footer',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_38 = new import28.View_Footer0(this.viewUtils,this,38,this._el_38);
    this._Footer_38_3 = new import28.Wrapper_Footer();
    this._text_39 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_40 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_41 = this.renderer.createText(this._el_40,'\n        ',(null as any));
    this._el_42 = import3.createRenderElement(this.renderer,this._el_40,'div',new import3.InlineArray2(2,'class','col-md-12'),(null as any));
    this._text_43 = this.renderer.createText(this._el_42,'\n          ',(null as any));
    this._anchor_44 = this.renderer.createTemplateAnchor(this._el_42,(null as any));
    this._vc_44 = new import13.ViewContainer(44,42,this,this._anchor_44);
    this._TemplateRef_44_5 = new import29.TemplateRef_(this,44,this._anchor_44);
    this._NgIf_44_6 = new import23.Wrapper_NgIf(this._vc_44.vcRef,this._TemplateRef_44_5);
    this._text_45 = this.renderer.createText(this._el_42,'\n          ',(null as any));
    this._el_46 = import3.createRenderElement(this.renderer,this._el_42,'button',new import3.InlineArray4(4,'color','primary','md-raised-button',''),(null as any));
    this.compView_46 = new import12.View_MdButton0(this.viewUtils,this,46,this._el_46);
    this._MdButton_46_3 = new import12.Wrapper_MdButton(new import14.ElementRef(this._el_46),this.renderer);
    this._text_47 = this.renderer.createText((null as any),'Import',(null as any));
    this.compView_46.create(this._MdButton_46_3.context);
    this._text_48 = this.renderer.createText(this._el_42,'\n        ',(null as any));
    this._text_49 = this.renderer.createText(this._el_40,'\n      ',(null as any));
    this._text_50 = this.renderer.createText((null as any),'\n    ',(null as any));
    this.compView_38.create(this._Footer_38_3.context);
    this._text_51 = this.renderer.createText((null as any),'\n  ',(null as any));
    this.compView_29.create(this._DataTable_29_4.context);
    this._text_52 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_9,new import3.InlineArray4(4,'ngModelChange',(null as any),'click',(null as any)),this.eventHandler(this.handleEvent_9));
    this._NgModel_9_5.subscribe(this,this.eventHandler(this.handleEvent_9),true);
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_13,new import3.InlineArray4(4,'ngModelChange',(null as any),'click',(null as any)),this.eventHandler(this.handleEvent_13));
    this._NgModel_13_5.subscribe(this,this.eventHandler(this.handleEvent_13),true);
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_20,new import3.InlineArray8(8,'click',(null as any),'mousedown',(null as any),'focus',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_20));
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_29,new import3.InlineArray2(2,'onRowSelect',(null as any)),this.eventHandler(this.handleEvent_29));
    this._DataTable_29_4.subscribe(this,this.eventHandler(this.handleEvent_29),false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false);
    var disposable_4:Function = import3.subscribeToRenderElement(this,this._el_46,new import3.InlineArray8(6,'mousedown',(null as any),'focus',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_46));
    this._query_MdPlaceholder_9_0.reset(([] as any[]));
    this._MdInput_9_3.context._placeholderChild = this._query_MdPlaceholder_9_0.first;
    this._query_MdPlaceholder_13_0.reset(([] as any[]));
    this._MdInput_13_3.context._placeholderChild = this._query_MdPlaceholder_13_0.first;
    this._query_Header_29_0.reset([this._Header_31_3.context]);
    this._DataTable_29_4.context.header = this._query_Header_29_0.first;
    this._query_Footer_29_1.reset([this._Footer_38_3.context]);
    this._DataTable_29_4.context.footer = this._query_Footer_29_1.first;
    this._query_HeaderColumnGroup_29_4.reset(([] as any[]));
    this._DataTable_29_4.context.headerColumnGroup = this._query_HeaderColumnGroup_29_4.first;
    this._query_FooterColumnGroup_29_5.reset(([] as any[]));
    this._DataTable_29_4.context.footerColumnGroup = this._query_FooterColumnGroup_29_5.first;
    this._query_TemplateRef_34_1.reset(([] as any[]));
    this._Column_34_3.context.template = this._query_TemplateRef_34_1.first;
    this._query_TemplateRef_36_1.reset(([] as any[]));
    this._Column_36_3.context.template = this._query_TemplateRef_36_1.first;
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._anchor_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._anchor_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._text_48,
      this._text_49,
      this._text_50,
      this._text_51,
      this._text_52
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.MdCardTitle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._MdCardTitle_4_3.context; }
    if (((token === import31.StyleCompatibility) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._StyleCompatibility_4_4.context; }
    if (((token === import18.MdInput) && (9 === requestNodeIndex))) { return this._MdInput_9_3.context; }
    if (((token === import32.NG_VALUE_ACCESSOR) && (9 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_9_4; }
    if (((token === import33.NgModel) && (9 === requestNodeIndex))) { return this._NgModel_9_5.context; }
    if (((token === import34.NgControl) && (9 === requestNodeIndex))) { return this._NgControl_9_6; }
    if (((token === import35.NgControlStatus) && (9 === requestNodeIndex))) { return this._NgControlStatus_9_7.context; }
    if (((token === import31.StyleCompatibility) && (9 === requestNodeIndex))) { return this._StyleCompatibility_9_8.context; }
    if (((token === import18.MdInput) && (13 === requestNodeIndex))) { return this._MdInput_13_3.context; }
    if (((token === import32.NG_VALUE_ACCESSOR) && (13 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_13_4; }
    if (((token === import33.NgModel) && (13 === requestNodeIndex))) { return this._NgModel_13_5.context; }
    if (((token === import34.NgControl) && (13 === requestNodeIndex))) { return this._NgControl_13_6; }
    if (((token === import35.NgControlStatus) && (13 === requestNodeIndex))) { return this._NgControlStatus_13_7.context; }
    if (((token === import31.StyleCompatibility) && (13 === requestNodeIndex))) { return this._StyleCompatibility_13_8.context; }
    if (((token === import15.MdCardContent) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._MdCardContent_7_3.context; }
    if (((token === import31.StyleCompatibility) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._StyleCompatibility_7_4.context; }
    if (((token === import29.TemplateRef) && (18 === requestNodeIndex))) { return this._TemplateRef_18_5; }
    if (((token === import36.NgIf) && (18 === requestNodeIndex))) { return this._NgIf_18_6.context; }
    if (((token === import11.MdButton) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._MdButton_20_3.context; }
    if (((token === import15.MdCardActions) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._MdCardActions_16_3.context; }
    if (((token === import31.StyleCompatibility) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._StyleCompatibility_16_4.context; }
    if (((token === import15.MdCard) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._MdCard_2_3.context; }
    if (((token === import31.StyleCompatibility) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._StyleCompatibility_2_4.context; }
    if (((token === import27.Header) && ((31 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._Header_31_3.context; }
    if (((token === import27.Column) && (34 === requestNodeIndex))) { return this._Column_34_3.context; }
    if (((token === import27.Column) && (36 === requestNodeIndex))) { return this._Column_36_3.context; }
    if (((token === import29.TemplateRef) && (44 === requestNodeIndex))) { return this._TemplateRef_44_5; }
    if (((token === import36.NgIf) && (44 === requestNodeIndex))) { return this._NgIf_44_6.context; }
    if (((token === import11.MdButton) && ((46 <= requestNodeIndex) && (requestNodeIndex <= 47)))) { return this._MdButton_46_3.context; }
    if (((token === import27.Footer) && ((38 <= requestNodeIndex) && (requestNodeIndex <= 50)))) { return this._Footer_38_3.context; }
    if (((token === import25.DomHandler) && ((29 <= requestNodeIndex) && (requestNodeIndex <= 51)))) { return this._DomHandler_29_3; }
    if (((token === import24.DataTable) && ((29 <= requestNodeIndex) && (requestNodeIndex <= 51)))) { return this._DataTable_29_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._MdCard_2_3.ngDoCheck(this,this._el_2,throwOnChange)) { this.compView_2.markAsCheckOnce(); }
    this._StyleCompatibility_2_4.ngDoCheck(this,this._el_2,throwOnChange);
    this._MdCardTitle_4_3.ngDoCheck(this,this._el_4,throwOnChange);
    this._StyleCompatibility_4_4.ngDoCheck(this,this._el_4,throwOnChange);
    this._MdCardContent_7_3.ngDoCheck(this,this._el_7,throwOnChange);
    this._StyleCompatibility_7_4.ngDoCheck(this,this._el_7,throwOnChange);
    const currVal_9_0_0:any = 'Name';
    this._MdInput_9_3.check_placeholder(currVal_9_0_0,throwOnChange,false);
    this._MdInput_9_3.ngDoCheck(this,this._el_9,throwOnChange);
    const currVal_9_1_0:any = this.parentView.context.userGroupSearchCriteria.groupName;
    this._NgModel_9_5.check_model(currVal_9_1_0,throwOnChange,false);
    this._NgModel_9_5.ngDoCheck(this,this._el_9,throwOnChange);
    this._NgControlStatus_9_7.ngDoCheck(this,this._el_9,throwOnChange);
    this._StyleCompatibility_9_8.ngDoCheck(this,this._el_9,throwOnChange);
    const currVal_13_0_0:any = 'Description';
    this._MdInput_13_3.check_placeholder(currVal_13_0_0,throwOnChange,false);
    this._MdInput_13_3.ngDoCheck(this,this._el_13,throwOnChange);
    const currVal_13_1_0:any = this.parentView.context.userGroupSearchCriteria.description;
    this._NgModel_13_5.check_model(currVal_13_1_0,throwOnChange,false);
    this._NgModel_13_5.ngDoCheck(this,this._el_13,throwOnChange);
    this._NgControlStatus_13_7.ngDoCheck(this,this._el_13,throwOnChange);
    this._StyleCompatibility_13_8.ngDoCheck(this,this._el_13,throwOnChange);
    this._MdCardActions_16_3.ngDoCheck(this,this._el_16,throwOnChange);
    this._StyleCompatibility_16_4.ngDoCheck(this,this._el_16,throwOnChange);
    const currVal_18_0_0:any = this.parentView.context.authorizationService.isUserHasRole('UI_USER_GROUPS_ACCESS');
    this._NgIf_18_6.check_ngIf(currVal_18_0_0,throwOnChange,false);
    this._NgIf_18_6.ngDoCheck(this,this._anchor_18,throwOnChange);
    const currVal_20_0_0:any = 'primary';
    this._MdButton_20_3.check_color(currVal_20_0_0,throwOnChange,false);
    if (this._MdButton_20_3.ngDoCheck(this,this._el_20,throwOnChange)) { this.compView_20.markAsCheckOnce(); }
    const currVal_29_0_0:any = this.parentView.context.userGroups;
    this._DataTable_29_4.check_value(currVal_29_0_0,throwOnChange,false);
    const currVal_29_0_1:any = true;
    this._DataTable_29_4.check_responsive(currVal_29_0_1,throwOnChange,false);
    const currVal_29_0_2:any = 'single';
    this._DataTable_29_4.check_selectionMode(currVal_29_0_2,throwOnChange,false);
    this._DataTable_29_4.ngDoCheck(this,this._el_29,throwOnChange);
    this._Header_31_3.ngDoCheck(this,this._el_31,throwOnChange);
    const currVal_34_0_0:any = 'groupName';
    this._Column_34_3.check_field(currVal_34_0_0,throwOnChange,false);
    const currVal_34_0_1:any = 'Name';
    this._Column_34_3.check_header(currVal_34_0_1,throwOnChange,false);
    const currVal_34_0_2:any = true;
    this._Column_34_3.check_sortable(currVal_34_0_2,throwOnChange,false);
    const currVal_34_0_3:any = true;
    this._Column_34_3.check_filter(currVal_34_0_3,throwOnChange,false);
    this._Column_34_3.ngDoCheck(this,this._el_34,throwOnChange);
    const currVal_36_0_0:any = 'description';
    this._Column_36_3.check_field(currVal_36_0_0,throwOnChange,false);
    const currVal_36_0_1:any = 'Description';
    this._Column_36_3.check_header(currVal_36_0_1,throwOnChange,false);
    const currVal_36_0_2:any = true;
    this._Column_36_3.check_sortable(currVal_36_0_2,throwOnChange,false);
    const currVal_36_0_3:any = true;
    this._Column_36_3.check_filter(currVal_36_0_3,throwOnChange,false);
    this._Column_36_3.ngDoCheck(this,this._el_36,throwOnChange);
    this._Footer_38_3.ngDoCheck(this,this._el_38,throwOnChange);
    const currVal_44_0_0:any = this.parentView.context.authorizationService.isUserHasRole('UI_USER_GROUPS_CREATE');
    this._NgIf_44_6.check_ngIf(currVal_44_0_0,throwOnChange,false);
    this._NgIf_44_6.ngDoCheck(this,this._anchor_44,throwOnChange);
    const currVal_46_0_0:any = 'primary';
    this._MdButton_46_3.check_color(currVal_46_0_0,throwOnChange,false);
    if (this._MdButton_46_3.ngDoCheck(this,this._el_46,throwOnChange)) { this.compView_46.markAsCheckOnce(); }
    this._vc_18.detectChangesInNestedViews(throwOnChange);
    this._vc_44.detectChangesInNestedViews(throwOnChange);
    if (!throwOnChange) {
      if (this._query_MdHint_9_1.dirty) {
        this._query_MdHint_9_1.reset(([] as any[]));
        this._MdInput_9_3.context._hintChildren = this._query_MdHint_9_1;
        this._query_MdHint_9_1.notifyOnChanges();
      }
      if (this._query_MdHint_13_1.dirty) {
        this._query_MdHint_13_1.reset(([] as any[]));
        this._MdInput_13_3.context._hintChildren = this._query_MdHint_13_1;
        this._query_MdHint_13_1.notifyOnChanges();
      }
      if (this._query_PrimeTemplate_29_2.dirty) {
        this._query_PrimeTemplate_29_2.reset(([] as any[]));
        this._DataTable_29_4.context.templates = this._query_PrimeTemplate_29_2;
        this._query_PrimeTemplate_29_2.notifyOnChanges();
      }
      if (this._query_Column_29_3.dirty) {
        this._query_Column_29_3.reset([
          this._Column_34_3.context,
          this._Column_36_3.context
        ]
        );
        this._DataTable_29_4.context.cols = this._query_Column_29_3;
        this._query_Column_29_3.notifyOnChanges();
      }
      if (this._query_PrimeTemplate_34_0.dirty) {
        this._query_PrimeTemplate_34_0.reset(([] as any[]));
        this._Column_34_3.context.templates = this._query_PrimeTemplate_34_0;
        this._query_PrimeTemplate_34_0.notifyOnChanges();
      }
      if (this._query_PrimeTemplate_36_0.dirty) {
        this._query_PrimeTemplate_36_0.reset(([] as any[]));
        this._Column_36_3.context.templates = this._query_PrimeTemplate_36_0;
        this._query_PrimeTemplate_36_0.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._MdInput_9_3.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._MdInput_13_3.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Column_34_3.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Column_36_3.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._DataTable_29_4.context.ngAfterContentInit(); }
    }
    this._MdInput_9_3.checkHost(this,this.compView_9,this._el_9,throwOnChange);
    this._NgControlStatus_9_7.checkHost(this,this.compView_9,this._el_9,throwOnChange);
    this._MdInput_13_3.checkHost(this,this.compView_13,this._el_13,throwOnChange);
    this._NgControlStatus_13_7.checkHost(this,this.compView_13,this._el_13,throwOnChange);
    this._MdButton_20_3.checkHost(this,this.compView_20,this._el_20,throwOnChange);
    this._MdButton_46_3.checkHost(this,this.compView_46,this._el_46,throwOnChange);
    this.compView_2.internalDetectChanges(throwOnChange);
    this.compView_9.internalDetectChanges(throwOnChange);
    this.compView_13.internalDetectChanges(throwOnChange);
    this.compView_20.internalDetectChanges(throwOnChange);
    this.compView_29.internalDetectChanges(throwOnChange);
    this.compView_31.internalDetectChanges(throwOnChange);
    this.compView_34.internalDetectChanges(throwOnChange);
    this.compView_36.internalDetectChanges(throwOnChange);
    this.compView_38.internalDetectChanges(throwOnChange);
    this.compView_46.internalDetectChanges(throwOnChange);
    if (!throwOnChange) {
      if ((this.numberOfChecks === 0)) { this._DataTable_29_4.context.ngAfterViewInit(); }
      this._DataTable_29_4.context.ngAfterViewChecked();
    }
  }
  destroyInternal():void {
    this._vc_18.destroyNestedViews();
    this._vc_44.destroyNestedViews();
    this.compView_2.destroy();
    this.compView_9.destroy();
    this.compView_13.destroy();
    this.compView_20.destroy();
    this.compView_29.destroy();
    this.compView_31.destroy();
    this.compView_34.destroy();
    this.compView_36.destroy();
    this.compView_38.destroy();
    this.compView_46.destroy();
    this._MdInput_9_3.ngOnDestroy();
    this._NgModel_9_5.ngOnDestroy();
    this._MdInput_13_3.ngOnDestroy();
    this._NgModel_13_5.ngOnDestroy();
    this._Column_34_3.ngOnDestroy();
    this._Column_36_3.ngOnDestroy();
    this._DataTable_29_4.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 2) && (ngContentIndex == 0))) {
      cb(this._text_3,ctx);
      cb(this._el_4,ctx);
      cb(this._text_6,ctx);
      cb(this._el_7,ctx);
      cb(this._text_15,ctx);
      cb(this._el_16,ctx);
      cb(this._text_23,ctx);
    }
    if (((nodeIndex == 9) && (ngContentIndex == 0))) {  }
    if (((nodeIndex == 9) && (ngContentIndex == 1))) {  }
    if (((nodeIndex == 9) && (ngContentIndex == 2))) {  }
    if (((nodeIndex == 9) && (ngContentIndex == 3))) {  }
    if (((nodeIndex == 13) && (ngContentIndex == 0))) {  }
    if (((nodeIndex == 13) && (ngContentIndex == 1))) {  }
    if (((nodeIndex == 13) && (ngContentIndex == 2))) {  }
    if (((nodeIndex == 13) && (ngContentIndex == 3))) {  }
    if (((nodeIndex == 20) && (ngContentIndex == 0))) { cb(this._text_21,ctx); }
    if (((nodeIndex == 29) && (ngContentIndex == 0))) { cb(this._el_31,ctx); }
    if (((nodeIndex == 29) && (ngContentIndex == 1))) { cb(this._el_38,ctx); }
    if (((nodeIndex == 31) && (ngContentIndex == 0))) { cb(this._text_32,ctx); }
    if (((nodeIndex == 38) && (ngContentIndex == 0))) {
      cb(this._text_39,ctx);
      cb(this._el_40,ctx);
      cb(this._text_50,ctx);
    }
    if (((nodeIndex == 46) && (ngContentIndex == 0))) { cb(this._text_47,ctx); }
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 18)) { return new View_UserGroupComponent2(this.viewUtils,this,18,this._anchor_18,this._vc_18); }
    if ((nodeIndex == 44)) { return new View_UserGroupComponent3(this.viewUtils,this,44,this._anchor_44,this._vc_44); }
    return (null as any);
  }
  handleEvent_9(eventName:string,$event:any):boolean {
    this.compView_9.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdInput_9_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.parentView.context.userGroupSearchCriteria.groupName = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_13(eventName:string,$event:any):boolean {
    this.compView_13.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdInput_13_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.parentView.context.userGroupSearchCriteria.description = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_20(eventName:string,$event:any):boolean {
    this.compView_20.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdButton_20_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.resetSearchCriteria()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_29(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'onRowSelect')) {
      const pd_sub_0:any = ((<any>this.parentView.context.onRowSelect($event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_46(eventName:string,$event:any):boolean {
    this.compView_46.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdButton_46_3.handleEvent(eventName,$event) && result);
    return result;
  }
}
class View_UserGroupComponent5 extends import1.AppView<any> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _text_5:any;
  _text_6:any;
  /*private*/ _expr_7:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import13.ViewContainer) {
    super(View_UserGroupComponent5,renderType_UserGroupComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_7 = import37.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._text_0 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','ui-helper-clearfix'),(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'\n              ',(null as any));
    this._el_3 = import3.createRenderElement(this.renderer,this._el_1,'div',new import3.InlineArray2(2,'style','font-size:14px;float:center;margin:15px 5px 0 0'),(null as any));
    this._text_4 = this.renderer.createText(this._el_3,'',(null as any));
    this._text_5 = this.renderer.createText(this._el_1,'\n            ',(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n          ',(null as any));
    this.init(this._text_6,((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._text_5,
      this._text_6
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_7:any = import3.inlineInterpolate(1,'',this.context.$implicit.userRole.roleName,'');
    if (import3.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setText(this._text_4,currVal_7);
      this._expr_7 = currVal_7;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._text_0,ctx);
    cb(this._el_1,ctx);
    cb(this._text_6,ctx);
  }
}
class View_UserGroupComponent6 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import11.MdButton>;
  _MdButton_0_3:import12.Wrapper_MdButton;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import13.ViewContainer) {
    super(View_UserGroupComponent6,renderType_UserGroupComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'button',new import3.InlineArray4(4,'color','primary','md-raised-button',''),(null as any));
    this.compView_0 = new import12.View_MdButton0(this.viewUtils,this,0,this._el_0);
    this._MdButton_0_3 = new import12.Wrapper_MdButton(new import14.ElementRef(this._el_0),this.renderer);
    this._text_1 = this.renderer.createText((null as any),'Submit',(null as any));
    this.compView_0.create(this._MdButton_0_3.context);
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray8(8,'click',(null as any),'mousedown',(null as any),'focus',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_0));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import11.MdButton) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._MdButton_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = 'primary';
    this._MdButton_0_3.check_color(currVal_0_0_0,throwOnChange,false);
    if (this._MdButton_0_3.ngDoCheck(this,this._el_0,throwOnChange)) { this.compView_0.markAsCheckOnce(); }
    this._MdButton_0_3.checkHost(this,this.compView_0,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 0) && (ngContentIndex == 0))) { cb(this._text_1,ctx); }
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.compView_0.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdButton_0_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.parentView.context.submitNewUserGroup()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_UserGroupComponent7 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import11.MdButton>;
  _MdButton_0_3:import12.Wrapper_MdButton;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import13.ViewContainer) {
    super(View_UserGroupComponent7,renderType_UserGroupComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'button',new import3.InlineArray4(4,'color','primary','md-raised-button',''),(null as any));
    this.compView_0 = new import12.View_MdButton0(this.viewUtils,this,0,this._el_0);
    this._MdButton_0_3 = new import12.Wrapper_MdButton(new import14.ElementRef(this._el_0),this.renderer);
    this._text_1 = this.renderer.createText((null as any),'Delete',(null as any));
    this.compView_0.create(this._MdButton_0_3.context);
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray8(8,'click',(null as any),'mousedown',(null as any),'focus',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_0));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import11.MdButton) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._MdButton_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = 'primary';
    this._MdButton_0_3.check_color(currVal_0_0_0,throwOnChange,false);
    if (this._MdButton_0_3.ngDoCheck(this,this._el_0,throwOnChange)) { this.compView_0.markAsCheckOnce(); }
    this._MdButton_0_3.checkHost(this,this.compView_0,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 0) && (ngContentIndex == 0))) { cb(this._text_1,ctx); }
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.compView_0.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdButton_0_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.parentView.context.deleteNewUserGroup()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_UserGroupComponent4 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  compView_2:import1.AppView<import15.MdCard>;
  _MdCard_2_3:import16.Wrapper_MdCard;
  _StyleCompatibility_2_4:import17.Wrapper_StyleCompatibility;
  _text_3:any;
  _el_4:any;
  _MdCardTitle_4_3:import16.Wrapper_MdCardTitle;
  _StyleCompatibility_4_4:import17.Wrapper_StyleCompatibility;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _MdCardContent_7_3:import16.Wrapper_MdCardContent;
  _StyleCompatibility_7_4:import17.Wrapper_StyleCompatibility;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  compView_11:import1.AppView<import18.MdInput>;
  _MdInput_11_3:import19.Wrapper_MdInput;
  _NG_VALUE_ACCESSOR_11_4:any[];
  _NgModel_11_5:import20.Wrapper_NgModel;
  _NgControl_11_6:any;
  _NgControlStatus_11_7:import21.Wrapper_NgControlStatus;
  _StyleCompatibility_11_8:import17.Wrapper_StyleCompatibility;
  _query_MdPlaceholder_11_0:import22.QueryList<any>;
  _query_MdHint_11_1:import22.QueryList<any>;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  compView_15:import1.AppView<import18.MdInput>;
  _MdInput_15_3:import19.Wrapper_MdInput;
  _NG_VALUE_ACCESSOR_15_4:any[];
  _NgModel_15_5:import20.Wrapper_NgModel;
  _NgControl_15_6:any;
  _NgControlStatus_15_7:import21.Wrapper_NgControlStatus;
  _StyleCompatibility_15_8:import17.Wrapper_StyleCompatibility;
  _query_MdPlaceholder_15_0:import22.QueryList<any>;
  _query_MdHint_15_1:import22.QueryList<any>;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _el_24:any;
  compView_24:import1.AppView<import38.PickList>;
  _DomHandler_24_3:import25.DomHandler;
  _PickList_24_4:import39.Wrapper_PickList;
  _query_TemplateRef_24_0:import22.QueryList<any>;
  _text_25:any;
  _anchor_26:any;
  /*private*/ _vc_26:import13.ViewContainer;
  _TemplateRef_26_4:any;
  _text_27:any;
  _text_28:any;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  _MdCardActions_31_3:import16.Wrapper_MdCardActions;
  _StyleCompatibility_31_4:import17.Wrapper_StyleCompatibility;
  _text_32:any;
  _anchor_33:any;
  /*private*/ _vc_33:import13.ViewContainer;
  _TemplateRef_33_5:any;
  _NgIf_33_6:import23.Wrapper_NgIf;
  _text_34:any;
  _anchor_35:any;
  /*private*/ _vc_35:import13.ViewContainer;
  _TemplateRef_35_5:any;
  _NgIf_35_6:import23.Wrapper_NgIf;
  _text_36:any;
  _el_37:any;
  compView_37:import1.AppView<import11.MdButton>;
  _MdButton_37_3:import12.Wrapper_MdButton;
  _text_38:any;
  _text_39:any;
  _text_40:any;
  _text_41:any;
  _map_83:any;
  _map_84:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import13.ViewContainer) {
    super(View_UserGroupComponent4,renderType_UserGroupComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._map_83 = import3.pureProxy1((p0:any):{[key: string]:any} => {
      return {height: p0};
    });
    this._map_84 = import3.pureProxy1((p0:any):{[key: string]:any} => {
      return {height: p0};
    });
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'md-card',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_2 = new import16.View_MdCard0(this.viewUtils,this,2,this._el_2);
    this._MdCard_2_3 = new import16.Wrapper_MdCard();
    this._StyleCompatibility_2_4 = new import17.Wrapper_StyleCompatibility(this.renderer,new import14.ElementRef(this._el_2));
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,(null as any),'md-card-title',new import3.InlineArray2(2,'color','primary'),(null as any));
    this._MdCardTitle_4_3 = new import16.Wrapper_MdCardTitle();
    this._StyleCompatibility_4_4 = new import17.Wrapper_StyleCompatibility(this.renderer,new import14.ElementRef(this._el_4));
    this._text_5 = this.renderer.createText(this._el_4,'Create User Group',(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,(null as any),'md-card-content',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._MdCardContent_7_3 = new import16.Wrapper_MdCardContent();
    this._StyleCompatibility_7_4 = new import17.Wrapper_StyleCompatibility(this.renderer,new import14.ElementRef(this._el_7));
    this._text_8 = this.renderer.createText(this._el_7,'\n      ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_7,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'\n        ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_9,'md-input',new import3.InlineArray4(4,'class','col-md-5','placeholder','Name'),(null as any));
    this.compView_11 = new import19.View_MdInput0(this.viewUtils,this,11,this._el_11);
    this._MdInput_11_3 = new import19.Wrapper_MdInput(new import14.ElementRef(this._el_11));
    this._NG_VALUE_ACCESSOR_11_4 = [this._MdInput_11_3.context];
    this._NgModel_11_5 = new import20.Wrapper_NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_11_4);
    this._NgControl_11_6 = this._NgModel_11_5.context;
    this._NgControlStatus_11_7 = new import21.Wrapper_NgControlStatus(this._NgControl_11_6);
    this._StyleCompatibility_11_8 = new import17.Wrapper_StyleCompatibility(this.renderer,new import14.ElementRef(this._el_11));
    this._query_MdPlaceholder_11_0 = new import22.QueryList<any>();
    this._query_MdHint_11_1 = new import22.QueryList<any>();
    this.compView_11.create(this._MdInput_11_3.context);
    this._text_12 = this.renderer.createText(this._el_9,'\n        ',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,this._el_9,'div',new import3.InlineArray2(2,'class','col-md-2'),(null as any));
    this._text_14 = this.renderer.createText(this._el_9,'\n        ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_9,'md-input',new import3.InlineArray4(4,'class','col-md-5','placeholder','Description'),(null as any));
    this.compView_15 = new import19.View_MdInput0(this.viewUtils,this,15,this._el_15);
    this._MdInput_15_3 = new import19.Wrapper_MdInput(new import14.ElementRef(this._el_15));
    this._NG_VALUE_ACCESSOR_15_4 = [this._MdInput_15_3.context];
    this._NgModel_15_5 = new import20.Wrapper_NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_15_4);
    this._NgControl_15_6 = this._NgModel_15_5.context;
    this._NgControlStatus_15_7 = new import21.Wrapper_NgControlStatus(this._NgControl_15_6);
    this._StyleCompatibility_15_8 = new import17.Wrapper_StyleCompatibility(this.renderer,new import14.ElementRef(this._el_15));
    this._query_MdPlaceholder_15_0 = new import22.QueryList<any>();
    this._query_MdHint_15_1 = new import22.QueryList<any>();
    this.compView_15.create(this._MdInput_15_3.context);
    this._text_16 = this.renderer.createText(this._el_9,'\n      ',(null as any));
    this._text_17 = this.renderer.createText(this._el_7,'\n      ',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_7,'br',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_19 = this.renderer.createText(this._el_7,'\n      ',(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,this._el_7,'br',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_21 = this.renderer.createText(this._el_7,'\n      ',(null as any));
    this._el_22 = import3.createRenderElement(this.renderer,this._el_7,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_23 = this.renderer.createText(this._el_22,'\n        ',(null as any));
    this._el_24 = import3.createRenderElement(this.renderer,this._el_22,'p-pickList',new import3.InlineArray4(4,'sourceHeader','Available Roles','targetHeader','Selected Roles'),(null as any));
    this.compView_24 = new import39.View_PickList0(this.viewUtils,this,24,this._el_24);
    this._DomHandler_24_3 = new import25.DomHandler();
    this._PickList_24_4 = new import39.Wrapper_PickList(new import14.ElementRef(this._el_24),this._DomHandler_24_3);
    this._query_TemplateRef_24_0 = new import22.QueryList<any>();
    this._text_25 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._anchor_26 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._vc_26 = new import13.ViewContainer(26,24,this,this._anchor_26);
    this._TemplateRef_26_4 = new import29.TemplateRef_(this,26,this._anchor_26);
    this._text_27 = this.renderer.createText((null as any),'\n        ',(null as any));
    this.compView_24.create(this._PickList_24_4.context);
    this._text_28 = this.renderer.createText(this._el_22,'\n      ',(null as any));
    this._text_29 = this.renderer.createText(this._el_7,'\n    ',(null as any));
    this._text_30 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_31 = import3.createRenderElement(this.renderer,(null as any),'md-card-actions',new import3.InlineArray2(2,'class','center'),(null as any));
    this._MdCardActions_31_3 = new import16.Wrapper_MdCardActions();
    this._StyleCompatibility_31_4 = new import17.Wrapper_StyleCompatibility(this.renderer,new import14.ElementRef(this._el_31));
    this._text_32 = this.renderer.createText(this._el_31,'\n      ',(null as any));
    this._anchor_33 = this.renderer.createTemplateAnchor(this._el_31,(null as any));
    this._vc_33 = new import13.ViewContainer(33,31,this,this._anchor_33);
    this._TemplateRef_33_5 = new import29.TemplateRef_(this,33,this._anchor_33);
    this._NgIf_33_6 = new import23.Wrapper_NgIf(this._vc_33.vcRef,this._TemplateRef_33_5);
    this._text_34 = this.renderer.createText(this._el_31,'\n      ',(null as any));
    this._anchor_35 = this.renderer.createTemplateAnchor(this._el_31,(null as any));
    this._vc_35 = new import13.ViewContainer(35,31,this,this._anchor_35);
    this._TemplateRef_35_5 = new import29.TemplateRef_(this,35,this._anchor_35);
    this._NgIf_35_6 = new import23.Wrapper_NgIf(this._vc_35.vcRef,this._TemplateRef_35_5);
    this._text_36 = this.renderer.createText(this._el_31,'\n      ',(null as any));
    this._el_37 = import3.createRenderElement(this.renderer,this._el_31,'button',new import3.InlineArray4(4,'color','primary','md-raised-button',''),(null as any));
    this.compView_37 = new import12.View_MdButton0(this.viewUtils,this,37,this._el_37);
    this._MdButton_37_3 = new import12.Wrapper_MdButton(new import14.ElementRef(this._el_37),this.renderer);
    this._text_38 = this.renderer.createText((null as any),'Back',(null as any));
    this.compView_37.create(this._MdButton_37_3.context);
    this._text_39 = this.renderer.createText(this._el_31,'\n    ',(null as any));
    this._text_40 = this.renderer.createText((null as any),'\n  ',(null as any));
    this.compView_2.create(this._MdCard_2_3.context);
    this._text_41 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_11,new import3.InlineArray4(4,'ngModelChange',(null as any),'click',(null as any)),this.eventHandler(this.handleEvent_11));
    this._NgModel_11_5.subscribe(this,this.eventHandler(this.handleEvent_11),true);
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_15,new import3.InlineArray4(4,'ngModelChange',(null as any),'click',(null as any)),this.eventHandler(this.handleEvent_15));
    this._NgModel_15_5.subscribe(this,this.eventHandler(this.handleEvent_15),true);
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_37,new import3.InlineArray8(8,'click',(null as any),'mousedown',(null as any),'focus',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_37));
    this._query_MdPlaceholder_11_0.reset(([] as any[]));
    this._MdInput_11_3.context._placeholderChild = this._query_MdPlaceholder_11_0.first;
    this._query_MdPlaceholder_15_0.reset(([] as any[]));
    this._MdInput_15_3.context._placeholderChild = this._query_MdPlaceholder_15_0.first;
    this._query_TemplateRef_24_0.reset([this._TemplateRef_26_4]);
    this._PickList_24_4.context.itemTemplate = this._query_TemplateRef_24_0.first;
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._anchor_26,
      this._text_27,
      this._text_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._anchor_33,
      this._text_34,
      this._anchor_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._text_39,
      this._text_40,
      this._text_41
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.MdCardTitle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._MdCardTitle_4_3.context; }
    if (((token === import31.StyleCompatibility) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._StyleCompatibility_4_4.context; }
    if (((token === import18.MdInput) && (11 === requestNodeIndex))) { return this._MdInput_11_3.context; }
    if (((token === import32.NG_VALUE_ACCESSOR) && (11 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_11_4; }
    if (((token === import33.NgModel) && (11 === requestNodeIndex))) { return this._NgModel_11_5.context; }
    if (((token === import34.NgControl) && (11 === requestNodeIndex))) { return this._NgControl_11_6; }
    if (((token === import35.NgControlStatus) && (11 === requestNodeIndex))) { return this._NgControlStatus_11_7.context; }
    if (((token === import31.StyleCompatibility) && (11 === requestNodeIndex))) { return this._StyleCompatibility_11_8.context; }
    if (((token === import18.MdInput) && (15 === requestNodeIndex))) { return this._MdInput_15_3.context; }
    if (((token === import32.NG_VALUE_ACCESSOR) && (15 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_15_4; }
    if (((token === import33.NgModel) && (15 === requestNodeIndex))) { return this._NgModel_15_5.context; }
    if (((token === import34.NgControl) && (15 === requestNodeIndex))) { return this._NgControl_15_6; }
    if (((token === import35.NgControlStatus) && (15 === requestNodeIndex))) { return this._NgControlStatus_15_7.context; }
    if (((token === import31.StyleCompatibility) && (15 === requestNodeIndex))) { return this._StyleCompatibility_15_8.context; }
    if (((token === import29.TemplateRef) && (26 === requestNodeIndex))) { return this._TemplateRef_26_4; }
    if (((token === import25.DomHandler) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._DomHandler_24_3; }
    if (((token === import38.PickList) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._PickList_24_4.context; }
    if (((token === import15.MdCardContent) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._MdCardContent_7_3.context; }
    if (((token === import31.StyleCompatibility) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._StyleCompatibility_7_4.context; }
    if (((token === import29.TemplateRef) && (33 === requestNodeIndex))) { return this._TemplateRef_33_5; }
    if (((token === import36.NgIf) && (33 === requestNodeIndex))) { return this._NgIf_33_6.context; }
    if (((token === import29.TemplateRef) && (35 === requestNodeIndex))) { return this._TemplateRef_35_5; }
    if (((token === import36.NgIf) && (35 === requestNodeIndex))) { return this._NgIf_35_6.context; }
    if (((token === import11.MdButton) && ((37 <= requestNodeIndex) && (requestNodeIndex <= 38)))) { return this._MdButton_37_3.context; }
    if (((token === import15.MdCardActions) && ((31 <= requestNodeIndex) && (requestNodeIndex <= 39)))) { return this._MdCardActions_31_3.context; }
    if (((token === import31.StyleCompatibility) && ((31 <= requestNodeIndex) && (requestNodeIndex <= 39)))) { return this._StyleCompatibility_31_4.context; }
    if (((token === import15.MdCard) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 40)))) { return this._MdCard_2_3.context; }
    if (((token === import31.StyleCompatibility) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 40)))) { return this._StyleCompatibility_2_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._MdCard_2_3.ngDoCheck(this,this._el_2,throwOnChange)) { this.compView_2.markAsCheckOnce(); }
    this._StyleCompatibility_2_4.ngDoCheck(this,this._el_2,throwOnChange);
    this._MdCardTitle_4_3.ngDoCheck(this,this._el_4,throwOnChange);
    this._StyleCompatibility_4_4.ngDoCheck(this,this._el_4,throwOnChange);
    this._MdCardContent_7_3.ngDoCheck(this,this._el_7,throwOnChange);
    this._StyleCompatibility_7_4.ngDoCheck(this,this._el_7,throwOnChange);
    const currVal_11_0_0:any = 'Name';
    this._MdInput_11_3.check_placeholder(currVal_11_0_0,throwOnChange,false);
    this._MdInput_11_3.ngDoCheck(this,this._el_11,throwOnChange);
    const currVal_11_1_0:any = this.parentView.context.selectedUserGroup.groupName;
    this._NgModel_11_5.check_model(currVal_11_1_0,throwOnChange,false);
    this._NgModel_11_5.ngDoCheck(this,this._el_11,throwOnChange);
    this._NgControlStatus_11_7.ngDoCheck(this,this._el_11,throwOnChange);
    this._StyleCompatibility_11_8.ngDoCheck(this,this._el_11,throwOnChange);
    const currVal_15_0_0:any = 'Description';
    this._MdInput_15_3.check_placeholder(currVal_15_0_0,throwOnChange,false);
    this._MdInput_15_3.ngDoCheck(this,this._el_15,throwOnChange);
    const currVal_15_1_0:any = this.parentView.context.selectedUserGroup.description;
    this._NgModel_15_5.check_model(currVal_15_1_0,throwOnChange,false);
    this._NgModel_15_5.ngDoCheck(this,this._el_15,throwOnChange);
    this._NgControlStatus_15_7.ngDoCheck(this,this._el_15,throwOnChange);
    this._StyleCompatibility_15_8.ngDoCheck(this,this._el_15,throwOnChange);
    const currVal_24_0_0:any = this.parentView.context.sourceUserGroupUserRoles;
    this._PickList_24_4.check_source(currVal_24_0_0,throwOnChange,false);
    const currVal_24_0_1:any = this.parentView.context.targetUserGroupUserRoles;
    this._PickList_24_4.check_target(currVal_24_0_1,throwOnChange,false);
    const currVal_24_0_2:any = 'Available Roles';
    this._PickList_24_4.check_sourceHeader(currVal_24_0_2,throwOnChange,false);
    const currVal_24_0_3:any = 'Selected Roles';
    this._PickList_24_4.check_targetHeader(currVal_24_0_3,throwOnChange,false);
    const currVal_24_0_4:any = true;
    this._PickList_24_4.check_responsive(currVal_24_0_4,throwOnChange,false);
    const currVal_24_0_5:any = this._map_83('300px');
    this._PickList_24_4.check_sourceStyle(currVal_24_0_5,throwOnChange,false);
    const currVal_24_0_6:any = this._map_84('300px');
    this._PickList_24_4.check_targetStyle(currVal_24_0_6,throwOnChange,false);
    this._PickList_24_4.ngDoCheck(this,this._el_24,throwOnChange);
    this._MdCardActions_31_3.ngDoCheck(this,this._el_31,throwOnChange);
    this._StyleCompatibility_31_4.ngDoCheck(this,this._el_31,throwOnChange);
    const currVal_33_0_0:any = this.parentView.context.authorizationService.isUserHasRole('UI_USER_GROUPS_UPDATE');
    this._NgIf_33_6.check_ngIf(currVal_33_0_0,throwOnChange,false);
    this._NgIf_33_6.ngDoCheck(this,this._anchor_33,throwOnChange);
    const currVal_35_0_0:any = this.parentView.context.authorizationService.isUserHasRole('UI_USER_GROUPS_DELETE');
    this._NgIf_35_6.check_ngIf(currVal_35_0_0,throwOnChange,false);
    this._NgIf_35_6.ngDoCheck(this,this._anchor_35,throwOnChange);
    const currVal_37_0_0:any = 'primary';
    this._MdButton_37_3.check_color(currVal_37_0_0,throwOnChange,false);
    if (this._MdButton_37_3.ngDoCheck(this,this._el_37,throwOnChange)) { this.compView_37.markAsCheckOnce(); }
    this._vc_26.detectChangesInNestedViews(throwOnChange);
    this._vc_33.detectChangesInNestedViews(throwOnChange);
    this._vc_35.detectChangesInNestedViews(throwOnChange);
    if (!throwOnChange) {
      if (this._query_MdHint_11_1.dirty) {
        this._query_MdHint_11_1.reset(([] as any[]));
        this._MdInput_11_3.context._hintChildren = this._query_MdHint_11_1;
        this._query_MdHint_11_1.notifyOnChanges();
      }
      if (this._query_MdHint_15_1.dirty) {
        this._query_MdHint_15_1.reset(([] as any[]));
        this._MdInput_15_3.context._hintChildren = this._query_MdHint_15_1;
        this._query_MdHint_15_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._MdInput_11_3.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._MdInput_15_3.context.ngAfterContentInit(); }
    }
    this._MdInput_11_3.checkHost(this,this.compView_11,this._el_11,throwOnChange);
    this._NgControlStatus_11_7.checkHost(this,this.compView_11,this._el_11,throwOnChange);
    this._MdInput_15_3.checkHost(this,this.compView_15,this._el_15,throwOnChange);
    this._NgControlStatus_15_7.checkHost(this,this.compView_15,this._el_15,throwOnChange);
    this._MdButton_37_3.checkHost(this,this.compView_37,this._el_37,throwOnChange);
    this.compView_2.internalDetectChanges(throwOnChange);
    this.compView_11.internalDetectChanges(throwOnChange);
    this.compView_15.internalDetectChanges(throwOnChange);
    this.compView_24.internalDetectChanges(throwOnChange);
    this.compView_37.internalDetectChanges(throwOnChange);
    if (!throwOnChange) { this._PickList_24_4.context.ngAfterViewChecked(); }
  }
  destroyInternal():void {
    this._vc_26.destroyNestedViews();
    this._vc_33.destroyNestedViews();
    this._vc_35.destroyNestedViews();
    this.compView_2.destroy();
    this.compView_11.destroy();
    this.compView_15.destroy();
    this.compView_24.destroy();
    this.compView_37.destroy();
    this._MdInput_11_3.ngOnDestroy();
    this._NgModel_11_5.ngOnDestroy();
    this._MdInput_15_3.ngOnDestroy();
    this._NgModel_15_5.ngOnDestroy();
    this._PickList_24_4.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 2) && (ngContentIndex == 0))) {
      cb(this._text_3,ctx);
      cb(this._el_4,ctx);
      cb(this._text_6,ctx);
      cb(this._el_7,ctx);
      cb(this._text_30,ctx);
      cb(this._el_31,ctx);
      cb(this._text_40,ctx);
    }
    if (((nodeIndex == 11) && (ngContentIndex == 0))) {  }
    if (((nodeIndex == 11) && (ngContentIndex == 1))) {  }
    if (((nodeIndex == 11) && (ngContentIndex == 2))) {  }
    if (((nodeIndex == 11) && (ngContentIndex == 3))) {  }
    if (((nodeIndex == 15) && (ngContentIndex == 0))) {  }
    if (((nodeIndex == 15) && (ngContentIndex == 1))) {  }
    if (((nodeIndex == 15) && (ngContentIndex == 2))) {  }
    if (((nodeIndex == 15) && (ngContentIndex == 3))) {  }
    if (((nodeIndex == 37) && (ngContentIndex == 0))) { cb(this._text_38,ctx); }
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 26)) { return new View_UserGroupComponent5(this.viewUtils,this,26,this._anchor_26,this._vc_26); }
    if ((nodeIndex == 33)) { return new View_UserGroupComponent6(this.viewUtils,this,33,this._anchor_33,this._vc_33); }
    if ((nodeIndex == 35)) { return new View_UserGroupComponent7(this.viewUtils,this,35,this._anchor_35,this._vc_35); }
    return (null as any);
  }
  handleEvent_11(eventName:string,$event:any):boolean {
    this.compView_11.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdInput_11_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.parentView.context.selectedUserGroup.groupName = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_15(eventName:string,$event:any):boolean {
    this.compView_15.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdInput_15_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.parentView.context.selectedUserGroup.description = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_37(eventName:string,$event:any):boolean {
    this.compView_37.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdButton_37_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.backToUserGroups()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
var renderType_UserGroupComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_UserGroupComponent,{});
export class View_UserGroupComponent0 extends import1.AppView<import0.UserGroupComponent> {
  _el_0:any;
  compView_0:import1.AppView<import40.Growl>;
  _DomHandler_0_3:import25.DomHandler;
  _Growl_0_4:import41.Wrapper_Growl;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _vc_2:import13.ViewContainer;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import23.Wrapper_NgIf;
  _text_3:any;
  _anchor_4:any;
  /*private*/ _vc_4:import13.ViewContainer;
  _TemplateRef_4_5:any;
  _NgIf_4_6:import23.Wrapper_NgIf;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_UserGroupComponent0,renderType_UserGroupComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'p-growl',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_0 = new import41.View_Growl0(this.viewUtils,this,0,this._el_0);
    this._DomHandler_0_3 = new import25.DomHandler();
    this._Growl_0_4 = new import41.Wrapper_Growl(new import14.ElementRef(this._el_0),this._DomHandler_0_3,this.parentView.injectorGet(import30.IterableDiffers,this.parentIndex));
    this.compView_0.create(this._Growl_0_4.context);
    this._text_1 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._vc_2 = new import13.ViewContainer(2,(null as any),this,this._anchor_2);
    this._TemplateRef_2_5 = new import29.TemplateRef_(this,2,this._anchor_2);
    this._NgIf_2_6 = new import23.Wrapper_NgIf(this._vc_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._anchor_4 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._vc_4 = new import13.ViewContainer(4,(null as any),this,this._anchor_4);
    this._TemplateRef_4_5 = new import29.TemplateRef_(this,4,this._anchor_4);
    this._NgIf_4_6 = new import23.Wrapper_NgIf(this._vc_4.vcRef,this._TemplateRef_4_5);
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3,
      this._anchor_4
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import25.DomHandler) && (0 === requestNodeIndex))) { return this._DomHandler_0_3; }
    if (((token === import40.Growl) && (0 === requestNodeIndex))) { return this._Growl_0_4.context; }
    if (((token === import29.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import36.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6.context; }
    if (((token === import29.TemplateRef) && (4 === requestNodeIndex))) { return this._TemplateRef_4_5; }
    if (((token === import36.NgIf) && (4 === requestNodeIndex))) { return this._NgIf_4_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this.context.msgs;
    this._Growl_0_4.check_value(currVal_0_0_0,throwOnChange,false);
    this._Growl_0_4.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_2_0_0:boolean = !this.context.displayUserGroupDetails;
    this._NgIf_2_6.check_ngIf(currVal_2_0_0,throwOnChange,false);
    this._NgIf_2_6.ngDoCheck(this,this._anchor_2,throwOnChange);
    const currVal_4_0_0:any = this.context.displayUserGroupDetails;
    this._NgIf_4_6.check_ngIf(currVal_4_0_0,throwOnChange,false);
    this._NgIf_4_6.ngDoCheck(this,this._anchor_4,throwOnChange);
    this._vc_2.detectChangesInNestedViews(throwOnChange);
    this._vc_4.detectChangesInNestedViews(throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Growl_0_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._vc_2.destroyNestedViews();
    this._vc_4.destroyNestedViews();
    this.compView_0.destroy();
    this._Growl_0_4.ngOnDestroy();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 2)) { return new View_UserGroupComponent1(this.viewUtils,this,2,this._anchor_2,this._vc_2); }
    if ((nodeIndex == 4)) { return new View_UserGroupComponent4(this.viewUtils,this,4,this._anchor_4,this._vc_4); }
    return (null as any);
  }
}