/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../src/app/email/email/email.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../../../../src/app/email/email/email.service';
import * as import9 from '../../../../../src/app/email/shared/common.service';
import * as import10 from '../../../../node_modules/@angular/forms/src/directives/ng_form.ngfactory';
import * as import11 from '../../../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import12 from 'primeng/components/multiselect/multiselect';
import * as import13 from '../../../../node_modules/@angular/forms/src/directives/validators.ngfactory';
import * as import14 from 'primeng/components/dom/domhandler';
import * as import15 from '../../../../node_modules/primeng/components/multiselect/multiselect.ngfactory';
import * as import16 from '../../../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import17 from '../../../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import18 from '../../../../node_modules/primeng/components/button/button.ngfactory';
import * as import19 from 'primeng/components/dialog/dialog';
import * as import20 from '../../../../node_modules/primeng/components/dialog/dialog.ngfactory';
import * as import21 from '@angular/core/src/linker/query_list';
import * as import22 from '@angular/core/src/linker/view_container';
import * as import23 from '@angular/core/src/change_detection/change_detection_util';
import * as import24 from '@angular/core/src/linker/element_ref';
import * as import25 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import26 from '@angular/forms/src/directives/validators';
import * as import27 from '@angular/forms/src/validators';
import * as import28 from '@angular/forms/src/directives/control_value_accessor';
import * as import29 from '@angular/forms/src/directives/ng_model';
import * as import30 from '@angular/forms/src/directives/ng_control';
import * as import31 from '@angular/forms/src/directives/ng_control_status';
import * as import32 from '@angular/forms/src/directives/default_value_accessor';
import * as import33 from 'primeng/components/button/button';
import * as import34 from '@angular/forms/src/directives/ng_form';
import * as import35 from '@angular/forms/src/directives/control_container';
import * as import36 from 'primeng/components/growl/growl';
import * as import37 from '../../../../node_modules/primeng/components/growl/growl.ngfactory';
import * as import38 from '../../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import39 from '@angular/core/src/linker/template_ref';
import * as import40 from '@angular/common/src/directives/ng_if';
export class Wrapper_EmailComponent {
  /*private*/ _eventHandler:Function;
  context:import0.EmailComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any) {
    this._changed = false;
    this.context = new import0.EmailComponent(p0,p1);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_EmailComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_EmailComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.EmailComponent>;
  _EmailComponent_0_3:Wrapper_EmailComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_EmailComponent_Host0,renderType_EmailComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'ng-component',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_EmailComponent0(this.viewUtils,this,0,this._el_0);
    this._EmailComponent_0_3 = new Wrapper_EmailComponent(this.injectorGet(import8.EmailService,this.parentIndex),this.injectorGet(import9.CommonService,this.parentIndex));
    this.compView_0.create(this._EmailComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._EmailComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.EmailComponent) && (0 === requestNodeIndex))) { return this._EmailComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._EmailComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const EmailComponentNgFactory:import7.ComponentFactory<import0.EmailComponent> = new import7.ComponentFactory<import0.EmailComponent>('ng-component',View_EmailComponent_Host0,import0.EmailComponent);
const styles_EmailComponent:any[] = ([] as any[]);
class View_EmailComponent1 extends import1.AppView<any> {
  _el_0:any;
  _NgForm_0_3:import10.Wrapper_NgForm;
  _ControlContainer_0_4:any;
  _NgControlStatusGroup_0_5:import11.Wrapper_NgControlStatusGroup;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  compView_23:import1.AppView<import12.MultiSelect>;
  _RequiredValidator_23_3:import13.Wrapper_RequiredValidator;
  _NG_VALIDATORS_23_4:any[];
  _DomHandler_23_5:import14.DomHandler;
  _MultiSelect_23_6:import15.Wrapper_MultiSelect;
  _NG_VALUE_ACCESSOR_23_7:any[];
  _NgModel_23_8:import16.Wrapper_NgModel;
  _NgControl_23_9:any;
  _NgControlStatus_23_10:import11.Wrapper_NgControlStatus;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _text_27:any;
  _text_28:any;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _text_39:any;
  _el_40:any;
  _DefaultValueAccessor_40_3:import17.Wrapper_DefaultValueAccessor;
  _RequiredValidator_40_4:import13.Wrapper_RequiredValidator;
  _NG_VALIDATORS_40_5:any[];
  _NG_VALUE_ACCESSOR_40_6:any[];
  _NgModel_40_7:import16.Wrapper_NgModel;
  _NgControl_40_8:any;
  _NgControlStatus_40_9:import11.Wrapper_NgControlStatus;
  _text_41:any;
  _el_42:any;
  _text_43:any;
  _text_44:any;
  _text_45:any;
  _text_46:any;
  _text_47:any;
  _el_48:any;
  _text_49:any;
  _el_50:any;
  _text_51:any;
  _el_52:any;
  _text_53:any;
  _text_54:any;
  _el_55:any;
  _DefaultValueAccessor_55_3:import17.Wrapper_DefaultValueAccessor;
  _RequiredValidator_55_4:import13.Wrapper_RequiredValidator;
  _NG_VALIDATORS_55_5:any[];
  _NG_VALUE_ACCESSOR_55_6:any[];
  _NgModel_55_7:import16.Wrapper_NgModel;
  _NgControl_55_8:any;
  _NgControlStatus_55_9:import11.Wrapper_NgControlStatus;
  _text_56:any;
  _el_57:any;
  _text_58:any;
  _text_59:any;
  _text_60:any;
  _text_61:any;
  _el_62:any;
  _text_63:any;
  _el_64:any;
  _text_65:any;
  _el_66:any;
  _text_67:any;
  _el_68:any;
  _DomHandler_68_3:import14.DomHandler;
  _Button_68_4:import18.Wrapper_Button;
  _text_69:any;
  _text_70:any;
  _text_71:any;
  _text_72:any;
  _text_73:any;
  _el_74:any;
  compView_74:import1.AppView<import19.Dialog>;
  _DomHandler_74_3:import14.DomHandler;
  _Dialog_74_4:import20.Wrapper_Dialog;
  _query_Header_74_0:import21.QueryList<any>;
  _text_75:any;
  _text_76:any;
  _map_109:any;
  /*private*/ _expr_110:any;
  /*private*/ _expr_111:any;
  /*private*/ _expr_112:any;
  /*private*/ _expr_113:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import22.ViewContainer) {
    super(View_EmailComponent1,renderType_EmailComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._map_109 = import3.pureProxy1((p0:any):{[key: string]:any} => {
      return {width: p0};
    });
    this._expr_110 = import23.UNINITIALIZED;
    this._expr_111 = import23.UNINITIALIZED;
    this._expr_112 = import23.UNINITIALIZED;
    this._expr_113 = import23.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'form',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._NgForm_0_3 = new import10.Wrapper_NgForm((null as any),(null as any));
    this._ControlContainer_0_4 = this._NgForm_0_3.context;
    this._NgControlStatusGroup_0_5 = new import11.Wrapper_NgControlStatusGroup(this._ControlContainer_0_4);
    this._text_1 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','panel panel-default'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','col-md-5'),(null as any));
    this._text_5 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','panel-heading'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n            ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_6,'h3',new import3.InlineArray2(2,'class','panel-title'),(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'Email Campaign',(null as any));
    this._text_10 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._text_11 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_2,'div',new import3.InlineArray2(2,'class','panel-body'),(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'\n            ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_12,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'\n                ',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_14,'div',new import3.InlineArray2(2,'class','col-md-6'),(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'\n                    ',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_16,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_19 = this.renderer.createText(this._el_18,'\n                        ',(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,this._el_18,'label',new import3.InlineArray2(2,'for','groups'),(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'Groups*',(null as any));
    this._text_22 = this.renderer.createText(this._el_18,' \n                        ',(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,this._el_18,'p-multiSelect',new import3.InlineArray8(6,'id','groups','name','emailGroups','required',''),(null as any));
    this.compView_23 = new import15.View_MultiSelect0(this.viewUtils,this,23,this._el_23);
    this._RequiredValidator_23_3 = new import13.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_23_4 = [this._RequiredValidator_23_3.context];
    this._DomHandler_23_5 = new import14.DomHandler();
    this._MultiSelect_23_6 = new import15.Wrapper_MultiSelect(new import24.ElementRef(this._el_23),this._DomHandler_23_5,this.renderer,this.parentView.injectorGet(import25.IterableDiffers,this.parentIndex));
    this._NG_VALUE_ACCESSOR_23_7 = [this._MultiSelect_23_6.context];
    this._NgModel_23_8 = new import16.Wrapper_NgModel(this._ControlContainer_0_4,this._NG_VALIDATORS_23_4,(null as any),this._NG_VALUE_ACCESSOR_23_7);
    this._NgControl_23_9 = this._NgModel_23_8.context;
    this._NgControlStatus_23_10 = new import11.Wrapper_NgControlStatus(this._NgControl_23_9);
    this.compView_23.create(this._MultiSelect_23_6.context);
    this._text_24 = this.renderer.createText(this._el_18,'\n                        ',(null as any));
    this._el_25 = import3.createRenderElement(this.renderer,this._el_18,'div',new import3.InlineArray2(2,'class','alert alert-danger'),(null as any));
    this._text_26 = this.renderer.createText(this._el_25,'\n                            Group is required\n                        ',(null as any));
    this._text_27 = this.renderer.createText(this._el_18,'\n                    ',(null as any));
    this._text_28 = this.renderer.createText(this._el_16,'\n                ',(null as any));
    this._text_29 = this.renderer.createText(this._el_14,'\n            ',(null as any));
    this._text_30 = this.renderer.createText(this._el_12,'            \n            ',(null as any));
    this._el_31 = import3.createRenderElement(this.renderer,this._el_12,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_32 = this.renderer.createText(this._el_31,'\n                ',(null as any));
    this._el_33 = import3.createRenderElement(this.renderer,this._el_31,'div',new import3.InlineArray2(2,'class','col-md-12'),(null as any));
    this._text_34 = this.renderer.createText(this._el_33,'\n                    ',(null as any));
    this._el_35 = import3.createRenderElement(this.renderer,this._el_33,'div',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_36 = this.renderer.createText(this._el_35,'\n                        ',(null as any));
    this._el_37 = import3.createRenderElement(this.renderer,this._el_35,'label',new import3.InlineArray2(2,'for','subject'),(null as any));
    this._text_38 = this.renderer.createText(this._el_37,'Subject*',(null as any));
    this._text_39 = this.renderer.createText(this._el_35,'\n                        ',(null as any));
    this._el_40 = import3.createRenderElement(this.renderer,this._el_35,'input',new import3.InlineArray16(12,'class','form-control','id','subject','name','subject','placeholder','Required','required','','type','text'),(null as any));
    this._DefaultValueAccessor_40_3 = new import17.Wrapper_DefaultValueAccessor(this.renderer,new import24.ElementRef(this._el_40));
    this._RequiredValidator_40_4 = new import13.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_40_5 = [this._RequiredValidator_40_4.context];
    this._NG_VALUE_ACCESSOR_40_6 = [this._DefaultValueAccessor_40_3.context];
    this._NgModel_40_7 = new import16.Wrapper_NgModel(this._ControlContainer_0_4,this._NG_VALIDATORS_40_5,(null as any),this._NG_VALUE_ACCESSOR_40_6);
    this._NgControl_40_8 = this._NgModel_40_7.context;
    this._NgControlStatus_40_9 = new import11.Wrapper_NgControlStatus(this._NgControl_40_8);
    this._text_41 = this.renderer.createText(this._el_35,'\n                        ',(null as any));
    this._el_42 = import3.createRenderElement(this.renderer,this._el_35,'div',new import3.InlineArray2(2,'class','alert alert-danger'),(null as any));
    this._text_43 = this.renderer.createText(this._el_42,'\n                            Subject is required\n                        ',(null as any));
    this._text_44 = this.renderer.createText(this._el_35,'\n                    ',(null as any));
    this._text_45 = this.renderer.createText(this._el_33,'\n                ',(null as any));
    this._text_46 = this.renderer.createText(this._el_31,'\n            ',(null as any));
    this._text_47 = this.renderer.createText(this._el_12,'\n            ',(null as any));
    this._el_48 = import3.createRenderElement(this.renderer,this._el_12,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_49 = this.renderer.createText(this._el_48,'\n                ',(null as any));
    this._el_50 = import3.createRenderElement(this.renderer,this._el_48,'div',new import3.InlineArray2(2,'class','col-md-12'),(null as any));
    this._text_51 = this.renderer.createText(this._el_50,'\n                    ',(null as any));
    this._el_52 = import3.createRenderElement(this.renderer,this._el_50,'label',new import3.InlineArray2(2,'for','message'),(null as any));
    this._text_53 = this.renderer.createText(this._el_52,'Message*',(null as any));
    this._text_54 = this.renderer.createText(this._el_50,'\n                    ',(null as any));
    this._el_55 = import3.createRenderElement(this.renderer,this._el_50,'textarea',new import3.InlineArray16(12,'class','form-control','id','message','name','message','placeholder','Required','required','','rows','10'),(null as any));
    this._DefaultValueAccessor_55_3 = new import17.Wrapper_DefaultValueAccessor(this.renderer,new import24.ElementRef(this._el_55));
    this._RequiredValidator_55_4 = new import13.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_55_5 = [this._RequiredValidator_55_4.context];
    this._NG_VALUE_ACCESSOR_55_6 = [this._DefaultValueAccessor_55_3.context];
    this._NgModel_55_7 = new import16.Wrapper_NgModel(this._ControlContainer_0_4,this._NG_VALIDATORS_55_5,(null as any),this._NG_VALUE_ACCESSOR_55_6);
    this._NgControl_55_8 = this._NgModel_55_7.context;
    this._NgControlStatus_55_9 = new import11.Wrapper_NgControlStatus(this._NgControl_55_8);
    this._text_56 = this.renderer.createText(this._el_50,'\n                    ',(null as any));
    this._el_57 = import3.createRenderElement(this.renderer,this._el_50,'div',new import3.InlineArray2(2,'class','alert alert-danger'),(null as any));
    this._text_58 = this.renderer.createText(this._el_57,'\n                        Message is required\n                    ',(null as any));
    this._text_59 = this.renderer.createText(this._el_50,'\n                ',(null as any));
    this._text_60 = this.renderer.createText(this._el_48,'\n            ',(null as any));
    this._text_61 = this.renderer.createText(this._el_12,'\n            ',(null as any));
    this._el_62 = import3.createRenderElement(this.renderer,this._el_12,'br',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_63 = this.renderer.createText(this._el_12,'\n            ',(null as any));
    this._el_64 = import3.createRenderElement(this.renderer,this._el_12,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_65 = this.renderer.createText(this._el_64,'\n                ',(null as any));
    this._el_66 = import3.createRenderElement(this.renderer,this._el_64,'div',new import3.InlineArray2(2,'class','col-md-12'),(null as any));
    this._text_67 = this.renderer.createText(this._el_66,'\n                    ',(null as any));
    this._el_68 = import3.createRenderElement(this.renderer,this._el_66,'button',new import3.InlineArray8(8,'icon','fa-check','label','Send','pButton','','type','submit'),(null as any));
    this._DomHandler_68_3 = new import14.DomHandler();
    this._Button_68_4 = new import18.Wrapper_Button(new import24.ElementRef(this._el_68),this._DomHandler_68_3);
    this._text_69 = this.renderer.createText(this._el_66,'\n                ',(null as any));
    this._text_70 = this.renderer.createText(this._el_64,'\n            ',(null as any));
    this._text_71 = this.renderer.createText(this._el_12,'\n        ',(null as any));
    this._text_72 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_73 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._el_74 = import3.createRenderElement(this.renderer,this._el_0,'p-dialog',new import3.InlineArray8(6,'header','Sending Mail...','minWidth','200px','modal','modal'),(null as any));
    this.compView_74 = new import20.View_Dialog0(this.viewUtils,this,74,this._el_74);
    this._DomHandler_74_3 = new import14.DomHandler();
    this._Dialog_74_4 = new import20.Wrapper_Dialog(new import24.ElementRef(this._el_74),this._DomHandler_74_3,this.renderer);
    this._query_Header_74_0 = new import21.QueryList<any>();
    this._text_75 = this.renderer.createText((null as any),'\n    ',(null as any));
    this.compView_74.create(this._Dialog_74_4.context);
    this._text_76 = this.renderer.createText(this._el_0,'\n\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray4(4,'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_0));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_23,new import3.InlineArray2(2,'ngModelChange',(null as any)),this.eventHandler(this.handleEvent_23));
    this._NgModel_23_8.subscribe(this,this.eventHandler(this.handleEvent_23),true);
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_40,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_40));
    this._NgModel_40_7.subscribe(this,this.eventHandler(this.handleEvent_40),true);
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_55,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_55));
    this._NgModel_55_7.subscribe(this,this.eventHandler(this.handleEvent_55),true);
    var disposable_4:Function = import3.subscribeToRenderElement(this,this._el_68,new import3.InlineArray16(14,'click',(null as any),'mouseenter',(null as any),'mouseleave',(null as any),'mousedown',(null as any),'mouseup',(null as any),'focus',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_68));
    var disposable_5:Function = import3.subscribeToRenderElement(this,this._el_74,new import3.InlineArray4(4,'visibleChange',(null as any),'onAfterShow',(null as any)),this.eventHandler(this.handleEvent_74));
    this._Dialog_74_4.subscribe(this,this.eventHandler(this.handleEvent_74),false,true,false,false,true);
    this._query_Header_74_0.reset(([] as any[]));
    this._Dialog_74_4.context.headerFacet = this._query_Header_74_0.first;
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._text_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._text_44,
      this._text_45,
      this._text_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._el_52,
      this._text_53,
      this._text_54,
      this._el_55,
      this._text_56,
      this._el_57,
      this._text_58,
      this._text_59,
      this._text_60,
      this._text_61,
      this._el_62,
      this._text_63,
      this._el_64,
      this._text_65,
      this._el_66,
      this._text_67,
      this._el_68,
      this._text_69,
      this._text_70,
      this._text_71,
      this._text_72,
      this._text_73,
      this._el_74,
      this._text_75,
      this._text_76
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import26.RequiredValidator) && (23 === requestNodeIndex))) { return this._RequiredValidator_23_3.context; }
    if (((token === import27.NG_VALIDATORS) && (23 === requestNodeIndex))) { return this._NG_VALIDATORS_23_4; }
    if (((token === import14.DomHandler) && (23 === requestNodeIndex))) { return this._DomHandler_23_5; }
    if (((token === import12.MultiSelect) && (23 === requestNodeIndex))) { return this._MultiSelect_23_6.context; }
    if (((token === import28.NG_VALUE_ACCESSOR) && (23 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_23_7; }
    if (((token === import29.NgModel) && (23 === requestNodeIndex))) { return this._NgModel_23_8.context; }
    if (((token === import30.NgControl) && (23 === requestNodeIndex))) { return this._NgControl_23_9; }
    if (((token === import31.NgControlStatus) && (23 === requestNodeIndex))) { return this._NgControlStatus_23_10.context; }
    if (((token === import32.DefaultValueAccessor) && (40 === requestNodeIndex))) { return this._DefaultValueAccessor_40_3.context; }
    if (((token === import26.RequiredValidator) && (40 === requestNodeIndex))) { return this._RequiredValidator_40_4.context; }
    if (((token === import27.NG_VALIDATORS) && (40 === requestNodeIndex))) { return this._NG_VALIDATORS_40_5; }
    if (((token === import28.NG_VALUE_ACCESSOR) && (40 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_40_6; }
    if (((token === import29.NgModel) && (40 === requestNodeIndex))) { return this._NgModel_40_7.context; }
    if (((token === import30.NgControl) && (40 === requestNodeIndex))) { return this._NgControl_40_8; }
    if (((token === import31.NgControlStatus) && (40 === requestNodeIndex))) { return this._NgControlStatus_40_9.context; }
    if (((token === import32.DefaultValueAccessor) && (55 === requestNodeIndex))) { return this._DefaultValueAccessor_55_3.context; }
    if (((token === import26.RequiredValidator) && (55 === requestNodeIndex))) { return this._RequiredValidator_55_4.context; }
    if (((token === import27.NG_VALIDATORS) && (55 === requestNodeIndex))) { return this._NG_VALIDATORS_55_5; }
    if (((token === import28.NG_VALUE_ACCESSOR) && (55 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_55_6; }
    if (((token === import29.NgModel) && (55 === requestNodeIndex))) { return this._NgModel_55_7.context; }
    if (((token === import30.NgControl) && (55 === requestNodeIndex))) { return this._NgControl_55_8; }
    if (((token === import31.NgControlStatus) && (55 === requestNodeIndex))) { return this._NgControlStatus_55_9.context; }
    if (((token === import14.DomHandler) && (68 === requestNodeIndex))) { return this._DomHandler_68_3; }
    if (((token === import33.Button) && (68 === requestNodeIndex))) { return this._Button_68_4.context; }
    if (((token === import14.DomHandler) && ((74 <= requestNodeIndex) && (requestNodeIndex <= 75)))) { return this._DomHandler_74_3; }
    if (((token === import19.Dialog) && ((74 <= requestNodeIndex) && (requestNodeIndex <= 75)))) { return this._Dialog_74_4.context; }
    if (((token === import34.NgForm) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 76)))) { return this._NgForm_0_3.context; }
    if (((token === import35.ControlContainer) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 76)))) { return this._ControlContainer_0_4; }
    if (((token === import31.NgControlStatusGroup) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 76)))) { return this._NgControlStatusGroup_0_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._NgForm_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this._NgControlStatusGroup_0_5.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_23_0_0:any = '';
    this._RequiredValidator_23_3.check_required(currVal_23_0_0,throwOnChange,false);
    this._RequiredValidator_23_3.ngDoCheck(this,this._el_23,throwOnChange);
    const currVal_23_1_0:any = this.parentView.context.commonService.groupItems;
    this._MultiSelect_23_6.check_options(currVal_23_1_0,throwOnChange,false);
    const currVal_23_1_1:any = this._map_109('100%');
    this._MultiSelect_23_6.check_style(currVal_23_1_1,throwOnChange,false);
    this._MultiSelect_23_6.ngDoCheck(this,this._el_23,throwOnChange);
    const currVal_23_2_0:any = 'emailGroups';
    this._NgModel_23_8.check_name(currVal_23_2_0,throwOnChange,false);
    const currVal_23_2_1:any = this.parentView.context.selectedGroups;
    this._NgModel_23_8.check_model(currVal_23_2_1,throwOnChange,false);
    this._NgModel_23_8.ngDoCheck(this,this._el_23,throwOnChange);
    this._NgControlStatus_23_10.ngDoCheck(this,this._el_23,throwOnChange);
    this._DefaultValueAccessor_40_3.ngDoCheck(this,this._el_40,throwOnChange);
    const currVal_40_1_0:any = '';
    this._RequiredValidator_40_4.check_required(currVal_40_1_0,throwOnChange,false);
    this._RequiredValidator_40_4.ngDoCheck(this,this._el_40,throwOnChange);
    const currVal_40_2_0:any = 'subject';
    this._NgModel_40_7.check_name(currVal_40_2_0,throwOnChange,false);
    const currVal_40_2_1:any = this.parentView.context.emailVO.subject;
    this._NgModel_40_7.check_model(currVal_40_2_1,throwOnChange,false);
    this._NgModel_40_7.ngDoCheck(this,this._el_40,throwOnChange);
    this._NgControlStatus_40_9.ngDoCheck(this,this._el_40,throwOnChange);
    this._DefaultValueAccessor_55_3.ngDoCheck(this,this._el_55,throwOnChange);
    const currVal_55_1_0:any = '';
    this._RequiredValidator_55_4.check_required(currVal_55_1_0,throwOnChange,false);
    this._RequiredValidator_55_4.ngDoCheck(this,this._el_55,throwOnChange);
    const currVal_55_2_0:any = 'message';
    this._NgModel_55_7.check_name(currVal_55_2_0,throwOnChange,false);
    const currVal_55_2_1:any = this.parentView.context.emailVO.message;
    this._NgModel_55_7.check_model(currVal_55_2_1,throwOnChange,false);
    this._NgModel_55_7.ngDoCheck(this,this._el_55,throwOnChange);
    this._NgControlStatus_55_9.ngDoCheck(this,this._el_55,throwOnChange);
    const currVal_68_0_0:any = 'Send';
    this._Button_68_4.check_label(currVal_68_0_0,throwOnChange,false);
    const currVal_68_0_1:any = 'fa-check';
    this._Button_68_4.check_icon(currVal_68_0_1,throwOnChange,false);
    this._Button_68_4.ngDoCheck(this,this._el_68,throwOnChange);
    const currVal_74_0_0:any = 'Sending Mail...';
    this._Dialog_74_4.check_header(currVal_74_0_0,throwOnChange,false);
    const currVal_74_0_1:any = '200px';
    this._Dialog_74_4.check_minWidth(currVal_74_0_1,throwOnChange,false);
    const currVal_74_0_2:any = 'modal';
    this._Dialog_74_4.check_modal(currVal_74_0_2,throwOnChange,false);
    const currVal_74_0_3:any = this.parentView.context.emailSending;
    this._Dialog_74_4.check_visible(currVal_74_0_3,throwOnChange,false);
    this._Dialog_74_4.ngDoCheck(this,this._el_74,throwOnChange);
    this._NgControlStatusGroup_0_5.checkHost(this,this,this._el_0,throwOnChange);
    this._RequiredValidator_23_3.checkHost(this,this.compView_23,this._el_23,throwOnChange);
    this._NgControlStatus_23_10.checkHost(this,this.compView_23,this._el_23,throwOnChange);
    const currVal_110:any = (this._NgModel_23_8.context.valid || this._NgModel_23_8.context.pristine);
    if (import3.checkBinding(throwOnChange,this._expr_110,currVal_110)) {
      this.renderer.setElementProperty(this._el_25,'hidden',currVal_110);
      this._expr_110 = currVal_110;
    }
    this._RequiredValidator_40_4.checkHost(this,this,this._el_40,throwOnChange);
    this._NgControlStatus_40_9.checkHost(this,this,this._el_40,throwOnChange);
    const currVal_111:any = (this._NgModel_40_7.context.valid || this._NgModel_40_7.context.pristine);
    if (import3.checkBinding(throwOnChange,this._expr_111,currVal_111)) {
      this.renderer.setElementProperty(this._el_42,'hidden',currVal_111);
      this._expr_111 = currVal_111;
    }
    this._RequiredValidator_55_4.checkHost(this,this,this._el_55,throwOnChange);
    this._NgControlStatus_55_9.checkHost(this,this,this._el_55,throwOnChange);
    const currVal_112:any = (this._NgModel_55_7.context.valid || this._NgModel_55_7.context.pristine);
    if (import3.checkBinding(throwOnChange,this._expr_112,currVal_112)) {
      this.renderer.setElementProperty(this._el_57,'hidden',currVal_112);
      this._expr_112 = currVal_112;
    }
    const currVal_113:boolean = !this._NgForm_0_3.context.form.valid;
    if (import3.checkBinding(throwOnChange,this._expr_113,currVal_113)) {
      this.renderer.setElementProperty(this._el_68,'disabled',currVal_113);
      this._expr_113 = currVal_113;
    }
    this._Button_68_4.checkHost(this,this,this._el_68,throwOnChange);
    this.compView_23.internalDetectChanges(throwOnChange);
    this.compView_74.internalDetectChanges(throwOnChange);
    if (!throwOnChange) {
      if ((this.numberOfChecks === 0)) { this._MultiSelect_23_6.context.ngAfterViewInit(); }
      this._MultiSelect_23_6.context.ngAfterViewChecked();
      if ((this.numberOfChecks === 0)) { this._Button_68_4.context.ngAfterViewInit(); }
      if ((this.numberOfChecks === 0)) { this._Dialog_74_4.context.ngAfterViewInit(); }
      this._Dialog_74_4.context.ngAfterViewChecked();
    }
  }
  destroyInternal():void {
    this.compView_23.destroy();
    this.compView_74.destroy();
    this._MultiSelect_23_6.ngOnDestroy();
    this._NgModel_23_8.ngOnDestroy();
    this._NgModel_40_7.ngOnDestroy();
    this._NgModel_55_7.ngOnDestroy();
    this._Button_68_4.ngOnDestroy();
    this._Dialog_74_4.ngOnDestroy();
    this._NgForm_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 74) && (ngContentIndex == 0))) {  }
    if (((nodeIndex == 74) && (ngContentIndex == 1))) { cb(this._text_75,ctx); }
    if (((nodeIndex == 74) && (ngContentIndex == 2))) {  }
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._NgForm_0_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_23(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.parentView.context.selectedGroups = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_40(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_40_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.parentView.context.emailVO.subject = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_55(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_55_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.parentView.context.emailVO.message = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_68(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._Button_68_4.handleEvent(eventName,$event) && result);
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.showDialog()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_74(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'visibleChange')) {
      const pd_sub_0:any = ((<any>(this.parentView.context.emailSending = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'onAfterShow')) {
      const pd_sub_1:any = ((<any>this.parentView.context.sendEmail()) !== false);
      result = (pd_sub_1 && result);
    }
    return result;
  }
}
var renderType_EmailComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_EmailComponent,{});
export class View_EmailComponent0 extends import1.AppView<import0.EmailComponent> {
  _el_0:any;
  compView_0:import1.AppView<import36.Growl>;
  _DomHandler_0_3:import14.DomHandler;
  _Growl_0_4:import37.Wrapper_Growl;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _vc_2:import22.ViewContainer;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import38.Wrapper_NgIf;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_EmailComponent0,renderType_EmailComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'p-growl',new import3.InlineArray2(2,'sticky','sticky'),(null as any));
    this.compView_0 = new import37.View_Growl0(this.viewUtils,this,0,this._el_0);
    this._DomHandler_0_3 = new import14.DomHandler();
    this._Growl_0_4 = new import37.Wrapper_Growl(new import24.ElementRef(this._el_0),this._DomHandler_0_3,this.parentView.injectorGet(import25.IterableDiffers,this.parentIndex));
    this.compView_0.create(this._Growl_0_4.context);
    this._text_1 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._vc_2 = new import22.ViewContainer(2,(null as any),this,this._anchor_2);
    this._TemplateRef_2_5 = new import39.TemplateRef_(this,2,this._anchor_2);
    this._NgIf_2_6 = new import38.Wrapper_NgIf(this._vc_2.vcRef,this._TemplateRef_2_5);
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._anchor_2
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.DomHandler) && (0 === requestNodeIndex))) { return this._DomHandler_0_3; }
    if (((token === import36.Growl) && (0 === requestNodeIndex))) { return this._Growl_0_4.context; }
    if (((token === import39.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import40.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = 'sticky';
    this._Growl_0_4.check_sticky(currVal_0_0_0,throwOnChange,false);
    const currVal_0_0_1:any = this.context.msgs;
    this._Growl_0_4.check_value(currVal_0_0_1,throwOnChange,false);
    this._Growl_0_4.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_2_0_0:any = this.context.active;
    this._NgIf_2_6.check_ngIf(currVal_2_0_0,throwOnChange,false);
    this._NgIf_2_6.ngDoCheck(this,this._anchor_2,throwOnChange);
    this._vc_2.detectChangesInNestedViews(throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Growl_0_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._vc_2.destroyNestedViews();
    this.compView_0.destroy();
    this._Growl_0_4.ngOnDestroy();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 2)) { return new View_EmailComponent1(this.viewUtils,this,2,this._anchor_2,this._vc_2); }
    return (null as any);
  }
}