/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../src/app/security/login/login.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../../../../src/app/security/login/login.service';
import * as import9 from '@angular/router/src/router';
import * as import10 from '../../../../../src/app/core/global.service';
import * as import11 from '../../../../node_modules/@angular/forms/src/directives/ng_form.ngfactory';
import * as import12 from '../../../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import13 from '@angular/material/card/card';
import * as import14 from '../../../../node_modules/@angular/material/card/card.ngfactory';
import * as import15 from '../../../../node_modules/@angular/material/core/compatibility/style-compatibility.ngfactory';
import * as import16 from '@angular/material/input/input';
import * as import17 from '../../../../node_modules/@angular/forms/src/directives/validators.ngfactory';
import * as import18 from '../../../../node_modules/@angular/material/input/input.ngfactory';
import * as import19 from '../../../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import20 from '@angular/core/src/linker/query_list';
import * as import21 from '@angular/material/button/button';
import * as import22 from '../../../../node_modules/@angular/material/button/button.ngfactory';
import * as import23 from '@angular/core/src/linker/element_ref';
import * as import24 from '@angular/material/core/compatibility/style-compatibility';
import * as import25 from '@angular/forms/src/directives/validators';
import * as import26 from '@angular/forms/src/validators';
import * as import27 from '@angular/forms/src/directives/control_value_accessor';
import * as import28 from '@angular/forms/src/directives/ng_model';
import * as import29 from '@angular/forms/src/directives/ng_control';
import * as import30 from '@angular/forms/src/directives/ng_control_status';
import * as import31 from '@angular/forms/src/directives/ng_form';
import * as import32 from '@angular/forms/src/directives/control_container';
export class Wrapper_LoginComponent {
  /*private*/ _eventHandler:Function;
  context:import0.LoginComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any,p2:any) {
    this._changed = false;
    this.context = new import0.LoginComponent(p0,p1,p2);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_LoginComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_LoginComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.LoginComponent>;
  _LoginComponent_0_3:Wrapper_LoginComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_LoginComponent_Host0,renderType_LoginComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'login',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_LoginComponent0(this.viewUtils,this,0,this._el_0);
    this._LoginComponent_0_3 = new Wrapper_LoginComponent(this.injectorGet(import8.LoginService,this.parentIndex),this.injectorGet(import9.Router,this.parentIndex),this.injectorGet(import10.GlobalService,this.parentIndex));
    this.compView_0.create(this._LoginComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._LoginComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.LoginComponent) && (0 === requestNodeIndex))) { return this._LoginComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._LoginComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const LoginComponentNgFactory:import7.ComponentFactory<import0.LoginComponent> = new import7.ComponentFactory<import0.LoginComponent>('login',View_LoginComponent_Host0,import0.LoginComponent);
const styles_LoginComponent:any[] = ([] as any[]);
var renderType_LoginComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_LoginComponent,{});
export class View_LoginComponent0 extends import1.AppView<import0.LoginComponent> {
  _el_0:any;
  _NgForm_0_3:import11.Wrapper_NgForm;
  _ControlContainer_0_4:any;
  _NgControlStatusGroup_0_5:import12.Wrapper_NgControlStatusGroup;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  compView_6:import1.AppView<import13.MdCard>;
  _MdCard_6_3:import14.Wrapper_MdCard;
  _StyleCompatibility_6_4:import15.Wrapper_StyleCompatibility;
  _text_7:any;
  _el_8:any;
  _MdCardTitle_8_3:import14.Wrapper_MdCardTitle;
  _StyleCompatibility_8_4:import15.Wrapper_StyleCompatibility;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _MdCardContent_11_3:import14.Wrapper_MdCardContent;
  _StyleCompatibility_11_4:import15.Wrapper_StyleCompatibility;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _el_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _el_20:any;
  compView_20:import1.AppView<import16.MdInput>;
  _RequiredValidator_20_3:import17.Wrapper_RequiredValidator;
  _NG_VALIDATORS_20_4:any[];
  _MdInput_20_5:import18.Wrapper_MdInput;
  _NG_VALUE_ACCESSOR_20_6:any[];
  _NgModel_20_7:import19.Wrapper_NgModel;
  _NgControl_20_8:any;
  _NgControlStatus_20_9:import12.Wrapper_NgControlStatus;
  _StyleCompatibility_20_10:import15.Wrapper_StyleCompatibility;
  _query_MdPlaceholder_20_0:import20.QueryList<any>;
  _query_MdHint_20_1:import20.QueryList<any>;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _text_26:any;
  _text_27:any;
  _text_28:any;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _el_35:any;
  compView_35:import1.AppView<import16.MdInput>;
  _RequiredValidator_35_3:import17.Wrapper_RequiredValidator;
  _NG_VALIDATORS_35_4:any[];
  _MdInput_35_5:import18.Wrapper_MdInput;
  _NG_VALUE_ACCESSOR_35_6:any[];
  _NgModel_35_7:import19.Wrapper_NgModel;
  _NgControl_35_8:any;
  _NgControlStatus_35_9:import12.Wrapper_NgControlStatus;
  _StyleCompatibility_35_10:import15.Wrapper_StyleCompatibility;
  _query_MdPlaceholder_35_0:import20.QueryList<any>;
  _query_MdHint_35_1:import20.QueryList<any>;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _text_41:any;
  _text_42:any;
  _text_43:any;
  _text_44:any;
  _text_45:any;
  _text_46:any;
  _text_47:any;
  _el_48:any;
  _MdCardActions_48_3:import14.Wrapper_MdCardActions;
  _StyleCompatibility_48_4:import15.Wrapper_StyleCompatibility;
  _text_49:any;
  _el_50:any;
  compView_50:import1.AppView<import21.MdButton>;
  _MdButton_50_3:import22.Wrapper_MdButton;
  _text_51:any;
  _text_52:any;
  _el_53:any;
  compView_53:import1.AppView<import21.MdButton>;
  _MdButton_53_3:import22.Wrapper_MdButton;
  _text_54:any;
  _text_55:any;
  _text_56:any;
  _text_57:any;
  _text_58:any;
  _el_59:any;
  _text_60:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_LoginComponent0,renderType_LoginComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'form',new import3.InlineArray4(4,'autocomplete','off','novalidate',''),(null as any));
    this._NgForm_0_3 = new import11.Wrapper_NgForm((null as any),(null as any));
    this._ControlContainer_0_4 = this._NgForm_0_3.context;
    this._NgControlStatusGroup_0_5 = new import12.Wrapper_NgControlStatusGroup(this._ControlContainer_0_4);
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','col-xs-1 col-sm-3 col-md-4 col-lg-4 col-xl-4'),(null as any));
    this._text_3 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','col-xs-8 col-sm-6 col-md-4 col-lg-4 col-xl-4'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'md-card',new import3.InlineArray2(2,'class','app-input-section'),(null as any));
    this.compView_6 = new import14.View_MdCard0(this.viewUtils,this,6,this._el_6);
    this._MdCard_6_3 = new import14.Wrapper_MdCard();
    this._StyleCompatibility_6_4 = new import15.Wrapper_StyleCompatibility(this.renderer,new import23.ElementRef(this._el_6));
    this._text_7 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,(null as any),'md-card-title',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._MdCardTitle_8_3 = new import14.Wrapper_MdCardTitle();
    this._StyleCompatibility_8_4 = new import15.Wrapper_StyleCompatibility(this.renderer,new import23.ElementRef(this._el_8));
    this._text_9 = this.renderer.createText(this._el_8,'Login',(null as any));
    this._text_10 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,(null as any),'md-card-content',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._MdCardContent_11_3 = new import14.Wrapper_MdCardContent();
    this._StyleCompatibility_11_4 = new import15.Wrapper_StyleCompatibility(this.renderer,new import23.ElementRef(this._el_11));
    this._text_12 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,this._el_11,'table',new import3.InlineArray4(4,'cellspacing','0','style','width: 100%'),(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'\n          ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_13,'tbody',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_15,'tr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'\n            ',(null as any));
    this._el_18 = import3.createRenderElement(this.renderer,this._el_16,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_19 = this.renderer.createText(this._el_18,'\n              ',(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,this._el_18,'md-input',new import3.InlineArray8(8,'name','username','placeholder','User name','required','','style','width: 100%'),(null as any));
    this.compView_20 = new import18.View_MdInput0(this.viewUtils,this,20,this._el_20);
    this._RequiredValidator_20_3 = new import17.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_20_4 = [this._RequiredValidator_20_3.context];
    this._MdInput_20_5 = new import18.Wrapper_MdInput(new import23.ElementRef(this._el_20));
    this._NG_VALUE_ACCESSOR_20_6 = [this._MdInput_20_5.context];
    this._NgModel_20_7 = new import19.Wrapper_NgModel(this._ControlContainer_0_4,this._NG_VALIDATORS_20_4,(null as any),this._NG_VALUE_ACCESSOR_20_6);
    this._NgControl_20_8 = this._NgModel_20_7.context;
    this._NgControlStatus_20_9 = new import12.Wrapper_NgControlStatus(this._NgControl_20_8);
    this._StyleCompatibility_20_10 = new import15.Wrapper_StyleCompatibility(this.renderer,new import23.ElementRef(this._el_20));
    this._query_MdPlaceholder_20_0 = new import20.QueryList<any>();
    this._query_MdHint_20_1 = new import20.QueryList<any>();
    this._text_21 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_22 = import3.createRenderElement(this.renderer,(null as any),'span',new import3.InlineArray2(2,'md-prefix',''),(null as any));
    this._text_23 = this.renderer.createText(this._el_22,'\n                ',(null as any));
    this._el_24 = import3.createRenderElement(this.renderer,this._el_22,'i',new import3.InlineArray2(2,'class','material-icons app-input-icon'),(null as any));
    this._text_25 = this.renderer.createText(this._el_24,'person',(null as any));
    this._text_26 = this.renderer.createText(this._el_22,'\n              ',(null as any));
    this._text_27 = this.renderer.createText((null as any),'\n              ',(null as any));
    this.compView_20.create(this._MdInput_20_5.context);
    this._text_28 = this.renderer.createText(this._el_18,'\n            ',(null as any));
    this._text_29 = this.renderer.createText(this._el_16,'\n          ',(null as any));
    this._text_30 = this.renderer.createText(this._el_15,'\n          ',(null as any));
    this._el_31 = import3.createRenderElement(this.renderer,this._el_15,'tr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_32 = this.renderer.createText(this._el_31,'\n            ',(null as any));
    this._el_33 = import3.createRenderElement(this.renderer,this._el_31,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_34 = this.renderer.createText(this._el_33,'\n              ',(null as any));
    this._el_35 = import3.createRenderElement(this.renderer,this._el_33,'md-input',new import3.InlineArray16(10,'name','password','placeholder','Password','required','','style','width: 100%','type','password'),(null as any));
    this.compView_35 = new import18.View_MdInput0(this.viewUtils,this,35,this._el_35);
    this._RequiredValidator_35_3 = new import17.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_35_4 = [this._RequiredValidator_35_3.context];
    this._MdInput_35_5 = new import18.Wrapper_MdInput(new import23.ElementRef(this._el_35));
    this._NG_VALUE_ACCESSOR_35_6 = [this._MdInput_35_5.context];
    this._NgModel_35_7 = new import19.Wrapper_NgModel(this._ControlContainer_0_4,this._NG_VALIDATORS_35_4,(null as any),this._NG_VALUE_ACCESSOR_35_6);
    this._NgControl_35_8 = this._NgModel_35_7.context;
    this._NgControlStatus_35_9 = new import12.Wrapper_NgControlStatus(this._NgControl_35_8);
    this._StyleCompatibility_35_10 = new import15.Wrapper_StyleCompatibility(this.renderer,new import23.ElementRef(this._el_35));
    this._query_MdPlaceholder_35_0 = new import20.QueryList<any>();
    this._query_MdHint_35_1 = new import20.QueryList<any>();
    this._text_36 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_37 = import3.createRenderElement(this.renderer,(null as any),'span',new import3.InlineArray2(2,'md-prefix',''),(null as any));
    this._text_38 = this.renderer.createText(this._el_37,'\n                ',(null as any));
    this._el_39 = import3.createRenderElement(this.renderer,this._el_37,'i',new import3.InlineArray2(2,'class','material-icons app-input-icon'),(null as any));
    this._text_40 = this.renderer.createText(this._el_39,'vpn_key',(null as any));
    this._text_41 = this.renderer.createText(this._el_37,'\n              ',(null as any));
    this._text_42 = this.renderer.createText((null as any),'\n              ',(null as any));
    this.compView_35.create(this._MdInput_35_5.context);
    this._text_43 = this.renderer.createText(this._el_33,'\n            ',(null as any));
    this._text_44 = this.renderer.createText(this._el_31,'\n          ',(null as any));
    this._text_45 = this.renderer.createText(this._el_15,'\n        ',(null as any));
    this._text_46 = this.renderer.createText(this._el_11,'\n      ',(null as any));
    this._text_47 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_48 = import3.createRenderElement(this.renderer,(null as any),'md-card-actions',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._MdCardActions_48_3 = new import14.Wrapper_MdCardActions();
    this._StyleCompatibility_48_4 = new import15.Wrapper_StyleCompatibility(this.renderer,new import23.ElementRef(this._el_48));
    this._text_49 = this.renderer.createText(this._el_48,'\n        ',(null as any));
    this._el_50 = import3.createRenderElement(this.renderer,this._el_48,'button',new import3.InlineArray8(8,'color','primary','md-button','','md-raised-button','','type','submit'),(null as any));
    this.compView_50 = new import22.View_MdButton0(this.viewUtils,this,50,this._el_50);
    this._MdButton_50_3 = new import22.Wrapper_MdButton(new import23.ElementRef(this._el_50),this.renderer);
    this._text_51 = this.renderer.createText((null as any),'Submit',(null as any));
    this.compView_50.create(this._MdButton_50_3.context);
    this._text_52 = this.renderer.createText(this._el_48,'\n        ',(null as any));
    this._el_53 = import3.createRenderElement(this.renderer,this._el_48,'button',new import3.InlineArray8(6,'color','primary','md-button','','md-raised-button',''),(null as any));
    this.compView_53 = new import22.View_MdButton0(this.viewUtils,this,53,this._el_53);
    this._MdButton_53_3 = new import22.Wrapper_MdButton(new import23.ElementRef(this._el_53),this.renderer);
    this._text_54 = this.renderer.createText((null as any),'Cancel',(null as any));
    this.compView_53.create(this._MdButton_53_3.context);
    this._text_55 = this.renderer.createText(this._el_48,'\n      ',(null as any));
    this._text_56 = this.renderer.createText((null as any),'\n    ',(null as any));
    this.compView_6.create(this._MdCard_6_3.context);
    this._text_57 = this.renderer.createText(this._el_4,'\n  ',(null as any));
    this._text_58 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_59 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','col-xs-1 col-sm-3 col-md-4 col-lg-4 col-xl-4'),(null as any));
    this._text_60 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray8(6,'ngSubmit',(null as any),'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_0));
    this._NgForm_0_3.subscribe(this,this.eventHandler(this.handleEvent_0),true);
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_20,new import3.InlineArray4(4,'ngModelChange',(null as any),'click',(null as any)),this.eventHandler(this.handleEvent_20));
    this._NgModel_20_7.subscribe(this,this.eventHandler(this.handleEvent_20),true);
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_35,new import3.InlineArray4(4,'ngModelChange',(null as any),'click',(null as any)),this.eventHandler(this.handleEvent_35));
    this._NgModel_35_7.subscribe(this,this.eventHandler(this.handleEvent_35),true);
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_50,new import3.InlineArray8(6,'mousedown',(null as any),'focus',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_50));
    var disposable_4:Function = import3.subscribeToRenderElement(this,this._el_53,new import3.InlineArray8(6,'mousedown',(null as any),'focus',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_53));
    this._query_MdPlaceholder_20_0.reset(([] as any[]));
    this._MdInput_20_5.context._placeholderChild = this._query_MdPlaceholder_20_0.first;
    this._query_MdPlaceholder_35_0.reset(([] as any[]));
    this._MdInput_35_5.context._placeholderChild = this._query_MdPlaceholder_35_0.first;
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._text_27,
      this._text_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._text_41,
      this._text_42,
      this._text_43,
      this._text_44,
      this._text_45,
      this._text_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._text_52,
      this._el_53,
      this._text_54,
      this._text_55,
      this._text_56,
      this._text_57,
      this._text_58,
      this._el_59,
      this._text_60
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.MdCardTitle) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._MdCardTitle_8_3.context; }
    if (((token === import24.StyleCompatibility) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._StyleCompatibility_8_4.context; }
    if (((token === import25.RequiredValidator) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._RequiredValidator_20_3.context; }
    if (((token === import26.NG_VALIDATORS) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._NG_VALIDATORS_20_4; }
    if (((token === import16.MdInput) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._MdInput_20_5.context; }
    if (((token === import27.NG_VALUE_ACCESSOR) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._NG_VALUE_ACCESSOR_20_6; }
    if (((token === import28.NgModel) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._NgModel_20_7.context; }
    if (((token === import29.NgControl) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._NgControl_20_8; }
    if (((token === import30.NgControlStatus) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._NgControlStatus_20_9.context; }
    if (((token === import24.StyleCompatibility) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._StyleCompatibility_20_10.context; }
    if (((token === import25.RequiredValidator) && ((35 <= requestNodeIndex) && (requestNodeIndex <= 42)))) { return this._RequiredValidator_35_3.context; }
    if (((token === import26.NG_VALIDATORS) && ((35 <= requestNodeIndex) && (requestNodeIndex <= 42)))) { return this._NG_VALIDATORS_35_4; }
    if (((token === import16.MdInput) && ((35 <= requestNodeIndex) && (requestNodeIndex <= 42)))) { return this._MdInput_35_5.context; }
    if (((token === import27.NG_VALUE_ACCESSOR) && ((35 <= requestNodeIndex) && (requestNodeIndex <= 42)))) { return this._NG_VALUE_ACCESSOR_35_6; }
    if (((token === import28.NgModel) && ((35 <= requestNodeIndex) && (requestNodeIndex <= 42)))) { return this._NgModel_35_7.context; }
    if (((token === import29.NgControl) && ((35 <= requestNodeIndex) && (requestNodeIndex <= 42)))) { return this._NgControl_35_8; }
    if (((token === import30.NgControlStatus) && ((35 <= requestNodeIndex) && (requestNodeIndex <= 42)))) { return this._NgControlStatus_35_9.context; }
    if (((token === import24.StyleCompatibility) && ((35 <= requestNodeIndex) && (requestNodeIndex <= 42)))) { return this._StyleCompatibility_35_10.context; }
    if (((token === import13.MdCardContent) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 46)))) { return this._MdCardContent_11_3.context; }
    if (((token === import24.StyleCompatibility) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 46)))) { return this._StyleCompatibility_11_4.context; }
    if (((token === import21.MdButton) && ((50 <= requestNodeIndex) && (requestNodeIndex <= 51)))) { return this._MdButton_50_3.context; }
    if (((token === import21.MdButton) && ((53 <= requestNodeIndex) && (requestNodeIndex <= 54)))) { return this._MdButton_53_3.context; }
    if (((token === import13.MdCardActions) && ((48 <= requestNodeIndex) && (requestNodeIndex <= 55)))) { return this._MdCardActions_48_3.context; }
    if (((token === import24.StyleCompatibility) && ((48 <= requestNodeIndex) && (requestNodeIndex <= 55)))) { return this._StyleCompatibility_48_4.context; }
    if (((token === import13.MdCard) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 56)))) { return this._MdCard_6_3.context; }
    if (((token === import24.StyleCompatibility) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 56)))) { return this._StyleCompatibility_6_4.context; }
    if (((token === import31.NgForm) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 60)))) { return this._NgForm_0_3.context; }
    if (((token === import32.ControlContainer) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 60)))) { return this._ControlContainer_0_4; }
    if (((token === import30.NgControlStatusGroup) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 60)))) { return this._NgControlStatusGroup_0_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._NgForm_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this._NgControlStatusGroup_0_5.ngDoCheck(this,this._el_0,throwOnChange);
    if (this._MdCard_6_3.ngDoCheck(this,this._el_6,throwOnChange)) { this.compView_6.markAsCheckOnce(); }
    this._StyleCompatibility_6_4.ngDoCheck(this,this._el_6,throwOnChange);
    this._MdCardTitle_8_3.ngDoCheck(this,this._el_8,throwOnChange);
    this._StyleCompatibility_8_4.ngDoCheck(this,this._el_8,throwOnChange);
    this._MdCardContent_11_3.ngDoCheck(this,this._el_11,throwOnChange);
    this._StyleCompatibility_11_4.ngDoCheck(this,this._el_11,throwOnChange);
    const currVal_20_0_0:any = '';
    this._RequiredValidator_20_3.check_required(currVal_20_0_0,throwOnChange,false);
    this._RequiredValidator_20_3.ngDoCheck(this,this._el_20,throwOnChange);
    const currVal_20_1_0:any = 'User name';
    this._MdInput_20_5.check_placeholder(currVal_20_1_0,throwOnChange,false);
    const currVal_20_1_1:any = 'username';
    this._MdInput_20_5.check_name(currVal_20_1_1,throwOnChange,false);
    const currVal_20_1_2:any = '';
    this._MdInput_20_5.check_required(currVal_20_1_2,throwOnChange,false);
    this._MdInput_20_5.ngDoCheck(this,this._el_20,throwOnChange);
    const currVal_20_2_0:any = 'username';
    this._NgModel_20_7.check_name(currVal_20_2_0,throwOnChange,false);
    const currVal_20_2_1:any = this.context.username;
    this._NgModel_20_7.check_model(currVal_20_2_1,throwOnChange,false);
    this._NgModel_20_7.ngDoCheck(this,this._el_20,throwOnChange);
    this._NgControlStatus_20_9.ngDoCheck(this,this._el_20,throwOnChange);
    this._StyleCompatibility_20_10.ngDoCheck(this,this._el_20,throwOnChange);
    const currVal_35_0_0:any = '';
    this._RequiredValidator_35_3.check_required(currVal_35_0_0,throwOnChange,false);
    this._RequiredValidator_35_3.ngDoCheck(this,this._el_35,throwOnChange);
    const currVal_35_1_0:any = 'Password';
    this._MdInput_35_5.check_placeholder(currVal_35_1_0,throwOnChange,false);
    const currVal_35_1_1:any = 'password';
    this._MdInput_35_5.check_type(currVal_35_1_1,throwOnChange,false);
    const currVal_35_1_2:any = 'password';
    this._MdInput_35_5.check_name(currVal_35_1_2,throwOnChange,false);
    const currVal_35_1_3:any = '';
    this._MdInput_35_5.check_required(currVal_35_1_3,throwOnChange,false);
    this._MdInput_35_5.ngDoCheck(this,this._el_35,throwOnChange);
    const currVal_35_2_0:any = 'password';
    this._NgModel_35_7.check_name(currVal_35_2_0,throwOnChange,false);
    const currVal_35_2_1:any = this.context.password;
    this._NgModel_35_7.check_model(currVal_35_2_1,throwOnChange,false);
    this._NgModel_35_7.ngDoCheck(this,this._el_35,throwOnChange);
    this._NgControlStatus_35_9.ngDoCheck(this,this._el_35,throwOnChange);
    this._StyleCompatibility_35_10.ngDoCheck(this,this._el_35,throwOnChange);
    this._MdCardActions_48_3.ngDoCheck(this,this._el_48,throwOnChange);
    this._StyleCompatibility_48_4.ngDoCheck(this,this._el_48,throwOnChange);
    const currVal_50_0_0:boolean = !this._NgForm_0_3.context.form.valid;
    this._MdButton_50_3.check_disabled(currVal_50_0_0,throwOnChange,false);
    const currVal_50_0_1:any = 'primary';
    this._MdButton_50_3.check_color(currVal_50_0_1,throwOnChange,false);
    if (this._MdButton_50_3.ngDoCheck(this,this._el_50,throwOnChange)) { this.compView_50.markAsCheckOnce(); }
    const currVal_53_0_0:any = 'primary';
    this._MdButton_53_3.check_color(currVal_53_0_0,throwOnChange,false);
    if (this._MdButton_53_3.ngDoCheck(this,this._el_53,throwOnChange)) { this.compView_53.markAsCheckOnce(); }
    if (!throwOnChange) {
      if (this._query_MdHint_20_1.dirty) {
        this._query_MdHint_20_1.reset(([] as any[]));
        this._MdInput_20_5.context._hintChildren = this._query_MdHint_20_1;
        this._query_MdHint_20_1.notifyOnChanges();
      }
      if (this._query_MdHint_35_1.dirty) {
        this._query_MdHint_35_1.reset(([] as any[]));
        this._MdInput_35_5.context._hintChildren = this._query_MdHint_35_1;
        this._query_MdHint_35_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._MdInput_20_5.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._MdInput_35_5.context.ngAfterContentInit(); }
    }
    this._NgControlStatusGroup_0_5.checkHost(this,this,this._el_0,throwOnChange);
    this._RequiredValidator_20_3.checkHost(this,this.compView_20,this._el_20,throwOnChange);
    this._MdInput_20_5.checkHost(this,this.compView_20,this._el_20,throwOnChange);
    this._NgControlStatus_20_9.checkHost(this,this.compView_20,this._el_20,throwOnChange);
    this._RequiredValidator_35_3.checkHost(this,this.compView_35,this._el_35,throwOnChange);
    this._MdInput_35_5.checkHost(this,this.compView_35,this._el_35,throwOnChange);
    this._NgControlStatus_35_9.checkHost(this,this.compView_35,this._el_35,throwOnChange);
    this._MdButton_50_3.checkHost(this,this.compView_50,this._el_50,throwOnChange);
    this._MdButton_53_3.checkHost(this,this.compView_53,this._el_53,throwOnChange);
    this.compView_6.internalDetectChanges(throwOnChange);
    this.compView_20.internalDetectChanges(throwOnChange);
    this.compView_35.internalDetectChanges(throwOnChange);
    this.compView_50.internalDetectChanges(throwOnChange);
    this.compView_53.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_6.destroy();
    this.compView_20.destroy();
    this.compView_35.destroy();
    this.compView_50.destroy();
    this.compView_53.destroy();
    this._MdInput_20_5.ngOnDestroy();
    this._NgModel_20_7.ngOnDestroy();
    this._MdInput_35_5.ngOnDestroy();
    this._NgModel_35_7.ngOnDestroy();
    this._NgForm_0_3.ngOnDestroy();
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 6) && (ngContentIndex == 0))) {
      cb(this._text_7,ctx);
      cb(this._el_8,ctx);
      cb(this._text_10,ctx);
      cb(this._el_11,ctx);
      cb(this._text_47,ctx);
      cb(this._el_48,ctx);
      cb(this._text_56,ctx);
    }
    if (((nodeIndex == 20) && (ngContentIndex == 0))) { cb(this._el_22,ctx); }
    if (((nodeIndex == 20) && (ngContentIndex == 1))) {  }
    if (((nodeIndex == 20) && (ngContentIndex == 2))) {  }
    if (((nodeIndex == 20) && (ngContentIndex == 3))) {  }
    if (((nodeIndex == 35) && (ngContentIndex == 0))) { cb(this._el_37,ctx); }
    if (((nodeIndex == 35) && (ngContentIndex == 1))) {  }
    if (((nodeIndex == 35) && (ngContentIndex == 2))) {  }
    if (((nodeIndex == 35) && (ngContentIndex == 3))) {  }
    if (((nodeIndex == 50) && (ngContentIndex == 0))) { cb(this._text_51,ctx); }
    if (((nodeIndex == 53) && (ngContentIndex == 0))) { cb(this._text_54,ctx); }
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._NgForm_0_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngSubmit')) {
      const pd_sub_0:any = ((<any>this.context.onSubmit()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_20(eventName:string,$event:any):boolean {
    this.compView_20.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdInput_20_5.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.username = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_35(eventName:string,$event:any):boolean {
    this.compView_35.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdInput_35_5.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.password = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_50(eventName:string,$event:any):boolean {
    this.compView_50.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdButton_50_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_53(eventName:string,$event:any):boolean {
    this.compView_53.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdButton_53_3.handleEvent(eventName,$event) && result);
    return result;
  }
}