/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../src/app/security/change-password/change-password.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '@angular/router/src/router';
import * as import9 from '../../../../../src/app/security/user-account/user-account.service';
import * as import10 from './change-password.component.css.shim.ngstyle';
import * as import11 from 'primeng/components/growl/growl';
import * as import12 from 'primeng/components/dom/domhandler';
import * as import13 from '../../../../node_modules/primeng/components/growl/growl.ngfactory';
import * as import14 from '@angular/material/card/card';
import * as import15 from '../../../../node_modules/@angular/material/card/card.ngfactory';
import * as import16 from '../../../../node_modules/@angular/material/core/compatibility/style-compatibility.ngfactory';
import * as import17 from '@angular/material/input/input';
import * as import18 from '../../../../node_modules/@angular/forms/src/directives/validators.ngfactory';
import * as import19 from '../../../../node_modules/@angular/material/input/input.ngfactory';
import * as import20 from '../../../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import21 from '../../../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import22 from '@angular/core/src/linker/query_list';
import * as import23 from '@angular/material/button/button';
import * as import24 from '../../../../node_modules/@angular/material/button/button.ngfactory';
import * as import25 from '@angular/core/src/linker/element_ref';
import * as import26 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import27 from '@angular/material/core/compatibility/style-compatibility';
import * as import28 from '@angular/forms/src/directives/validators';
import * as import29 from '@angular/forms/src/validators';
import * as import30 from '@angular/forms/src/directives/control_value_accessor';
import * as import31 from '@angular/forms/src/directives/ng_model';
import * as import32 from '@angular/forms/src/directives/ng_control';
import * as import33 from '@angular/forms/src/directives/ng_control_status';
export class Wrapper_ChangePasswordComponent {
  /*private*/ _eventHandler:Function;
  context:import0.ChangePasswordComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any) {
    this._changed = false;
    this.context = new import0.ChangePasswordComponent(p0,p1);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_ChangePasswordComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_ChangePasswordComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.ChangePasswordComponent>;
  _ChangePasswordComponent_0_3:Wrapper_ChangePasswordComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ChangePasswordComponent_Host0,renderType_ChangePasswordComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'app-change-password',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_ChangePasswordComponent0(this.viewUtils,this,0,this._el_0);
    this._ChangePasswordComponent_0_3 = new Wrapper_ChangePasswordComponent(this.injectorGet(import8.Router,this.parentIndex),this.injectorGet(import9.UserAccountService,this.parentIndex));
    this.compView_0.create(this._ChangePasswordComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._ChangePasswordComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.ChangePasswordComponent) && (0 === requestNodeIndex))) { return this._ChangePasswordComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._ChangePasswordComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const ChangePasswordComponentNgFactory:import7.ComponentFactory<import0.ChangePasswordComponent> = new import7.ComponentFactory<import0.ChangePasswordComponent>('app-change-password',View_ChangePasswordComponent_Host0,import0.ChangePasswordComponent);
const styles_ChangePasswordComponent:any[] = [import10.styles];
var renderType_ChangePasswordComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_ChangePasswordComponent,{});
export class View_ChangePasswordComponent0 extends import1.AppView<import0.ChangePasswordComponent> {
  _text_0:any;
  _el_1:any;
  compView_1:import1.AppView<import11.Growl>;
  _DomHandler_1_3:import12.DomHandler;
  _Growl_1_4:import13.Wrapper_Growl;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  compView_7:import1.AppView<import14.MdCard>;
  _MdCard_7_3:import15.Wrapper_MdCard;
  _StyleCompatibility_7_4:import16.Wrapper_StyleCompatibility;
  _text_8:any;
  _el_9:any;
  _MdCardTitle_9_3:import15.Wrapper_MdCardTitle;
  _StyleCompatibility_9_4:import16.Wrapper_StyleCompatibility;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _MdCardContent_12_3:import15.Wrapper_MdCardContent;
  _StyleCompatibility_12_4:import16.Wrapper_StyleCompatibility;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _el_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _el_21:any;
  compView_21:import1.AppView<import17.MdInput>;
  _RequiredValidator_21_3:import18.Wrapper_RequiredValidator;
  _NG_VALIDATORS_21_4:any[];
  _MdInput_21_5:import19.Wrapper_MdInput;
  _NG_VALUE_ACCESSOR_21_6:any[];
  _NgModel_21_7:import20.Wrapper_NgModel;
  _NgControl_21_8:any;
  _NgControlStatus_21_9:import21.Wrapper_NgControlStatus;
  _StyleCompatibility_21_10:import16.Wrapper_StyleCompatibility;
  _query_MdPlaceholder_21_0:import22.QueryList<any>;
  _query_MdHint_21_1:import22.QueryList<any>;
  _text_22:any;
  _text_23:any;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _el_30:any;
  compView_30:import1.AppView<import17.MdInput>;
  _RequiredValidator_30_3:import18.Wrapper_RequiredValidator;
  _NG_VALIDATORS_30_4:any[];
  _MdInput_30_5:import19.Wrapper_MdInput;
  _NG_VALUE_ACCESSOR_30_6:any[];
  _NgModel_30_7:import20.Wrapper_NgModel;
  _NgControl_30_8:any;
  _NgControlStatus_30_9:import21.Wrapper_NgControlStatus;
  _StyleCompatibility_30_10:import16.Wrapper_StyleCompatibility;
  _query_MdPlaceholder_30_0:import22.QueryList<any>;
  _query_MdHint_30_1:import22.QueryList<any>;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _el_39:any;
  compView_39:import1.AppView<import17.MdInput>;
  _RequiredValidator_39_3:import18.Wrapper_RequiredValidator;
  _NG_VALIDATORS_39_4:any[];
  _MdInput_39_5:import19.Wrapper_MdInput;
  _NG_VALUE_ACCESSOR_39_6:any[];
  _NgModel_39_7:import20.Wrapper_NgModel;
  _NgControl_39_8:any;
  _NgControlStatus_39_9:import21.Wrapper_NgControlStatus;
  _StyleCompatibility_39_10:import16.Wrapper_StyleCompatibility;
  _query_MdPlaceholder_39_0:import22.QueryList<any>;
  _query_MdHint_39_1:import22.QueryList<any>;
  _text_40:any;
  _text_41:any;
  _text_42:any;
  _text_43:any;
  _text_44:any;
  _text_45:any;
  _el_46:any;
  _MdCardActions_46_3:import15.Wrapper_MdCardActions;
  _StyleCompatibility_46_4:import16.Wrapper_StyleCompatibility;
  _text_47:any;
  _el_48:any;
  compView_48:import1.AppView<import23.MdButton>;
  _MdButton_48_3:import24.Wrapper_MdButton;
  _text_49:any;
  _text_50:any;
  _el_51:any;
  compView_51:import1.AppView<import23.MdButton>;
  _MdButton_51_3:import24.Wrapper_MdButton;
  _text_52:any;
  _text_53:any;
  _text_54:any;
  _text_55:any;
  _text_56:any;
  _el_57:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ChangePasswordComponent0,renderType_ChangePasswordComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._text_0 = this.renderer.createText(parentRenderNode,' ',(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,parentRenderNode,'p-growl',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_1 = new import13.View_Growl0(this.viewUtils,this,1,this._el_1);
    this._DomHandler_1_3 = new import12.DomHandler();
    this._Growl_1_4 = new import13.Wrapper_Growl(new import25.ElementRef(this._el_1),this._DomHandler_1_3,this.parentView.injectorGet(import26.IterableDiffers,this.parentIndex));
    this.compView_1.create(this._Growl_1_4.context);
    this._text_2 = this.renderer.createText(parentRenderNode,'\n ',(null as any));
    this._el_3 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','col-xs-1 col-sm-3 col-md-4 col-lg-4 col-xl-4'),(null as any));
    this._text_4 = this.renderer.createText(parentRenderNode,'\n  ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','col-xs-8 col-sm-6 col-md-4 col-lg-4 col-xl-4'),(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'\n    ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_5,'md-card',new import3.InlineArray2(2,'class','app-input-section'),(null as any));
    this.compView_7 = new import15.View_MdCard0(this.viewUtils,this,7,this._el_7);
    this._MdCard_7_3 = new import15.Wrapper_MdCard();
    this._StyleCompatibility_7_4 = new import16.Wrapper_StyleCompatibility(this.renderer,new import25.ElementRef(this._el_7));
    this._text_8 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,(null as any),'md-card-title',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._MdCardTitle_9_3 = new import15.Wrapper_MdCardTitle();
    this._StyleCompatibility_9_4 = new import16.Wrapper_StyleCompatibility(this.renderer,new import25.ElementRef(this._el_9));
    this._text_10 = this.renderer.createText(this._el_9,'Change password',(null as any));
    this._text_11 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,(null as any),'md-card-content',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._MdCardContent_12_3 = new import15.Wrapper_MdCardContent();
    this._StyleCompatibility_12_4 = new import16.Wrapper_StyleCompatibility(this.renderer,new import25.ElementRef(this._el_12));
    this._text_13 = this.renderer.createText(this._el_12,'\n        ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_12,'table',new import3.InlineArray4(4,'cellspacing','0','style','width: 100%'),(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'\n          ',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_14,'tbody',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_16,'tr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'\n            ',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_17,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'\n              ',(null as any));
    this._el_21 = import3.createRenderElement(this.renderer,this._el_19,'md-input',new import3.InlineArray16(10,'name','oldPassword','placeholder','Old Password','required','','style','width: 100%','type','password'),(null as any));
    this.compView_21 = new import19.View_MdInput0(this.viewUtils,this,21,this._el_21);
    this._RequiredValidator_21_3 = new import18.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_21_4 = [this._RequiredValidator_21_3.context];
    this._MdInput_21_5 = new import19.Wrapper_MdInput(new import25.ElementRef(this._el_21));
    this._NG_VALUE_ACCESSOR_21_6 = [this._MdInput_21_5.context];
    this._NgModel_21_7 = new import20.Wrapper_NgModel((null as any),this._NG_VALIDATORS_21_4,(null as any),this._NG_VALUE_ACCESSOR_21_6);
    this._NgControl_21_8 = this._NgModel_21_7.context;
    this._NgControlStatus_21_9 = new import21.Wrapper_NgControlStatus(this._NgControl_21_8);
    this._StyleCompatibility_21_10 = new import16.Wrapper_StyleCompatibility(this.renderer,new import25.ElementRef(this._el_21));
    this._query_MdPlaceholder_21_0 = new import22.QueryList<any>();
    this._query_MdHint_21_1 = new import22.QueryList<any>();
    this._text_22 = this.renderer.createText((null as any),'\n              ',(null as any));
    this.compView_21.create(this._MdInput_21_5.context);
    this._text_23 = this.renderer.createText(this._el_19,'\n            ',(null as any));
    this._text_24 = this.renderer.createText(this._el_17,'\n          ',(null as any));
    this._text_25 = this.renderer.createText(this._el_16,'\n          ',(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,this._el_16,'tr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_27 = this.renderer.createText(this._el_26,'\n            ',(null as any));
    this._el_28 = import3.createRenderElement(this.renderer,this._el_26,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_29 = this.renderer.createText(this._el_28,'\n              ',(null as any));
    this._el_30 = import3.createRenderElement(this.renderer,this._el_28,'md-input',new import3.InlineArray16(10,'name','newPassword','placeholder','New Password','required','','style','width: 100%','type','password'),(null as any));
    this.compView_30 = new import19.View_MdInput0(this.viewUtils,this,30,this._el_30);
    this._RequiredValidator_30_3 = new import18.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_30_4 = [this._RequiredValidator_30_3.context];
    this._MdInput_30_5 = new import19.Wrapper_MdInput(new import25.ElementRef(this._el_30));
    this._NG_VALUE_ACCESSOR_30_6 = [this._MdInput_30_5.context];
    this._NgModel_30_7 = new import20.Wrapper_NgModel((null as any),this._NG_VALIDATORS_30_4,(null as any),this._NG_VALUE_ACCESSOR_30_6);
    this._NgControl_30_8 = this._NgModel_30_7.context;
    this._NgControlStatus_30_9 = new import21.Wrapper_NgControlStatus(this._NgControl_30_8);
    this._StyleCompatibility_30_10 = new import16.Wrapper_StyleCompatibility(this.renderer,new import25.ElementRef(this._el_30));
    this._query_MdPlaceholder_30_0 = new import22.QueryList<any>();
    this._query_MdHint_30_1 = new import22.QueryList<any>();
    this._text_31 = this.renderer.createText((null as any),'\n              ',(null as any));
    this.compView_30.create(this._MdInput_30_5.context);
    this._text_32 = this.renderer.createText(this._el_28,'\n            ',(null as any));
    this._text_33 = this.renderer.createText(this._el_26,'\n          ',(null as any));
    this._text_34 = this.renderer.createText(this._el_16,'\n          ',(null as any));
    this._el_35 = import3.createRenderElement(this.renderer,this._el_16,'tr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_36 = this.renderer.createText(this._el_35,'\n            ',(null as any));
    this._el_37 = import3.createRenderElement(this.renderer,this._el_35,'td',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_38 = this.renderer.createText(this._el_37,'\n              ',(null as any));
    this._el_39 = import3.createRenderElement(this.renderer,this._el_37,'md-input',new import3.InlineArray16(10,'name','confirmPassword','placeholder','Confirm Password','required','','style','width: 100%','type','password'),(null as any));
    this.compView_39 = new import19.View_MdInput0(this.viewUtils,this,39,this._el_39);
    this._RequiredValidator_39_3 = new import18.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_39_4 = [this._RequiredValidator_39_3.context];
    this._MdInput_39_5 = new import19.Wrapper_MdInput(new import25.ElementRef(this._el_39));
    this._NG_VALUE_ACCESSOR_39_6 = [this._MdInput_39_5.context];
    this._NgModel_39_7 = new import20.Wrapper_NgModel((null as any),this._NG_VALIDATORS_39_4,(null as any),this._NG_VALUE_ACCESSOR_39_6);
    this._NgControl_39_8 = this._NgModel_39_7.context;
    this._NgControlStatus_39_9 = new import21.Wrapper_NgControlStatus(this._NgControl_39_8);
    this._StyleCompatibility_39_10 = new import16.Wrapper_StyleCompatibility(this.renderer,new import25.ElementRef(this._el_39));
    this._query_MdPlaceholder_39_0 = new import22.QueryList<any>();
    this._query_MdHint_39_1 = new import22.QueryList<any>();
    this._text_40 = this.renderer.createText((null as any),'\n              ',(null as any));
    this.compView_39.create(this._MdInput_39_5.context);
    this._text_41 = this.renderer.createText(this._el_37,'\n            ',(null as any));
    this._text_42 = this.renderer.createText(this._el_35,'\n          ',(null as any));
    this._text_43 = this.renderer.createText(this._el_16,'\n        ',(null as any));
    this._text_44 = this.renderer.createText(this._el_12,'\n      ',(null as any));
    this._text_45 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_46 = import3.createRenderElement(this.renderer,(null as any),'md-card-actions',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._MdCardActions_46_3 = new import15.Wrapper_MdCardActions();
    this._StyleCompatibility_46_4 = new import16.Wrapper_StyleCompatibility(this.renderer,new import25.ElementRef(this._el_46));
    this._text_47 = this.renderer.createText(this._el_46,'\n        ',(null as any));
    this._el_48 = import3.createRenderElement(this.renderer,this._el_46,'button',new import3.InlineArray8(6,'color','primary','md-button','','md-raised-button',''),(null as any));
    this.compView_48 = new import24.View_MdButton0(this.viewUtils,this,48,this._el_48);
    this._MdButton_48_3 = new import24.Wrapper_MdButton(new import25.ElementRef(this._el_48),this.renderer);
    this._text_49 = this.renderer.createText((null as any),'Submit',(null as any));
    this.compView_48.create(this._MdButton_48_3.context);
    this._text_50 = this.renderer.createText(this._el_46,'\n        ',(null as any));
    this._el_51 = import3.createRenderElement(this.renderer,this._el_46,'button',new import3.InlineArray8(6,'color','primary','md-button','','md-raised-button',''),(null as any));
    this.compView_51 = new import24.View_MdButton0(this.viewUtils,this,51,this._el_51);
    this._MdButton_51_3 = new import24.Wrapper_MdButton(new import25.ElementRef(this._el_51),this.renderer);
    this._text_52 = this.renderer.createText((null as any),'Cancel',(null as any));
    this.compView_51.create(this._MdButton_51_3.context);
    this._text_53 = this.renderer.createText(this._el_46,'\n      ',(null as any));
    this._text_54 = this.renderer.createText((null as any),'\n    ',(null as any));
    this.compView_7.create(this._MdCard_7_3.context);
    this._text_55 = this.renderer.createText(this._el_5,'\n  ',(null as any));
    this._text_56 = this.renderer.createText(parentRenderNode,'\n  ',(null as any));
    this._el_57 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','col-xs-1 col-sm-3 col-md-4 col-lg-4 col-xl-4'),(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_21,new import3.InlineArray4(4,'ngModelChange',(null as any),'click',(null as any)),this.eventHandler(this.handleEvent_21));
    this._NgModel_21_7.subscribe(this,this.eventHandler(this.handleEvent_21),true);
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_30,new import3.InlineArray4(4,'ngModelChange',(null as any),'click',(null as any)),this.eventHandler(this.handleEvent_30));
    this._NgModel_30_7.subscribe(this,this.eventHandler(this.handleEvent_30),true);
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_39,new import3.InlineArray4(4,'ngModelChange',(null as any),'click',(null as any)),this.eventHandler(this.handleEvent_39));
    this._NgModel_39_7.subscribe(this,this.eventHandler(this.handleEvent_39),true);
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_48,new import3.InlineArray8(8,'click',(null as any),'mousedown',(null as any),'focus',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_48));
    var disposable_4:Function = import3.subscribeToRenderElement(this,this._el_51,new import3.InlineArray8(8,'click',(null as any),'mousedown',(null as any),'focus',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_51));
    this._query_MdPlaceholder_21_0.reset(([] as any[]));
    this._MdInput_21_5.context._placeholderChild = this._query_MdPlaceholder_21_0.first;
    this._query_MdPlaceholder_30_0.reset(([] as any[]));
    this._MdInput_30_5.context._placeholderChild = this._query_MdPlaceholder_30_0.first;
    this._query_MdPlaceholder_39_0.reset(([] as any[]));
    this._MdInput_39_5.context._placeholderChild = this._query_MdPlaceholder_39_0.first;
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._text_41,
      this._text_42,
      this._text_43,
      this._text_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._text_53,
      this._text_54,
      this._text_55,
      this._text_56,
      this._el_57
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import12.DomHandler) && (1 === requestNodeIndex))) { return this._DomHandler_1_3; }
    if (((token === import11.Growl) && (1 === requestNodeIndex))) { return this._Growl_1_4.context; }
    if (((token === import14.MdCardTitle) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._MdCardTitle_9_3.context; }
    if (((token === import27.StyleCompatibility) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._StyleCompatibility_9_4.context; }
    if (((token === import28.RequiredValidator) && ((21 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._RequiredValidator_21_3.context; }
    if (((token === import29.NG_VALIDATORS) && ((21 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._NG_VALIDATORS_21_4; }
    if (((token === import17.MdInput) && ((21 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._MdInput_21_5.context; }
    if (((token === import30.NG_VALUE_ACCESSOR) && ((21 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._NG_VALUE_ACCESSOR_21_6; }
    if (((token === import31.NgModel) && ((21 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._NgModel_21_7.context; }
    if (((token === import32.NgControl) && ((21 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._NgControl_21_8; }
    if (((token === import33.NgControlStatus) && ((21 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._NgControlStatus_21_9.context; }
    if (((token === import27.StyleCompatibility) && ((21 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._StyleCompatibility_21_10.context; }
    if (((token === import28.RequiredValidator) && ((30 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._RequiredValidator_30_3.context; }
    if (((token === import29.NG_VALIDATORS) && ((30 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._NG_VALIDATORS_30_4; }
    if (((token === import17.MdInput) && ((30 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._MdInput_30_5.context; }
    if (((token === import30.NG_VALUE_ACCESSOR) && ((30 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._NG_VALUE_ACCESSOR_30_6; }
    if (((token === import31.NgModel) && ((30 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._NgModel_30_7.context; }
    if (((token === import32.NgControl) && ((30 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._NgControl_30_8; }
    if (((token === import33.NgControlStatus) && ((30 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._NgControlStatus_30_9.context; }
    if (((token === import27.StyleCompatibility) && ((30 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._StyleCompatibility_30_10.context; }
    if (((token === import28.RequiredValidator) && ((39 <= requestNodeIndex) && (requestNodeIndex <= 40)))) { return this._RequiredValidator_39_3.context; }
    if (((token === import29.NG_VALIDATORS) && ((39 <= requestNodeIndex) && (requestNodeIndex <= 40)))) { return this._NG_VALIDATORS_39_4; }
    if (((token === import17.MdInput) && ((39 <= requestNodeIndex) && (requestNodeIndex <= 40)))) { return this._MdInput_39_5.context; }
    if (((token === import30.NG_VALUE_ACCESSOR) && ((39 <= requestNodeIndex) && (requestNodeIndex <= 40)))) { return this._NG_VALUE_ACCESSOR_39_6; }
    if (((token === import31.NgModel) && ((39 <= requestNodeIndex) && (requestNodeIndex <= 40)))) { return this._NgModel_39_7.context; }
    if (((token === import32.NgControl) && ((39 <= requestNodeIndex) && (requestNodeIndex <= 40)))) { return this._NgControl_39_8; }
    if (((token === import33.NgControlStatus) && ((39 <= requestNodeIndex) && (requestNodeIndex <= 40)))) { return this._NgControlStatus_39_9.context; }
    if (((token === import27.StyleCompatibility) && ((39 <= requestNodeIndex) && (requestNodeIndex <= 40)))) { return this._StyleCompatibility_39_10.context; }
    if (((token === import14.MdCardContent) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 44)))) { return this._MdCardContent_12_3.context; }
    if (((token === import27.StyleCompatibility) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 44)))) { return this._StyleCompatibility_12_4.context; }
    if (((token === import23.MdButton) && ((48 <= requestNodeIndex) && (requestNodeIndex <= 49)))) { return this._MdButton_48_3.context; }
    if (((token === import23.MdButton) && ((51 <= requestNodeIndex) && (requestNodeIndex <= 52)))) { return this._MdButton_51_3.context; }
    if (((token === import14.MdCardActions) && ((46 <= requestNodeIndex) && (requestNodeIndex <= 53)))) { return this._MdCardActions_46_3.context; }
    if (((token === import27.StyleCompatibility) && ((46 <= requestNodeIndex) && (requestNodeIndex <= 53)))) { return this._StyleCompatibility_46_4.context; }
    if (((token === import14.MdCard) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 54)))) { return this._MdCard_7_3.context; }
    if (((token === import27.StyleCompatibility) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 54)))) { return this._StyleCompatibility_7_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1_0_0:any = this.context.msgs;
    this._Growl_1_4.check_value(currVal_1_0_0,throwOnChange,false);
    this._Growl_1_4.ngDoCheck(this,this._el_1,throwOnChange);
    if (this._MdCard_7_3.ngDoCheck(this,this._el_7,throwOnChange)) { this.compView_7.markAsCheckOnce(); }
    this._StyleCompatibility_7_4.ngDoCheck(this,this._el_7,throwOnChange);
    this._MdCardTitle_9_3.ngDoCheck(this,this._el_9,throwOnChange);
    this._StyleCompatibility_9_4.ngDoCheck(this,this._el_9,throwOnChange);
    this._MdCardContent_12_3.ngDoCheck(this,this._el_12,throwOnChange);
    this._StyleCompatibility_12_4.ngDoCheck(this,this._el_12,throwOnChange);
    const currVal_21_0_0:any = '';
    this._RequiredValidator_21_3.check_required(currVal_21_0_0,throwOnChange,false);
    this._RequiredValidator_21_3.ngDoCheck(this,this._el_21,throwOnChange);
    const currVal_21_1_0:any = 'Old Password';
    this._MdInput_21_5.check_placeholder(currVal_21_1_0,throwOnChange,false);
    const currVal_21_1_1:any = 'password';
    this._MdInput_21_5.check_type(currVal_21_1_1,throwOnChange,false);
    const currVal_21_1_2:any = 'oldPassword';
    this._MdInput_21_5.check_name(currVal_21_1_2,throwOnChange,false);
    const currVal_21_1_3:any = '';
    this._MdInput_21_5.check_required(currVal_21_1_3,throwOnChange,false);
    this._MdInput_21_5.ngDoCheck(this,this._el_21,throwOnChange);
    const currVal_21_2_0:any = 'oldPassword';
    this._NgModel_21_7.check_name(currVal_21_2_0,throwOnChange,false);
    const currVal_21_2_1:any = this.context.userAccountChangePasswordResource.oldPassword;
    this._NgModel_21_7.check_model(currVal_21_2_1,throwOnChange,false);
    this._NgModel_21_7.ngDoCheck(this,this._el_21,throwOnChange);
    this._NgControlStatus_21_9.ngDoCheck(this,this._el_21,throwOnChange);
    this._StyleCompatibility_21_10.ngDoCheck(this,this._el_21,throwOnChange);
    const currVal_30_0_0:any = '';
    this._RequiredValidator_30_3.check_required(currVal_30_0_0,throwOnChange,false);
    this._RequiredValidator_30_3.ngDoCheck(this,this._el_30,throwOnChange);
    const currVal_30_1_0:any = 'New Password';
    this._MdInput_30_5.check_placeholder(currVal_30_1_0,throwOnChange,false);
    const currVal_30_1_1:any = 'password';
    this._MdInput_30_5.check_type(currVal_30_1_1,throwOnChange,false);
    const currVal_30_1_2:any = 'newPassword';
    this._MdInput_30_5.check_name(currVal_30_1_2,throwOnChange,false);
    const currVal_30_1_3:any = '';
    this._MdInput_30_5.check_required(currVal_30_1_3,throwOnChange,false);
    this._MdInput_30_5.ngDoCheck(this,this._el_30,throwOnChange);
    const currVal_30_2_0:any = 'newPassword';
    this._NgModel_30_7.check_name(currVal_30_2_0,throwOnChange,false);
    const currVal_30_2_1:any = this.context.userAccountChangePasswordResource.newPassword;
    this._NgModel_30_7.check_model(currVal_30_2_1,throwOnChange,false);
    this._NgModel_30_7.ngDoCheck(this,this._el_30,throwOnChange);
    this._NgControlStatus_30_9.ngDoCheck(this,this._el_30,throwOnChange);
    this._StyleCompatibility_30_10.ngDoCheck(this,this._el_30,throwOnChange);
    const currVal_39_0_0:any = '';
    this._RequiredValidator_39_3.check_required(currVal_39_0_0,throwOnChange,false);
    this._RequiredValidator_39_3.ngDoCheck(this,this._el_39,throwOnChange);
    const currVal_39_1_0:any = 'Confirm Password';
    this._MdInput_39_5.check_placeholder(currVal_39_1_0,throwOnChange,false);
    const currVal_39_1_1:any = 'password';
    this._MdInput_39_5.check_type(currVal_39_1_1,throwOnChange,false);
    const currVal_39_1_2:any = 'confirmPassword';
    this._MdInput_39_5.check_name(currVal_39_1_2,throwOnChange,false);
    const currVal_39_1_3:any = '';
    this._MdInput_39_5.check_required(currVal_39_1_3,throwOnChange,false);
    this._MdInput_39_5.ngDoCheck(this,this._el_39,throwOnChange);
    const currVal_39_2_0:any = 'confirmPassword';
    this._NgModel_39_7.check_name(currVal_39_2_0,throwOnChange,false);
    const currVal_39_2_1:any = this.context.userAccountChangePasswordResource.confirmPassword;
    this._NgModel_39_7.check_model(currVal_39_2_1,throwOnChange,false);
    this._NgModel_39_7.ngDoCheck(this,this._el_39,throwOnChange);
    this._NgControlStatus_39_9.ngDoCheck(this,this._el_39,throwOnChange);
    this._StyleCompatibility_39_10.ngDoCheck(this,this._el_39,throwOnChange);
    this._MdCardActions_46_3.ngDoCheck(this,this._el_46,throwOnChange);
    this._StyleCompatibility_46_4.ngDoCheck(this,this._el_46,throwOnChange);
    const currVal_48_0_0:any = 'primary';
    this._MdButton_48_3.check_color(currVal_48_0_0,throwOnChange,false);
    if (this._MdButton_48_3.ngDoCheck(this,this._el_48,throwOnChange)) { this.compView_48.markAsCheckOnce(); }
    const currVal_51_0_0:any = 'primary';
    this._MdButton_51_3.check_color(currVal_51_0_0,throwOnChange,false);
    if (this._MdButton_51_3.ngDoCheck(this,this._el_51,throwOnChange)) { this.compView_51.markAsCheckOnce(); }
    if (!throwOnChange) {
      if (this._query_MdHint_21_1.dirty) {
        this._query_MdHint_21_1.reset(([] as any[]));
        this._MdInput_21_5.context._hintChildren = this._query_MdHint_21_1;
        this._query_MdHint_21_1.notifyOnChanges();
      }
      if (this._query_MdHint_30_1.dirty) {
        this._query_MdHint_30_1.reset(([] as any[]));
        this._MdInput_30_5.context._hintChildren = this._query_MdHint_30_1;
        this._query_MdHint_30_1.notifyOnChanges();
      }
      if (this._query_MdHint_39_1.dirty) {
        this._query_MdHint_39_1.reset(([] as any[]));
        this._MdInput_39_5.context._hintChildren = this._query_MdHint_39_1;
        this._query_MdHint_39_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._MdInput_21_5.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._MdInput_30_5.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._MdInput_39_5.context.ngAfterContentInit(); }
    }
    this._RequiredValidator_21_3.checkHost(this,this.compView_21,this._el_21,throwOnChange);
    this._MdInput_21_5.checkHost(this,this.compView_21,this._el_21,throwOnChange);
    this._NgControlStatus_21_9.checkHost(this,this.compView_21,this._el_21,throwOnChange);
    this._RequiredValidator_30_3.checkHost(this,this.compView_30,this._el_30,throwOnChange);
    this._MdInput_30_5.checkHost(this,this.compView_30,this._el_30,throwOnChange);
    this._NgControlStatus_30_9.checkHost(this,this.compView_30,this._el_30,throwOnChange);
    this._RequiredValidator_39_3.checkHost(this,this.compView_39,this._el_39,throwOnChange);
    this._MdInput_39_5.checkHost(this,this.compView_39,this._el_39,throwOnChange);
    this._NgControlStatus_39_9.checkHost(this,this.compView_39,this._el_39,throwOnChange);
    this._MdButton_48_3.checkHost(this,this.compView_48,this._el_48,throwOnChange);
    this._MdButton_51_3.checkHost(this,this.compView_51,this._el_51,throwOnChange);
    this.compView_1.internalDetectChanges(throwOnChange);
    this.compView_7.internalDetectChanges(throwOnChange);
    this.compView_21.internalDetectChanges(throwOnChange);
    this.compView_30.internalDetectChanges(throwOnChange);
    this.compView_39.internalDetectChanges(throwOnChange);
    this.compView_48.internalDetectChanges(throwOnChange);
    this.compView_51.internalDetectChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Growl_1_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this.compView_1.destroy();
    this.compView_7.destroy();
    this.compView_21.destroy();
    this.compView_30.destroy();
    this.compView_39.destroy();
    this.compView_48.destroy();
    this.compView_51.destroy();
    this._Growl_1_4.ngOnDestroy();
    this._MdInput_21_5.ngOnDestroy();
    this._NgModel_21_7.ngOnDestroy();
    this._MdInput_30_5.ngOnDestroy();
    this._NgModel_30_7.ngOnDestroy();
    this._MdInput_39_5.ngOnDestroy();
    this._NgModel_39_7.ngOnDestroy();
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 7) && (ngContentIndex == 0))) {
      cb(this._text_8,ctx);
      cb(this._el_9,ctx);
      cb(this._text_11,ctx);
      cb(this._el_12,ctx);
      cb(this._text_45,ctx);
      cb(this._el_46,ctx);
      cb(this._text_54,ctx);
    }
    if (((nodeIndex == 21) && (ngContentIndex == 0))) {  }
    if (((nodeIndex == 21) && (ngContentIndex == 1))) {  }
    if (((nodeIndex == 21) && (ngContentIndex == 2))) {  }
    if (((nodeIndex == 21) && (ngContentIndex == 3))) {  }
    if (((nodeIndex == 30) && (ngContentIndex == 0))) {  }
    if (((nodeIndex == 30) && (ngContentIndex == 1))) {  }
    if (((nodeIndex == 30) && (ngContentIndex == 2))) {  }
    if (((nodeIndex == 30) && (ngContentIndex == 3))) {  }
    if (((nodeIndex == 39) && (ngContentIndex == 0))) {  }
    if (((nodeIndex == 39) && (ngContentIndex == 1))) {  }
    if (((nodeIndex == 39) && (ngContentIndex == 2))) {  }
    if (((nodeIndex == 39) && (ngContentIndex == 3))) {  }
    if (((nodeIndex == 48) && (ngContentIndex == 0))) { cb(this._text_49,ctx); }
    if (((nodeIndex == 51) && (ngContentIndex == 0))) { cb(this._text_52,ctx); }
  }
  handleEvent_21(eventName:string,$event:any):boolean {
    this.compView_21.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdInput_21_5.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.userAccountChangePasswordResource.oldPassword = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_30(eventName:string,$event:any):boolean {
    this.compView_30.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdInput_30_5.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.userAccountChangePasswordResource.newPassword = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_39(eventName:string,$event:any):boolean {
    this.compView_39.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdInput_39_5.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.userAccountChangePasswordResource.confirmPassword = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_48(eventName:string,$event:any):boolean {
    this.compView_48.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdButton_48_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.submitChangePassword()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_51(eventName:string,$event:any):boolean {
    this.compView_51.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdButton_51_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.cancel()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}