/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../src/app/analytics/analytics.root.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from './analytics.component.css.shim.ngstyle';
import * as import9 from '@angular/material/card/card';
import * as import10 from '../../../node_modules/@angular/material/card/card.ngfactory';
import * as import11 from '../../../node_modules/@angular/material/core/compatibility/style-compatibility.ngfactory';
import * as import12 from '../../../../src/app/analytics/tabs.component';
import * as import13 from './tabs.component.ngfactory';
import * as import14 from '@angular/core/src/linker/query_list';
import * as import15 from '../../../../src/app/analytics/tab.component';
import * as import16 from './tab.component.ngfactory';
import * as import17 from 'ng2-google-charts/google-chart/google-chart.component';
import * as import18 from '../../../node_modules/ng2-google-charts/google-chart/google-chart.component.ngfactory';
import * as import19 from '@angular/core/src/linker/element_ref';
import * as import20 from 'ng2-google-charts/google-charts-loader.service';
import * as import21 from '@angular/material/core/compatibility/style-compatibility';
export class Wrapper_AnalyticsComponent {
  /*private*/ _eventHandler:Function;
  context:import0.AnalyticsComponent;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import0.AnalyticsComponent();
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_AnalyticsComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_AnalyticsComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.AnalyticsComponent>;
  _AnalyticsComponent_0_3:Wrapper_AnalyticsComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AnalyticsComponent_Host0,renderType_AnalyticsComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'analytics',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_AnalyticsComponent0(this.viewUtils,this,0,this._el_0);
    this._AnalyticsComponent_0_3 = new Wrapper_AnalyticsComponent();
    this.compView_0.create(this._AnalyticsComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._AnalyticsComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.AnalyticsComponent) && (0 === requestNodeIndex))) { return this._AnalyticsComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._AnalyticsComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const AnalyticsComponentNgFactory:import7.ComponentFactory<import0.AnalyticsComponent> = new import7.ComponentFactory<import0.AnalyticsComponent>('analytics',View_AnalyticsComponent_Host0,import0.AnalyticsComponent);
const styles_AnalyticsComponent:any[] = [import8.styles];
var renderType_AnalyticsComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_AnalyticsComponent,{});
export class View_AnalyticsComponent0 extends import1.AppView<import0.AnalyticsComponent> {
  _text_0:any;
  _text_1:any;
  _text_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  compView_8:import1.AppView<import9.MdCard>;
  _MdCard_8_3:import10.Wrapper_MdCard;
  _StyleCompatibility_8_4:import11.Wrapper_StyleCompatibility;
  _text_9:any;
  _el_10:any;
  _MdCardTitle_10_3:import10.Wrapper_MdCardTitle;
  _StyleCompatibility_10_4:import11.Wrapper_StyleCompatibility;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _MdCardContent_13_3:import10.Wrapper_MdCardContent;
  _StyleCompatibility_13_4:import11.Wrapper_StyleCompatibility;
  _text_14:any;
  _el_15:any;
  compView_15:import1.AppView<import12.Tabs>;
  _Tabs_15_3:import13.Wrapper_Tabs;
  _query_Tab_15_0:import14.QueryList<any>;
  _text_16:any;
  _el_17:any;
  compView_17:import1.AppView<import15.Tab>;
  _Tab_17_3:import16.Wrapper_Tab;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  compView_20:import1.AppView<import15.Tab>;
  _Tab_20_3:import16.Wrapper_Tab;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  compView_23:import1.AppView<import15.Tab>;
  _Tab_23_3:import16.Wrapper_Tab;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  compView_26:import1.AppView<import15.Tab>;
  _Tab_26_3:import16.Wrapper_Tab;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  compView_29:import1.AppView<import15.Tab>;
  _Tab_29_3:import16.Wrapper_Tab;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  _el_34:any;
  _MdCardActions_34_3:import10.Wrapper_MdCardActions;
  _StyleCompatibility_34_4:import11.Wrapper_StyleCompatibility;
  _text_35:any;
  _text_36:any;
  _text_37:any;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _el_41:any;
  compView_41:import1.AppView<import9.MdCard>;
  _MdCard_41_3:import10.Wrapper_MdCard;
  _StyleCompatibility_41_4:import11.Wrapper_StyleCompatibility;
  _text_42:any;
  _el_43:any;
  _MdCardTitle_43_3:import10.Wrapper_MdCardTitle;
  _StyleCompatibility_43_4:import11.Wrapper_StyleCompatibility;
  _text_44:any;
  _text_45:any;
  _el_46:any;
  _MdCardContent_46_3:import10.Wrapper_MdCardContent;
  _StyleCompatibility_46_4:import11.Wrapper_StyleCompatibility;
  _text_47:any;
  _el_48:any;
  compView_48:import1.AppView<import17.GoogleChartComponent>;
  _GoogleChartComponent_48_3:import18.Wrapper_GoogleChartComponent;
  _text_49:any;
  _text_50:any;
  _el_51:any;
  _MdCardActions_51_3:import10.Wrapper_MdCardActions;
  _StyleCompatibility_51_4:import11.Wrapper_StyleCompatibility;
  _text_52:any;
  _text_53:any;
  _text_54:any;
  _text_55:any;
  _el_56:any;
  _text_57:any;
  _el_58:any;
  compView_58:import1.AppView<import9.MdCard>;
  _MdCard_58_3:import10.Wrapper_MdCard;
  _StyleCompatibility_58_4:import11.Wrapper_StyleCompatibility;
  _text_59:any;
  _el_60:any;
  _MdCardTitle_60_3:import10.Wrapper_MdCardTitle;
  _StyleCompatibility_60_4:import11.Wrapper_StyleCompatibility;
  _text_61:any;
  _text_62:any;
  _el_63:any;
  _MdCardContent_63_3:import10.Wrapper_MdCardContent;
  _StyleCompatibility_63_4:import11.Wrapper_StyleCompatibility;
  _text_64:any;
  _el_65:any;
  compView_65:import1.AppView<import17.GoogleChartComponent>;
  _GoogleChartComponent_65_3:import18.Wrapper_GoogleChartComponent;
  _text_66:any;
  _text_67:any;
  _el_68:any;
  _MdCardActions_68_3:import10.Wrapper_MdCardActions;
  _StyleCompatibility_68_4:import11.Wrapper_StyleCompatibility;
  _text_69:any;
  _text_70:any;
  _text_71:any;
  _text_72:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AnalyticsComponent0,renderType_AnalyticsComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._text_1 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._text_2 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._text_3 = this.renderer.createText(parentRenderNode,'\n  ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','col-xs-1 col-sm-3 col-md-4 col-lg-4 col-xl-4'),(null as any));
    this._text_5 = this.renderer.createText(parentRenderNode,'\n  ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','divtabs'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n    ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_6,'md-card',new import3.InlineArray2(2,'class','app-analytics-display-section'),(null as any));
    this.compView_8 = new import10.View_MdCard0(this.viewUtils,this,8,this._el_8);
    this._MdCard_8_3 = new import10.Wrapper_MdCard();
    this._StyleCompatibility_8_4 = new import11.Wrapper_StyleCompatibility(this.renderer,new import19.ElementRef(this._el_8));
    this._text_9 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,(null as any),'md-card-title',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._MdCardTitle_10_3 = new import10.Wrapper_MdCardTitle();
    this._StyleCompatibility_10_4 = new import11.Wrapper_StyleCompatibility(this.renderer,new import19.ElementRef(this._el_10));
    this._text_11 = this.renderer.createText(this._el_10,'Campaign Summary',(null as any));
    this._text_12 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,(null as any),'md-card-content',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._MdCardContent_13_3 = new import10.Wrapper_MdCardContent();
    this._StyleCompatibility_13_4 = new import11.Wrapper_StyleCompatibility(this.renderer,new import19.ElementRef(this._el_13));
    this._text_14 = this.renderer.createText(this._el_13,'\n	  ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_13,'tabs',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_15 = new import13.View_Tabs0(this.viewUtils,this,15,this._el_15);
    this._Tabs_15_3 = new import13.Wrapper_Tabs();
    this._query_Tab_15_0 = new import14.QueryList<any>();
    this._text_16 = this.renderer.createText((null as any),'\n		',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,(null as any),'tab',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_17 = new import16.View_Tab0(this.viewUtils,this,17,this._el_17);
    this._Tab_17_3 = new import16.Wrapper_Tab();
    this._text_18 = this.renderer.createText((null as any),'Tab 1 Content\n		',(null as any));
    this.compView_17.create(this._Tab_17_3.context);
    this._text_19 = this.renderer.createText((null as any),'\n		',(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,(null as any),'tab',new import3.InlineArray2(2,'tabTitle','Clicked'),(null as any));
    this.compView_20 = new import16.View_Tab0(this.viewUtils,this,20,this._el_20);
    this._Tab_20_3 = new import16.Wrapper_Tab();
    this._text_21 = this.renderer.createText((null as any),'Tab 2 Content',(null as any));
    this.compView_20.create(this._Tab_20_3.context);
    this._text_22 = this.renderer.createText((null as any),'\n		',(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,(null as any),'tab',new import3.InlineArray2(2,'tabTitle','Unsubscribed'),(null as any));
    this.compView_23 = new import16.View_Tab0(this.viewUtils,this,23,this._el_23);
    this._Tab_23_3 = new import16.Wrapper_Tab();
    this._text_24 = this.renderer.createText((null as any),'Tab 3 Content',(null as any));
    this.compView_23.create(this._Tab_23_3.context);
    this._text_25 = this.renderer.createText((null as any),'\n		',(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,(null as any),'tab',new import3.InlineArray2(2,'tabTitle','Bounced'),(null as any));
    this.compView_26 = new import16.View_Tab0(this.viewUtils,this,26,this._el_26);
    this._Tab_26_3 = new import16.Wrapper_Tab();
    this._text_27 = this.renderer.createText((null as any),'Tab 4 Content',(null as any));
    this.compView_26.create(this._Tab_26_3.context);
    this._text_28 = this.renderer.createText((null as any),'\n		',(null as any));
    this._el_29 = import3.createRenderElement(this.renderer,(null as any),'tab',new import3.InlineArray2(2,'tabTitle','Complaints'),(null as any));
    this.compView_29 = new import16.View_Tab0(this.viewUtils,this,29,this._el_29);
    this._Tab_29_3 = new import16.Wrapper_Tab();
    this._text_30 = this.renderer.createText((null as any),'Tab 5 Content',(null as any));
    this.compView_29.create(this._Tab_29_3.context);
    this._text_31 = this.renderer.createText((null as any),'\n      ',(null as any));
    this.compView_15.create(this._Tabs_15_3.context);
    this._text_32 = this.renderer.createText(this._el_13,'\n      ',(null as any));
    this._text_33 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_34 = import3.createRenderElement(this.renderer,(null as any),'md-card-actions',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._MdCardActions_34_3 = new import10.Wrapper_MdCardActions();
    this._StyleCompatibility_34_4 = new import11.Wrapper_StyleCompatibility(this.renderer,new import19.ElementRef(this._el_34));
    this._text_35 = this.renderer.createText(this._el_34,'\n      ',(null as any));
    this._text_36 = this.renderer.createText((null as any),'\n    ',(null as any));
    this.compView_8.create(this._MdCard_8_3.context);
    this._text_37 = this.renderer.createText(this._el_6,'\n  ',(null as any));
    this._text_38 = this.renderer.createText(parentRenderNode,'\n  ',(null as any));
    this._el_39 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','barChartTabs'),(null as any));
    this._text_40 = this.renderer.createText(this._el_39,'\n      ',(null as any));
    this._el_41 = import3.createRenderElement(this.renderer,this._el_39,'md-card',new import3.InlineArray2(2,'class','app-analytics-display-section'),(null as any));
    this.compView_41 = new import10.View_MdCard0(this.viewUtils,this,41,this._el_41);
    this._MdCard_41_3 = new import10.Wrapper_MdCard();
    this._StyleCompatibility_41_4 = new import11.Wrapper_StyleCompatibility(this.renderer,new import19.ElementRef(this._el_41));
    this._text_42 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_43 = import3.createRenderElement(this.renderer,(null as any),'md-card-title',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._MdCardTitle_43_3 = new import10.Wrapper_MdCardTitle();
    this._StyleCompatibility_43_4 = new import11.Wrapper_StyleCompatibility(this.renderer,new import19.ElementRef(this._el_43));
    this._text_44 = this.renderer.createText(this._el_43,'Percentage wise comparison',(null as any));
    this._text_45 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_46 = import3.createRenderElement(this.renderer,(null as any),'md-card-content',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._MdCardContent_46_3 = new import10.Wrapper_MdCardContent();
    this._StyleCompatibility_46_4 = new import11.Wrapper_StyleCompatibility(this.renderer,new import19.ElementRef(this._el_46));
    this._text_47 = this.renderer.createText(this._el_46,'\n		',(null as any));
    this._el_48 = import3.createRenderElement(this.renderer,this._el_46,'google-chart',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_48 = new import18.View_GoogleChartComponent0(this.viewUtils,this,48,this._el_48);
    this._GoogleChartComponent_48_3 = new import18.Wrapper_GoogleChartComponent(new import19.ElementRef(this._el_48),this.parentView.injectorGet(import20.GoogleChartsLoaderService,this.parentIndex));
    this.compView_48.create(this._GoogleChartComponent_48_3.context);
    this._text_49 = this.renderer.createText(this._el_46,'\n      ',(null as any));
    this._text_50 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_51 = import3.createRenderElement(this.renderer,(null as any),'md-card-actions',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._MdCardActions_51_3 = new import10.Wrapper_MdCardActions();
    this._StyleCompatibility_51_4 = new import11.Wrapper_StyleCompatibility(this.renderer,new import19.ElementRef(this._el_51));
    this._text_52 = this.renderer.createText(this._el_51,'\n      ',(null as any));
    this._text_53 = this.renderer.createText((null as any),'\n    ',(null as any));
    this.compView_41.create(this._MdCard_41_3.context);
    this._text_54 = this.renderer.createText(this._el_39,'\n  ',(null as any));
    this._text_55 = this.renderer.createText(parentRenderNode,'\n   ',(null as any));
    this._el_56 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','barChartTabs'),(null as any));
    this._text_57 = this.renderer.createText(this._el_56,'\n      ',(null as any));
    this._el_58 = import3.createRenderElement(this.renderer,this._el_56,'md-card',new import3.InlineArray2(2,'class','app-analytics-display-section'),(null as any));
    this.compView_58 = new import10.View_MdCard0(this.viewUtils,this,58,this._el_58);
    this._MdCard_58_3 = new import10.Wrapper_MdCard();
    this._StyleCompatibility_58_4 = new import11.Wrapper_StyleCompatibility(this.renderer,new import19.ElementRef(this._el_58));
    this._text_59 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_60 = import3.createRenderElement(this.renderer,(null as any),'md-card-title',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._MdCardTitle_60_3 = new import10.Wrapper_MdCardTitle();
    this._StyleCompatibility_60_4 = new import11.Wrapper_StyleCompatibility(this.renderer,new import19.ElementRef(this._el_60));
    this._text_61 = this.renderer.createText(this._el_60,'Metrics over Time',(null as any));
    this._text_62 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_63 = import3.createRenderElement(this.renderer,(null as any),'md-card-content',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._MdCardContent_63_3 = new import10.Wrapper_MdCardContent();
    this._StyleCompatibility_63_4 = new import11.Wrapper_StyleCompatibility(this.renderer,new import19.ElementRef(this._el_63));
    this._text_64 = this.renderer.createText(this._el_63,'\n		',(null as any));
    this._el_65 = import3.createRenderElement(this.renderer,this._el_63,'google-chart',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_65 = new import18.View_GoogleChartComponent0(this.viewUtils,this,65,this._el_65);
    this._GoogleChartComponent_65_3 = new import18.Wrapper_GoogleChartComponent(new import19.ElementRef(this._el_65),this.parentView.injectorGet(import20.GoogleChartsLoaderService,this.parentIndex));
    this.compView_65.create(this._GoogleChartComponent_65_3.context);
    this._text_66 = this.renderer.createText(this._el_63,'\n      ',(null as any));
    this._text_67 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_68 = import3.createRenderElement(this.renderer,(null as any),'md-card-actions',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._MdCardActions_68_3 = new import10.Wrapper_MdCardActions();
    this._StyleCompatibility_68_4 = new import11.Wrapper_StyleCompatibility(this.renderer,new import19.ElementRef(this._el_68));
    this._text_69 = this.renderer.createText(this._el_68,'\n      ',(null as any));
    this._text_70 = this.renderer.createText((null as any),'\n    ',(null as any));
    this.compView_58.create(this._MdCard_58_3.context);
    this._text_71 = this.renderer.createText(this._el_56,'\n  ',(null as any));
    this._text_72 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._text_1,
      this._text_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._text_31,
      this._text_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._text_36,
      this._text_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._text_53,
      this._text_54,
      this._text_55,
      this._el_56,
      this._text_57,
      this._el_58,
      this._text_59,
      this._el_60,
      this._text_61,
      this._text_62,
      this._el_63,
      this._text_64,
      this._el_65,
      this._text_66,
      this._text_67,
      this._el_68,
      this._text_69,
      this._text_70,
      this._text_71,
      this._text_72
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import9.MdCardTitle) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._MdCardTitle_10_3.context; }
    if (((token === import21.StyleCompatibility) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._StyleCompatibility_10_4.context; }
    if (((token === import15.Tab) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._Tab_17_3.context; }
    if (((token === import15.Tab) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._Tab_20_3.context; }
    if (((token === import15.Tab) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 24)))) { return this._Tab_23_3.context; }
    if (((token === import15.Tab) && ((26 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._Tab_26_3.context; }
    if (((token === import15.Tab) && ((29 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._Tab_29_3.context; }
    if (((token === import12.Tabs) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._Tabs_15_3.context; }
    if (((token === import9.MdCardContent) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._MdCardContent_13_3.context; }
    if (((token === import21.StyleCompatibility) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._StyleCompatibility_13_4.context; }
    if (((token === import9.MdCardActions) && ((34 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._MdCardActions_34_3.context; }
    if (((token === import21.StyleCompatibility) && ((34 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._StyleCompatibility_34_4.context; }
    if (((token === import9.MdCard) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 36)))) { return this._MdCard_8_3.context; }
    if (((token === import21.StyleCompatibility) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 36)))) { return this._StyleCompatibility_8_4.context; }
    if (((token === import9.MdCardTitle) && ((43 <= requestNodeIndex) && (requestNodeIndex <= 44)))) { return this._MdCardTitle_43_3.context; }
    if (((token === import21.StyleCompatibility) && ((43 <= requestNodeIndex) && (requestNodeIndex <= 44)))) { return this._StyleCompatibility_43_4.context; }
    if (((token === import17.GoogleChartComponent) && (48 === requestNodeIndex))) { return this._GoogleChartComponent_48_3.context; }
    if (((token === import9.MdCardContent) && ((46 <= requestNodeIndex) && (requestNodeIndex <= 49)))) { return this._MdCardContent_46_3.context; }
    if (((token === import21.StyleCompatibility) && ((46 <= requestNodeIndex) && (requestNodeIndex <= 49)))) { return this._StyleCompatibility_46_4.context; }
    if (((token === import9.MdCardActions) && ((51 <= requestNodeIndex) && (requestNodeIndex <= 52)))) { return this._MdCardActions_51_3.context; }
    if (((token === import21.StyleCompatibility) && ((51 <= requestNodeIndex) && (requestNodeIndex <= 52)))) { return this._StyleCompatibility_51_4.context; }
    if (((token === import9.MdCard) && ((41 <= requestNodeIndex) && (requestNodeIndex <= 53)))) { return this._MdCard_41_3.context; }
    if (((token === import21.StyleCompatibility) && ((41 <= requestNodeIndex) && (requestNodeIndex <= 53)))) { return this._StyleCompatibility_41_4.context; }
    if (((token === import9.MdCardTitle) && ((60 <= requestNodeIndex) && (requestNodeIndex <= 61)))) { return this._MdCardTitle_60_3.context; }
    if (((token === import21.StyleCompatibility) && ((60 <= requestNodeIndex) && (requestNodeIndex <= 61)))) { return this._StyleCompatibility_60_4.context; }
    if (((token === import17.GoogleChartComponent) && (65 === requestNodeIndex))) { return this._GoogleChartComponent_65_3.context; }
    if (((token === import9.MdCardContent) && ((63 <= requestNodeIndex) && (requestNodeIndex <= 66)))) { return this._MdCardContent_63_3.context; }
    if (((token === import21.StyleCompatibility) && ((63 <= requestNodeIndex) && (requestNodeIndex <= 66)))) { return this._StyleCompatibility_63_4.context; }
    if (((token === import9.MdCardActions) && ((68 <= requestNodeIndex) && (requestNodeIndex <= 69)))) { return this._MdCardActions_68_3.context; }
    if (((token === import21.StyleCompatibility) && ((68 <= requestNodeIndex) && (requestNodeIndex <= 69)))) { return this._StyleCompatibility_68_4.context; }
    if (((token === import9.MdCard) && ((58 <= requestNodeIndex) && (requestNodeIndex <= 70)))) { return this._MdCard_58_3.context; }
    if (((token === import21.StyleCompatibility) && ((58 <= requestNodeIndex) && (requestNodeIndex <= 70)))) { return this._StyleCompatibility_58_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._MdCard_8_3.ngDoCheck(this,this._el_8,throwOnChange)) { this.compView_8.markAsCheckOnce(); }
    this._StyleCompatibility_8_4.ngDoCheck(this,this._el_8,throwOnChange);
    this._MdCardTitle_10_3.ngDoCheck(this,this._el_10,throwOnChange);
    this._StyleCompatibility_10_4.ngDoCheck(this,this._el_10,throwOnChange);
    this._MdCardContent_13_3.ngDoCheck(this,this._el_13,throwOnChange);
    this._StyleCompatibility_13_4.ngDoCheck(this,this._el_13,throwOnChange);
    this._Tabs_15_3.ngDoCheck(this,this._el_15,throwOnChange);
    const currVal_17_0_0:any = 'Total';
    this._Tab_17_3.check_title(currVal_17_0_0,throwOnChange,false);
    this._Tab_17_3.ngDoCheck(this,this._el_17,throwOnChange);
    const currVal_20_0_0:any = 'Clicked';
    this._Tab_20_3.check_title(currVal_20_0_0,throwOnChange,false);
    this._Tab_20_3.ngDoCheck(this,this._el_20,throwOnChange);
    const currVal_23_0_0:any = 'Unsubscribed';
    this._Tab_23_3.check_title(currVal_23_0_0,throwOnChange,false);
    this._Tab_23_3.ngDoCheck(this,this._el_23,throwOnChange);
    const currVal_26_0_0:any = 'Bounced';
    this._Tab_26_3.check_title(currVal_26_0_0,throwOnChange,false);
    this._Tab_26_3.ngDoCheck(this,this._el_26,throwOnChange);
    const currVal_29_0_0:any = 'Complaints';
    this._Tab_29_3.check_title(currVal_29_0_0,throwOnChange,false);
    this._Tab_29_3.ngDoCheck(this,this._el_29,throwOnChange);
    this._MdCardActions_34_3.ngDoCheck(this,this._el_34,throwOnChange);
    this._StyleCompatibility_34_4.ngDoCheck(this,this._el_34,throwOnChange);
    if (this._MdCard_41_3.ngDoCheck(this,this._el_41,throwOnChange)) { this.compView_41.markAsCheckOnce(); }
    this._StyleCompatibility_41_4.ngDoCheck(this,this._el_41,throwOnChange);
    this._MdCardTitle_43_3.ngDoCheck(this,this._el_43,throwOnChange);
    this._StyleCompatibility_43_4.ngDoCheck(this,this._el_43,throwOnChange);
    this._MdCardContent_46_3.ngDoCheck(this,this._el_46,throwOnChange);
    this._StyleCompatibility_46_4.ngDoCheck(this,this._el_46,throwOnChange);
    const currVal_48_0_0:any = this.context.columnChartOptions;
    this._GoogleChartComponent_48_3.check_data(currVal_48_0_0,throwOnChange,false);
    if (this._GoogleChartComponent_48_3.ngDoCheck(this,this._el_48,throwOnChange)) { this.compView_48.markAsCheckOnce(); }
    this._MdCardActions_51_3.ngDoCheck(this,this._el_51,throwOnChange);
    this._StyleCompatibility_51_4.ngDoCheck(this,this._el_51,throwOnChange);
    if (this._MdCard_58_3.ngDoCheck(this,this._el_58,throwOnChange)) { this.compView_58.markAsCheckOnce(); }
    this._StyleCompatibility_58_4.ngDoCheck(this,this._el_58,throwOnChange);
    this._MdCardTitle_60_3.ngDoCheck(this,this._el_60,throwOnChange);
    this._StyleCompatibility_60_4.ngDoCheck(this,this._el_60,throwOnChange);
    this._MdCardContent_63_3.ngDoCheck(this,this._el_63,throwOnChange);
    this._StyleCompatibility_63_4.ngDoCheck(this,this._el_63,throwOnChange);
    const currVal_65_0_0:any = this.context.timelineChartOptions;
    this._GoogleChartComponent_65_3.check_data(currVal_65_0_0,throwOnChange,false);
    if (this._GoogleChartComponent_65_3.ngDoCheck(this,this._el_65,throwOnChange)) { this.compView_65.markAsCheckOnce(); }
    this._MdCardActions_68_3.ngDoCheck(this,this._el_68,throwOnChange);
    this._StyleCompatibility_68_4.ngDoCheck(this,this._el_68,throwOnChange);
    if (!throwOnChange) {
      if (this._query_Tab_15_0.dirty) {
        this._query_Tab_15_0.reset([
          this._Tab_17_3.context,
          this._Tab_20_3.context,
          this._Tab_23_3.context,
          this._Tab_26_3.context,
          this._Tab_29_3.context
        ]
        );
        this._Tabs_15_3.context.tabs = this._query_Tab_15_0;
        this._query_Tab_15_0.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Tabs_15_3.context.ngAfterContentInit(); }
    }
    this.compView_8.internalDetectChanges(throwOnChange);
    this.compView_15.internalDetectChanges(throwOnChange);
    this.compView_17.internalDetectChanges(throwOnChange);
    this.compView_20.internalDetectChanges(throwOnChange);
    this.compView_23.internalDetectChanges(throwOnChange);
    this.compView_26.internalDetectChanges(throwOnChange);
    this.compView_29.internalDetectChanges(throwOnChange);
    this.compView_41.internalDetectChanges(throwOnChange);
    this.compView_48.internalDetectChanges(throwOnChange);
    this.compView_58.internalDetectChanges(throwOnChange);
    this.compView_65.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_8.destroy();
    this.compView_15.destroy();
    this.compView_17.destroy();
    this.compView_20.destroy();
    this.compView_23.destroy();
    this.compView_26.destroy();
    this.compView_29.destroy();
    this.compView_41.destroy();
    this.compView_48.destroy();
    this.compView_58.destroy();
    this.compView_65.destroy();
    this._GoogleChartComponent_48_3.ngOnDestroy();
    this._GoogleChartComponent_65_3.ngOnDestroy();
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 8) && (ngContentIndex == 0))) {
      cb(this._text_9,ctx);
      cb(this._el_10,ctx);
      cb(this._text_12,ctx);
      cb(this._el_13,ctx);
      cb(this._text_33,ctx);
      cb(this._el_34,ctx);
      cb(this._text_36,ctx);
    }
    if (((nodeIndex == 15) && (ngContentIndex == 0))) {
      cb(this._text_16,ctx);
      cb(this._el_17,ctx);
      cb(this._text_19,ctx);
      cb(this._el_20,ctx);
      cb(this._text_22,ctx);
      cb(this._el_23,ctx);
      cb(this._text_25,ctx);
      cb(this._el_26,ctx);
      cb(this._text_28,ctx);
      cb(this._el_29,ctx);
      cb(this._text_31,ctx);
    }
    if (((nodeIndex == 41) && (ngContentIndex == 0))) {
      cb(this._text_42,ctx);
      cb(this._el_43,ctx);
      cb(this._text_45,ctx);
      cb(this._el_46,ctx);
      cb(this._text_50,ctx);
      cb(this._el_51,ctx);
      cb(this._text_53,ctx);
    }
    if (((nodeIndex == 58) && (ngContentIndex == 0))) {
      cb(this._text_59,ctx);
      cb(this._el_60,ctx);
      cb(this._text_62,ctx);
      cb(this._el_63,ctx);
      cb(this._text_67,ctx);
      cb(this._el_68,ctx);
      cb(this._text_70,ctx);
    }
  }
}