/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.centered[_ngcontent-%COMP%] {\r\n  position: fixed;\r\n  top: 50%;\r\n  left: 50%;\r\n  transform: translate(-80%, -50%);\r\n}\r\n\r\n.divtabs[_ngcontent-%COMP%], .barChartTabs[_ngcontent-%COMP%] {\r\n	\r\n	padding-left:8%;\r\n	width:80%;\r\n	height:80%;\r\n}\r\n\r\n.tab.active[_ngcontent-%COMP%] {\r\n	background:blue;\r\n}'];