/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['md-sidenav-layout.m2app-dark[_ngcontent-%COMP%] {\r\n  background: black;\r\n}\r\n\r\n.app-content[_ngcontent-%COMP%] {\r\n  padding: 20px;\r\n  background: white;\r\n  min-height:80vh;\r\n}\r\n\r\n.app-sidenav[_ngcontent-%COMP%] {\r\n  background: white;\r\n  height: 100vh;\r\n  min-height:100vh;\r\n}\r\n\r\n.app-sidenav-links[_ngcontent-%COMP%] {\r\n  background: white;\r\n}\r\n\r\n.app-sidenav-links[_ngcontent-%COMP%]:hover\r\n{\r\n   background:white;\r\n   background-color: white;\r\n}\r\n\r\n.app-toolbar-filler[_ngcontent-%COMP%] {\r\n  flex: 1 1 auto;\r\n}\r\n\r\n.app-toolbar-menu[_ngcontent-%COMP%] {\r\n  padding: 0 14px 0 14px;\r\n  color: white;\r\n}\r\n\r\n.app-icon-button[_ngcontent-%COMP%] {\r\n  box-shadow: none;\r\n  user-select: none;\r\n  background: none;\r\n  border: none;\r\n  cursor: pointer;\r\n  filter: none;\r\n  font-weight: normal;\r\n  height: auto;\r\n  line-height: inherit;\r\n  margin: 0;\r\n  min-width: 0;\r\n  padding: 0;\r\n  text-align: left;\r\n  text-decoration: none;\r\n}\r\n\r\n.app-action[_ngcontent-%COMP%] {\r\n  display: inline-block;\r\n  position: fixed;\r\n  bottom: 20px;\r\n  right: 20px;\r\n}'];