/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../../src/app/app-routing.module';
import * as import2 from '@angular/router/src/router_module';
import * as import3 from '@angular/common/src/location/location';
import * as import4 from '@angular/router/src/url_tree';
import * as import5 from '@angular/router/src/router_outlet_map';
import * as import6 from '@angular/core/src/linker/system_js_ng_module_factory_loader';
import * as import7 from '@angular/router/src/router_preloader';
import * as import8 from '@angular/core/src/di/injector';
import * as import9 from './default/default.component.ngfactory';
import * as import10 from './email/email/email.component.ngfactory';
import * as import11 from './email/contact/contact.component.ngfactory';
import * as import12 from './email/group/group.component.ngfactory';
import * as import13 from './email/server/emailserver.component.ngfactory';
import * as import14 from './security/user-role/user-role.component.ngfactory';
import * as import15 from './security/user-account/user-account.component.ngfactory';
import * as import16 from './security/user-group/user-group.component.ngfactory';
import * as import17 from './dashboard/dashboard.component.ngfactory';
import * as import18 from './security/login/login.component.ngfactory';
import * as import19 from './security/change-password/change-password.component.ngfactory';
import * as import20 from './analytics/analytics.root.component.ngfactory';
import * as import21 from '@angular/common/src/location/platform_location';
import * as import22 from '@angular/common/src/location/location_strategy';
import * as import23 from '@angular/core/src/linker/compiler';
import * as import24 from '../../../src/app/default/default.component';
import * as import25 from '../../../src/app/email/email/email.component';
import * as import26 from '../../../src/app/email/contact/contact.component';
import * as import27 from '../../../src/app/email/group/group.component';
import * as import28 from '../../../src/app/email/server/emailserver.component';
import * as import29 from '../../../src/app/security/user-role/user-role.component';
import * as import30 from '../../../src/app/security/user-account/user-account.component';
import * as import31 from '../../../src/app/security/user-group/user-group.component';
import * as import32 from '../../../src/app/dashboard/dashboard.component';
import * as import33 from '../../../src/app/security/login/login.component';
import * as import34 from '../../../src/app/security/change-password/change-password.component';
import * as import35 from '../../../src/app/analytics/analytics.root.component';
import * as import36 from '@angular/core/src/application_ref';
import * as import37 from '@angular/router/src/url_handling_strategy';
import * as import38 from '@angular/router/src/route_reuse_strategy';
import * as import39 from '@angular/router/src/router';
import * as import40 from '@angular/core/src/linker/ng_module_factory_loader';
import * as import41 from '@angular/router/src/router_config_loader';
import * as import42 from '@angular/router/src/router_state';
import * as import43 from '@angular/core/src/application_init';
import * as import44 from '@angular/core/src/application_tokens';
class EmailAppRoutingModuleInjector extends import0.NgModuleInjector<import1.EmailAppRoutingModule> {
  _ROUTER_FORROOT_GUARD_0:any;
  _RouterModule_1:import2.RouterModule;
  _EmailAppRoutingModule_2:import1.EmailAppRoutingModule;
  __ROUTER_CONFIGURATION_3:any;
  __LocationStrategy_4:any;
  __Location_5:import3.Location;
  __UrlSerializer_6:import4.DefaultUrlSerializer;
  __RouterOutletMap_7:import5.RouterOutletMap;
  __NgModuleFactoryLoader_8:import6.SystemJsNgModuleLoader;
  __ROUTES_9:any[];
  __Router_10:any;
  __ActivatedRoute_11:any;
  _NoPreloading_12:import7.NoPreloading;
  _PreloadingStrategy_13:any;
  _RouterPreloader_14:import7.RouterPreloader;
  __PreloadAllModules_15:import7.PreloadAllModules;
  __NgProbeToken_16:any[];
  __RouterInitializer_17:import2.RouterInitializer;
  __APP_INITIALIZER_18:any[];
  __ROUTER_INITIALIZER_19:any;
  __APP_BOOTSTRAP_LISTENER_20:any[];
  constructor(parent:import8.Injector) {
    super(parent,[
      import9.DefaultComponentNgFactory,
      import10.EmailComponentNgFactory,
      import11.ContactComponentNgFactory,
      import12.GroupComponentNgFactory,
      import13.EmailServerComponentNgFactory,
      import14.UserRoleComponentNgFactory,
      import15.UserAccountComponentNgFactory,
      import16.UserGroupComponentNgFactory,
      import17.DashboardComponentNgFactory,
      import18.LoginComponentNgFactory,
      import19.ChangePasswordComponentNgFactory,
      import20.AnalyticsComponentNgFactory
    ]
    ,([] as any[]));
  }
  get _ROUTER_CONFIGURATION_3():any {
    if ((this.__ROUTER_CONFIGURATION_3 == null)) { (this.__ROUTER_CONFIGURATION_3 = {}); }
    return this.__ROUTER_CONFIGURATION_3;
  }
  get _LocationStrategy_4():any {
    if ((this.__LocationStrategy_4 == null)) { (this.__LocationStrategy_4 = import2.provideLocationStrategy(this.parent.get(import21.PlatformLocation),this.parent.get(import22.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_3)); }
    return this.__LocationStrategy_4;
  }
  get _Location_5():import3.Location {
    if ((this.__Location_5 == null)) { (this.__Location_5 = new import3.Location(this._LocationStrategy_4)); }
    return this.__Location_5;
  }
  get _UrlSerializer_6():import4.DefaultUrlSerializer {
    if ((this.__UrlSerializer_6 == null)) { (this.__UrlSerializer_6 = new import4.DefaultUrlSerializer()); }
    return this.__UrlSerializer_6;
  }
  get _RouterOutletMap_7():import5.RouterOutletMap {
    if ((this.__RouterOutletMap_7 == null)) { (this.__RouterOutletMap_7 = new import5.RouterOutletMap()); }
    return this.__RouterOutletMap_7;
  }
  get _NgModuleFactoryLoader_8():import6.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_8 == null)) { (this.__NgModuleFactoryLoader_8 = new import6.SystemJsNgModuleLoader(this.parent.get(import23.Compiler),this.parent.get(import6.SystemJsNgModuleLoaderConfig,(null as any)))); }
    return this.__NgModuleFactoryLoader_8;
  }
  get _ROUTES_9():any[] {
      if ((this.__ROUTES_9 == null)) { (this.__ROUTES_9 = [[
        {
          path: '',
          component: import24.DefaultComponent
        }
        ,
        {
          path: 'send_email',
          component: import25.EmailComponent
        }
        ,
        {
          path: 'contacts',
          component: import26.ContactComponent
        }
        ,
        {
          path: 'groups',
          component: import27.GroupComponent
        }
        ,
        {
          path: 'servers',
          component: import28.EmailServerComponent
        }
        ,
        {
          path: 'user_roles',
          component: import29.UserRoleComponent
        }
        ,
        {
          path: 'user_accounts',
          component: import30.UserAccountComponent
        }
        ,
        {
          path: 'user_groups',
          component: import31.UserGroupComponent
        }
        ,
        {
          path: 'dashboard',
          component: import32.DashboardComponent
        }
        ,
        {
          path: 'appLogin',
          component: import33.LoginComponent
        }
        ,
        {
          path: 'changePassword',
          component: import34.ChangePasswordComponent
        }
        ,
        {
          path: 'analytics',
          component: import35.AnalyticsComponent
        }

      ]
    ]); }
    return this.__ROUTES_9;
  }
  get _Router_10():any {
    if ((this.__Router_10 == null)) { (this.__Router_10 = import2.setupRouter(this.parent.get(import36.ApplicationRef),this._UrlSerializer_6,this._RouterOutletMap_7,this._Location_5,this,this._NgModuleFactoryLoader_8,this.parent.get(import23.Compiler),this._ROUTES_9,this._ROUTER_CONFIGURATION_3,this.parent.get(import37.UrlHandlingStrategy,(null as any)),this.parent.get(import38.RouteReuseStrategy,(null as any)))); }
    return this.__Router_10;
  }
  get _ActivatedRoute_11():any {
    if ((this.__ActivatedRoute_11 == null)) { (this.__ActivatedRoute_11 = import2.rootRoute(this._Router_10)); }
    return this.__ActivatedRoute_11;
  }
  get _PreloadAllModules_15():import7.PreloadAllModules {
    if ((this.__PreloadAllModules_15 == null)) { (this.__PreloadAllModules_15 = new import7.PreloadAllModules()); }
    return this.__PreloadAllModules_15;
  }
  get _NgProbeToken_16():any[] {
    if ((this.__NgProbeToken_16 == null)) { (this.__NgProbeToken_16 = [import2.routerNgProbeToken()]); }
    return this.__NgProbeToken_16;
  }
  get _RouterInitializer_17():import2.RouterInitializer {
    if ((this.__RouterInitializer_17 == null)) { (this.__RouterInitializer_17 = new import2.RouterInitializer(this)); }
    return this.__RouterInitializer_17;
  }
  get _APP_INITIALIZER_18():any[] {
    if ((this.__APP_INITIALIZER_18 == null)) { (this.__APP_INITIALIZER_18 = [import2.getAppInitializer(this._RouterInitializer_17)]); }
    return this.__APP_INITIALIZER_18;
  }
  get _ROUTER_INITIALIZER_19():any {
    if ((this.__ROUTER_INITIALIZER_19 == null)) { (this.__ROUTER_INITIALIZER_19 = import2.getBootstrapListener(this._RouterInitializer_17)); }
    return this.__ROUTER_INITIALIZER_19;
  }
  get _APP_BOOTSTRAP_LISTENER_20():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_20 == null)) { (this.__APP_BOOTSTRAP_LISTENER_20 = [this._ROUTER_INITIALIZER_19]); }
    return this.__APP_BOOTSTRAP_LISTENER_20;
  }
  createInternal():import1.EmailAppRoutingModule {
    this._ROUTER_FORROOT_GUARD_0 = import2.provideForRootGuard(this.parent.get(import39.Router,(null as any)));
    this._RouterModule_1 = new import2.RouterModule(this._ROUTER_FORROOT_GUARD_0);
    this._EmailAppRoutingModule_2 = new import1.EmailAppRoutingModule();
    this._NoPreloading_12 = new import7.NoPreloading();
    this._PreloadingStrategy_13 = this._NoPreloading_12;
    this._RouterPreloader_14 = new import7.RouterPreloader(this._Router_10,this._NgModuleFactoryLoader_8,this.parent.get(import23.Compiler),this,this._PreloadingStrategy_13);
    return this._EmailAppRoutingModule_2;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.ROUTER_FORROOT_GUARD)) { return this._ROUTER_FORROOT_GUARD_0; }
    if ((token === import2.RouterModule)) { return this._RouterModule_1; }
    if ((token === import1.EmailAppRoutingModule)) { return this._EmailAppRoutingModule_2; }
    if ((token === import2.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_3; }
    if ((token === import22.LocationStrategy)) { return this._LocationStrategy_4; }
    if ((token === import3.Location)) { return this._Location_5; }
    if ((token === import4.UrlSerializer)) { return this._UrlSerializer_6; }
    if ((token === import5.RouterOutletMap)) { return this._RouterOutletMap_7; }
    if ((token === import40.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_8; }
    if ((token === import41.ROUTES)) { return this._ROUTES_9; }
    if ((token === import39.Router)) { return this._Router_10; }
    if ((token === import42.ActivatedRoute)) { return this._ActivatedRoute_11; }
    if ((token === import7.NoPreloading)) { return this._NoPreloading_12; }
    if ((token === import7.PreloadingStrategy)) { return this._PreloadingStrategy_13; }
    if ((token === import7.RouterPreloader)) { return this._RouterPreloader_14; }
    if ((token === import7.PreloadAllModules)) { return this._PreloadAllModules_15; }
    if ((token === import36.NgProbeToken)) { return this._NgProbeToken_16; }
    if ((token === import2.RouterInitializer)) { return this._RouterInitializer_17; }
    if ((token === import43.APP_INITIALIZER)) { return this._APP_INITIALIZER_18; }
    if ((token === import2.ROUTER_INITIALIZER)) { return this._ROUTER_INITIALIZER_19; }
    if ((token === import44.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_20; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._RouterPreloader_14.ngOnDestroy();
  }
}
export const EmailAppRoutingModuleNgFactory:import0.NgModuleFactory<import1.EmailAppRoutingModule> = new import0.NgModuleFactory(EmailAppRoutingModuleInjector,import1.EmailAppRoutingModule);