/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../../src/app/app.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/forms/src/directives';
import * as import6 from '@angular/forms/src/form_providers';
import * as import7 from '@angular/http/src/http_module';
import * as import8 from '@angular/material/core/ripple/ripple';
import * as import9 from '@angular/material/button/button';
import * as import10 from '@angular/material/card/card';
import * as import11 from '@angular/material/checkbox/checkbox';
import * as import12 from '@angular/material/core/line/line';
import * as import13 from '@angular/material/grid-list/grid-list';
import * as import14 from '@angular/material/input/input';
import * as import15 from '@angular/material/list/list';
import * as import16 from '@angular/material/progress-bar/progress-bar';
import * as import17 from '@angular/material/progress-circle/progress-circle';
import * as import18 from '@angular/material/sidenav/sidenav';
import * as import19 from '@angular/material/core/portal/portal-directives';
import * as import20 from '@angular/material/tabs/tabs';
import * as import21 from '@angular/material/toolbar/toolbar';
import * as import22 from '@angular/material/core/rtl/dir';
import * as import23 from '@angular/material/core/a11y/index';
import * as import24 from '@angular/material/button-toggle/button-toggle';
import * as import25 from '@angular/material/core/overlay/overlay-directives';
import * as import26 from '@angular/material/dialog/dialog';
import * as import27 from '@angular/material/icon/icon';
import * as import28 from '@angular/material/menu/menu';
import * as import29 from '@angular/material/radio/radio';
import * as import30 from '@angular/material/slider/slider';
import * as import31 from '@angular/material/slide-toggle/slide-toggle';
import * as import32 from '@angular/material/snack-bar/snack-bar';
import * as import33 from '@angular/material/tooltip/tooltip';
import * as import34 from '@angular/material/core/compatibility/style-compatibility';
import * as import35 from '@angular/material/module';
import * as import36 from '@angular/router/src/router_module';
import * as import37 from '../../../src/app/app-routing.module';
import * as import38 from 'primeng/components/common/shared';
import * as import39 from 'primeng/components/paginator/paginator';
import * as import40 from 'primeng/components/inputtext/inputtext';
import * as import41 from 'primeng/components/datatable/datatable';
import * as import42 from 'primeng/components/button/button';
import * as import43 from 'primeng/components/picklist/picklist';
import * as import44 from 'primeng/components/dialog/dialog';
import * as import45 from 'primeng/components/panel/panel';
import * as import46 from 'primeng/components/growl/growl';
import * as import47 from 'primeng/components/multiselect/multiselect';
import * as import48 from 'primeng/components/listbox/listbox';
import * as import49 from 'primeng/components/tabview/tabview';
import * as import50 from 'primeng/components/dropdown/dropdown';
import * as import51 from '../../../src/app/security/security.module';
import * as import52 from '../../../src/app/email/email.module';
import * as import53 from 'ng2-google-charts/google-charts.module';
import * as import54 from '@angular/common/src/localization';
import * as import55 from '@angular/core/src/application_init';
import * as import56 from '@angular/core/src/testability/testability';
import * as import57 from '@angular/core/src/application_ref';
import * as import58 from '@angular/core/src/linker/compiler';
import * as import59 from '@angular/material/core/gestures/MdGestureConfig';
import * as import60 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import61 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import62 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import63 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import64 from '@angular/core/src/animation/animation_queue';
import * as import65 from '@angular/core/src/linker/view_utils';
import * as import66 from '@angular/platform-browser/src/browser/title';
import * as import67 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import68 from '@angular/http/src/backends/browser_xhr';
import * as import69 from '@angular/http/src/base_response_options';
import * as import70 from '@angular/http/src/backends/xhr_backend';
import * as import71 from '@angular/http/src/base_request_options';
import * as import72 from '@angular/http/src/backends/browser_jsonp';
import * as import73 from '@angular/http/src/backends/jsonp_backend';
import * as import74 from '@angular/material/core/a11y/live-announcer';
import * as import75 from '@angular/material/core/a11y/interactivity-checker';
import * as import76 from '@angular/material/core/coordination/unique-selection-dispatcher';
import * as import77 from '@angular/material/core/overlay/overlay-container';
import * as import78 from '@angular/material/core/overlay/position/viewport-ruler';
import * as import79 from '@angular/material/core/overlay/position/overlay-position-builder';
import * as import80 from '@angular/material/core/overlay/overlay';
import * as import81 from '@angular/material/icon/icon-registry';
import * as import82 from '@angular/common/src/location/location';
import * as import83 from '@angular/router/src/url_tree';
import * as import84 from '@angular/router/src/router_outlet_map';
import * as import85 from '@angular/core/src/linker/system_js_ng_module_factory_loader';
import * as import86 from '@angular/router/src/router_preloader';
import * as import87 from '../../../src/app/security/user-role/user-role.service';
import * as import88 from '../../../src/app/security/login/login.service';
import * as import89 from '../../../src/app/security/user-group/user-group.service';
import * as import90 from '../../../src/app/security/user-account/user-account.service';
import * as import91 from '../../../src/app/email/contact/contact.service';
import * as import92 from '../../../src/app/email/group/group.service';
import * as import93 from '../../../src/app/email/shared/common.service';
import * as import94 from '../../../src/app/email/contactgroup/contactgroup.service';
import * as import95 from '../../../src/app/email/server/emailserver.service';
import * as import96 from '../../../src/app/email/email/email.service';
import * as import97 from '../../../src/app/email/server/emailserverproperties.service';
import * as import98 from 'ng2-google-charts/google-charts-loader.service';
import * as import99 from '../../../src/app/core/global.service';
import * as import100 from '../../../src/app/core/authorization.service';
import * as import101 from '@angular/core/src/di/injector';
import * as import102 from '../../node_modules/@angular/material/dialog/dialog-container.ngfactory';
import * as import103 from '../../node_modules/@angular/material/snack-bar/snack-bar-container.ngfactory';
import * as import104 from '../../node_modules/@angular/material/snack-bar/simple-snack-bar.ngfactory';
import * as import105 from '../../node_modules/@angular/material/tooltip/tooltip.ngfactory';
import * as import106 from './default/default.component.ngfactory';
import * as import107 from './email/email/email.component.ngfactory';
import * as import108 from './email/contact/contact.component.ngfactory';
import * as import109 from './email/group/group.component.ngfactory';
import * as import110 from './email/server/emailserver.component.ngfactory';
import * as import111 from './security/user-role/user-role.component.ngfactory';
import * as import112 from './security/user-account/user-account.component.ngfactory';
import * as import113 from './security/user-group/user-group.component.ngfactory';
import * as import114 from './dashboard/dashboard.component.ngfactory';
import * as import115 from './security/login/login.component.ngfactory';
import * as import116 from './security/change-password/change-password.component.ngfactory';
import * as import117 from './analytics/analytics.root.component.ngfactory';
import * as import118 from './app.component.ngfactory';
import * as import119 from '@angular/core/src/i18n/tokens';
import * as import120 from '@angular/core/src/application_tokens';
import * as import121 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import122 from '@angular/platform-browser/src/dom/events/key_events';
import * as import123 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import124 from '@angular/core/src/zone/ng_zone';
import * as import125 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import126 from '@angular/common/src/location/platform_location';
import * as import127 from '@angular/common/src/location/location_strategy';
import * as import128 from '../../../src/app/default/default.component';
import * as import129 from '../../../src/app/email/email/email.component';
import * as import130 from '../../../src/app/email/contact/contact.component';
import * as import131 from '../../../src/app/email/group/group.component';
import * as import132 from '../../../src/app/email/server/emailserver.component';
import * as import133 from '../../../src/app/security/user-role/user-role.component';
import * as import134 from '../../../src/app/security/user-account/user-account.component';
import * as import135 from '../../../src/app/security/user-group/user-group.component';
import * as import136 from '../../../src/app/dashboard/dashboard.component';
import * as import137 from '../../../src/app/security/login/login.component';
import * as import138 from '../../../src/app/security/change-password/change-password.component';
import * as import139 from '../../../src/app/analytics/analytics.root.component';
import * as import140 from '@angular/router/src/url_handling_strategy';
import * as import141 from '@angular/router/src/route_reuse_strategy';
import * as import142 from '@angular/router/src/router';
import * as import143 from '@angular/core/src/console';
import * as import144 from '@angular/core/src/error_handler';
import * as import145 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import146 from '@angular/platform-browser/src/dom/animation_driver';
import * as import147 from '@angular/core/src/render/api';
import * as import148 from '@angular/core/src/security';
import * as import149 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import150 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import151 from '@angular/http/src/interfaces';
import * as import152 from '@angular/http/src/http';
import * as import153 from '@angular/core/src/linker/ng_module_factory_loader';
import * as import154 from '@angular/router/src/router_config_loader';
import * as import155 from '@angular/router/src/router_state';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _InternalFormsSharedModule_3:import5.InternalFormsSharedModule;
  _FormsModule_4:import6.FormsModule;
  _HttpModule_5:import7.HttpModule;
  _JsonpModule_6:import7.JsonpModule;
  _MdRippleModule_7:import8.MdRippleModule;
  _MdButtonModule_8:import9.MdButtonModule;
  _MdCardModule_9:import10.MdCardModule;
  _MdCheckboxModule_10:import11.MdCheckboxModule;
  _MdLineModule_11:import12.MdLineModule;
  _MdGridListModule_12:import13.MdGridListModule;
  _MdInputModule_13:import14.MdInputModule;
  _MdListModule_14:import15.MdListModule;
  _MdProgressBarModule_15:import16.MdProgressBarModule;
  _MdProgressCircleModule_16:import17.MdProgressCircleModule;
  _MdSidenavModule_17:import18.MdSidenavModule;
  _PortalModule_18:import19.PortalModule;
  _MdTabsModule_19:import20.MdTabsModule;
  _MdToolbarModule_20:import21.MdToolbarModule;
  _RtlModule_21:import22.RtlModule;
  _A11yModule_22:import23.A11yModule;
  _MdButtonToggleModule_23:import24.MdButtonToggleModule;
  _OverlayModule_24:import25.OverlayModule;
  _MdDialogModule_25:import26.MdDialogModule;
  _MdIconModule_26:import27.MdIconModule;
  _MdMenuModule_27:import28.MdMenuModule;
  _MdRadioModule_28:import29.MdRadioModule;
  _MdSliderModule_29:import30.MdSliderModule;
  _MdSlideToggleModule_30:import31.MdSlideToggleModule;
  _MdSnackBarModule_31:import32.MdSnackBarModule;
  _MdTooltipModule_32:import33.MdTooltipModule;
  _StyleCompatibilityModule_33:import34.StyleCompatibilityModule;
  _MaterialRootModule_34:import35.MaterialRootModule;
  _ROUTER_FORROOT_GUARD_35:any;
  _RouterModule_36:import36.RouterModule;
  _EmailAppRoutingModule_37:import37.EmailAppRoutingModule;
  _SharedModule_38:import38.SharedModule;
  _PaginatorModule_39:import39.PaginatorModule;
  _InputTextModule_40:import40.InputTextModule;
  _DataTableModule_41:import41.DataTableModule;
  _ButtonModule_42:import42.ButtonModule;
  _PickListModule_43:import43.PickListModule;
  _DialogModule_44:import44.DialogModule;
  _PanelModule_45:import45.PanelModule;
  _GrowlModule_46:import46.GrowlModule;
  _MultiSelectModule_47:import47.MultiSelectModule;
  _ListboxModule_48:import48.ListboxModule;
  _TabViewModule_49:import49.TabViewModule;
  _DropdownModule_50:import50.DropdownModule;
  _SecurityModule_51:import51.SecurityModule;
  _EmailModule_52:import52.EmailModule;
  _Ng2GoogleChartsModule_53:import53.Ng2GoogleChartsModule;
  _AppModule_54:import1.AppModule;
  __LOCALE_ID_55:any;
  __NgLocalization_56:import54.NgLocaleLocalization;
  _ErrorHandler_57:any;
  _RouterInitializer_58:import36.RouterInitializer;
  _APP_INITIALIZER_59:any[];
  _ApplicationInitStatus_60:import55.ApplicationInitStatus;
  _Testability_61:import56.Testability;
  _ApplicationRef__62:import57.ApplicationRef_;
  __ApplicationRef_63:any;
  __Compiler_64:import58.Compiler;
  __APP_ID_65:any;
  __DOCUMENT_66:any;
  __HAMMER_GESTURE_CONFIG_67:import59.MdGestureConfig;
  __EVENT_MANAGER_PLUGINS_68:any[];
  __EventManager_69:import60.EventManager;
  _DomSharedStylesHost_70:import61.DomSharedStylesHost;
  __AnimationDriver_71:any;
  __DomRootRenderer_72:import62.DomRootRenderer_;
  __NgProbeToken_73:any[];
  __RootRenderer_74:any;
  __DomSanitizer_75:import63.DomSanitizerImpl;
  __Sanitizer_76:any;
  __AnimationQueue_77:import64.AnimationQueue;
  __ViewUtils_78:import65.ViewUtils;
  __IterableDiffers_79:any;
  __KeyValueDiffers_80:any;
  __SharedStylesHost_81:any;
  __Title_82:import66.Title;
  __RadioControlRegistry_83:import67.RadioControlRegistry;
  __BrowserXhr_84:import68.BrowserXhr;
  __ResponseOptions_85:import69.BaseResponseOptions;
  __XSRFStrategy_86:any;
  __XHRBackend_87:import70.XHRBackend;
  __RequestOptions_88:import71.BaseRequestOptions;
  __Http_89:any;
  __BrowserJsonp_90:import72.BrowserJsonp;
  __JSONPBackend_91:import73.JSONPBackend_;
  __Jsonp_92:any;
  __MdLiveAnnouncer_93:import74.MdLiveAnnouncer;
  __InteractivityChecker_94:import75.InteractivityChecker;
  __MdUniqueSelectionDispatcher_95:import76.MdUniqueSelectionDispatcher;
  __OverlayContainer_96:import77.OverlayContainer;
  __ViewportRuler_97:import78.ViewportRuler;
  __OverlayPositionBuilder_98:import79.OverlayPositionBuilder;
  __Overlay_99:import80.Overlay;
  __MdDialog_100:import26.MdDialog;
  __MdIconRegistry_101:import81.MdIconRegistry;
  __MdSnackBar_102:import32.MdSnackBar;
  __ROUTER_CONFIGURATION_103:any;
  __LocationStrategy_104:any;
  __Location_105:import82.Location;
  __UrlSerializer_106:import83.DefaultUrlSerializer;
  __RouterOutletMap_107:import84.RouterOutletMap;
  __NgModuleFactoryLoader_108:import85.SystemJsNgModuleLoader;
  __ROUTES_109:any[];
  __Router_110:any;
  __ActivatedRoute_111:any;
  _NoPreloading_112:import86.NoPreloading;
  _PreloadingStrategy_113:any;
  _RouterPreloader_114:import86.RouterPreloader;
  __PreloadAllModules_115:import86.PreloadAllModules;
  __ROUTER_INITIALIZER_116:any;
  __APP_BOOTSTRAP_LISTENER_117:any[];
  __UserRoleService_118:import87.UserRoleService;
  __LoginService_119:import88.LoginService;
  __UserGroupService_120:import89.UserGroupService;
  __UserAccountService_121:import90.UserAccountService;
  __ContactService_122:import91.ContactService;
  __GroupService_123:import92.GroupService;
  __CommonService_124:import93.CommonService;
  __ContactGroupService_125:import94.ContactGroupService;
  __EmailServerService_126:import95.EmailServerService;
  __EmailService_127:import96.EmailService;
  __EmailServerPropertiesService_128:import97.EmailServerPropertiesService;
  __GoogleChartsLoaderService_129:import98.GoogleChartsLoaderService;
  __GlobalService_130:import99.GlobalService;
  __AuthorizationService_131:import100.AuthorizationService;
  constructor(parent:import101.Injector) {
    super(parent,[
      import102.MdDialogContainerNgFactory,
      import103.MdSnackBarContainerNgFactory,
      import104.SimpleSnackBarNgFactory,
      import105.TooltipComponentNgFactory,
      import106.DefaultComponentNgFactory,
      import107.EmailComponentNgFactory,
      import108.ContactComponentNgFactory,
      import109.GroupComponentNgFactory,
      import110.EmailServerComponentNgFactory,
      import111.UserRoleComponentNgFactory,
      import112.UserAccountComponentNgFactory,
      import113.UserGroupComponentNgFactory,
      import114.DashboardComponentNgFactory,
      import115.LoginComponentNgFactory,
      import116.ChangePasswordComponentNgFactory,
      import117.AnalyticsComponentNgFactory,
      import118.AppComponentNgFactory
    ]
    ,[import118.AppComponentNgFactory]);
  }
  get _LOCALE_ID_55():any {
    if ((this.__LOCALE_ID_55 == null)) { (this.__LOCALE_ID_55 = import3._localeFactory(this.parent.get(import119.LOCALE_ID,(null as any)))); }
    return this.__LOCALE_ID_55;
  }
  get _NgLocalization_56():import54.NgLocaleLocalization {
    if ((this.__NgLocalization_56 == null)) { (this.__NgLocalization_56 = new import54.NgLocaleLocalization(this._LOCALE_ID_55)); }
    return this.__NgLocalization_56;
  }
  get _ApplicationRef_63():any {
    if ((this.__ApplicationRef_63 == null)) { (this.__ApplicationRef_63 = this._ApplicationRef__62); }
    return this.__ApplicationRef_63;
  }
  get _Compiler_64():import58.Compiler {
    if ((this.__Compiler_64 == null)) { (this.__Compiler_64 = new import58.Compiler()); }
    return this.__Compiler_64;
  }
  get _APP_ID_65():any {
    if ((this.__APP_ID_65 == null)) { (this.__APP_ID_65 = import120._appIdRandomProviderFactory()); }
    return this.__APP_ID_65;
  }
  get _DOCUMENT_66():any {
    if ((this.__DOCUMENT_66 == null)) { (this.__DOCUMENT_66 = import4._document()); }
    return this.__DOCUMENT_66;
  }
  get _HAMMER_GESTURE_CONFIG_67():import59.MdGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_67 == null)) { (this.__HAMMER_GESTURE_CONFIG_67 = new import59.MdGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_67;
  }
  get _EVENT_MANAGER_PLUGINS_68():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_68 == null)) { (this.__EVENT_MANAGER_PLUGINS_68 = [
      new import121.DomEventsPlugin(),
      new import122.KeyEventsPlugin(),
      new import123.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_67)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_68;
  }
  get _EventManager_69():import60.EventManager {
    if ((this.__EventManager_69 == null)) { (this.__EventManager_69 = new import60.EventManager(this._EVENT_MANAGER_PLUGINS_68,this.parent.get(import124.NgZone))); }
    return this.__EventManager_69;
  }
  get _AnimationDriver_71():any {
    if ((this.__AnimationDriver_71 == null)) { (this.__AnimationDriver_71 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_71;
  }
  get _DomRootRenderer_72():import62.DomRootRenderer_ {
    if ((this.__DomRootRenderer_72 == null)) { (this.__DomRootRenderer_72 = new import62.DomRootRenderer_(this._DOCUMENT_66,this._EventManager_69,this._DomSharedStylesHost_70,this._AnimationDriver_71,this._APP_ID_65)); }
    return this.__DomRootRenderer_72;
  }
  get _NgProbeToken_73():any[] {
    if ((this.__NgProbeToken_73 == null)) { (this.__NgProbeToken_73 = [import36.routerNgProbeToken()]); }
    return this.__NgProbeToken_73;
  }
  get _RootRenderer_74():any {
    if ((this.__RootRenderer_74 == null)) { (this.__RootRenderer_74 = import125._createConditionalRootRenderer(this._DomRootRenderer_72,this.parent.get(import125.NgProbeToken,(null as any)),this._NgProbeToken_73)); }
    return this.__RootRenderer_74;
  }
  get _DomSanitizer_75():import63.DomSanitizerImpl {
    if ((this.__DomSanitizer_75 == null)) { (this.__DomSanitizer_75 = new import63.DomSanitizerImpl()); }
    return this.__DomSanitizer_75;
  }
  get _Sanitizer_76():any {
    if ((this.__Sanitizer_76 == null)) { (this.__Sanitizer_76 = this._DomSanitizer_75); }
    return this.__Sanitizer_76;
  }
  get _AnimationQueue_77():import64.AnimationQueue {
    if ((this.__AnimationQueue_77 == null)) { (this.__AnimationQueue_77 = new import64.AnimationQueue(this.parent.get(import124.NgZone))); }
    return this.__AnimationQueue_77;
  }
  get _ViewUtils_78():import65.ViewUtils {
    if ((this.__ViewUtils_78 == null)) { (this.__ViewUtils_78 = new import65.ViewUtils(this._RootRenderer_74,this._Sanitizer_76,this._AnimationQueue_77)); }
    return this.__ViewUtils_78;
  }
  get _IterableDiffers_79():any {
    if ((this.__IterableDiffers_79 == null)) { (this.__IterableDiffers_79 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_79;
  }
  get _KeyValueDiffers_80():any {
    if ((this.__KeyValueDiffers_80 == null)) { (this.__KeyValueDiffers_80 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_80;
  }
  get _SharedStylesHost_81():any {
    if ((this.__SharedStylesHost_81 == null)) { (this.__SharedStylesHost_81 = this._DomSharedStylesHost_70); }
    return this.__SharedStylesHost_81;
  }
  get _Title_82():import66.Title {
    if ((this.__Title_82 == null)) { (this.__Title_82 = new import66.Title()); }
    return this.__Title_82;
  }
  get _RadioControlRegistry_83():import67.RadioControlRegistry {
    if ((this.__RadioControlRegistry_83 == null)) { (this.__RadioControlRegistry_83 = new import67.RadioControlRegistry()); }
    return this.__RadioControlRegistry_83;
  }
  get _BrowserXhr_84():import68.BrowserXhr {
    if ((this.__BrowserXhr_84 == null)) { (this.__BrowserXhr_84 = new import68.BrowserXhr()); }
    return this.__BrowserXhr_84;
  }
  get _ResponseOptions_85():import69.BaseResponseOptions {
    if ((this.__ResponseOptions_85 == null)) { (this.__ResponseOptions_85 = new import69.BaseResponseOptions()); }
    return this.__ResponseOptions_85;
  }
  get _XSRFStrategy_86():any {
    if ((this.__XSRFStrategy_86 == null)) { (this.__XSRFStrategy_86 = import7._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_86;
  }
  get _XHRBackend_87():import70.XHRBackend {
    if ((this.__XHRBackend_87 == null)) { (this.__XHRBackend_87 = new import70.XHRBackend(this._BrowserXhr_84,this._ResponseOptions_85,this._XSRFStrategy_86)); }
    return this.__XHRBackend_87;
  }
  get _RequestOptions_88():import71.BaseRequestOptions {
    if ((this.__RequestOptions_88 == null)) { (this.__RequestOptions_88 = new import71.BaseRequestOptions()); }
    return this.__RequestOptions_88;
  }
  get _Http_89():any {
    if ((this.__Http_89 == null)) { (this.__Http_89 = import7.httpFactory(this._XHRBackend_87,this._RequestOptions_88)); }
    return this.__Http_89;
  }
  get _BrowserJsonp_90():import72.BrowserJsonp {
    if ((this.__BrowserJsonp_90 == null)) { (this.__BrowserJsonp_90 = new import72.BrowserJsonp()); }
    return this.__BrowserJsonp_90;
  }
  get _JSONPBackend_91():import73.JSONPBackend_ {
    if ((this.__JSONPBackend_91 == null)) { (this.__JSONPBackend_91 = new import73.JSONPBackend_(this._BrowserJsonp_90,this._ResponseOptions_85)); }
    return this.__JSONPBackend_91;
  }
  get _Jsonp_92():any {
    if ((this.__Jsonp_92 == null)) { (this.__Jsonp_92 = import7.jsonpFactory(this._JSONPBackend_91,this._RequestOptions_88)); }
    return this.__Jsonp_92;
  }
  get _MdLiveAnnouncer_93():import74.MdLiveAnnouncer {
    if ((this.__MdLiveAnnouncer_93 == null)) { (this.__MdLiveAnnouncer_93 = new import74.MdLiveAnnouncer(this.parent.get(import74.LIVE_ANNOUNCER_ELEMENT_TOKEN,(null as any)))); }
    return this.__MdLiveAnnouncer_93;
  }
  get _InteractivityChecker_94():import75.InteractivityChecker {
    if ((this.__InteractivityChecker_94 == null)) { (this.__InteractivityChecker_94 = new import75.InteractivityChecker()); }
    return this.__InteractivityChecker_94;
  }
  get _MdUniqueSelectionDispatcher_95():import76.MdUniqueSelectionDispatcher {
    if ((this.__MdUniqueSelectionDispatcher_95 == null)) { (this.__MdUniqueSelectionDispatcher_95 = new import76.MdUniqueSelectionDispatcher()); }
    return this.__MdUniqueSelectionDispatcher_95;
  }
  get _OverlayContainer_96():import77.OverlayContainer {
    if ((this.__OverlayContainer_96 == null)) { (this.__OverlayContainer_96 = new import77.OverlayContainer()); }
    return this.__OverlayContainer_96;
  }
  get _ViewportRuler_97():import78.ViewportRuler {
    if ((this.__ViewportRuler_97 == null)) { (this.__ViewportRuler_97 = new import78.ViewportRuler()); }
    return this.__ViewportRuler_97;
  }
  get _OverlayPositionBuilder_98():import79.OverlayPositionBuilder {
    if ((this.__OverlayPositionBuilder_98 == null)) { (this.__OverlayPositionBuilder_98 = new import79.OverlayPositionBuilder(this._ViewportRuler_97)); }
    return this.__OverlayPositionBuilder_98;
  }
  get _Overlay_99():import80.Overlay {
    if ((this.__Overlay_99 == null)) { (this.__Overlay_99 = new import80.Overlay(this._OverlayContainer_96,this,this._OverlayPositionBuilder_98,this._ApplicationRef_63,this)); }
    return this.__Overlay_99;
  }
  get _MdDialog_100():import26.MdDialog {
    if ((this.__MdDialog_100 == null)) { (this.__MdDialog_100 = new import26.MdDialog(this._Overlay_99,this)); }
    return this.__MdDialog_100;
  }
  get _MdIconRegistry_101():import81.MdIconRegistry {
    if ((this.__MdIconRegistry_101 == null)) { (this.__MdIconRegistry_101 = new import81.MdIconRegistry(this._Http_89)); }
    return this.__MdIconRegistry_101;
  }
  get _MdSnackBar_102():import32.MdSnackBar {
    if ((this.__MdSnackBar_102 == null)) { (this.__MdSnackBar_102 = new import32.MdSnackBar(this._Overlay_99,this._MdLiveAnnouncer_93)); }
    return this.__MdSnackBar_102;
  }
  get _ROUTER_CONFIGURATION_103():any {
    if ((this.__ROUTER_CONFIGURATION_103 == null)) { (this.__ROUTER_CONFIGURATION_103 = {}); }
    return this.__ROUTER_CONFIGURATION_103;
  }
  get _LocationStrategy_104():any {
    if ((this.__LocationStrategy_104 == null)) { (this.__LocationStrategy_104 = import36.provideLocationStrategy(this.parent.get(import126.PlatformLocation),this.parent.get(import127.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_103)); }
    return this.__LocationStrategy_104;
  }
  get _Location_105():import82.Location {
    if ((this.__Location_105 == null)) { (this.__Location_105 = new import82.Location(this._LocationStrategy_104)); }
    return this.__Location_105;
  }
  get _UrlSerializer_106():import83.DefaultUrlSerializer {
    if ((this.__UrlSerializer_106 == null)) { (this.__UrlSerializer_106 = new import83.DefaultUrlSerializer()); }
    return this.__UrlSerializer_106;
  }
  get _RouterOutletMap_107():import84.RouterOutletMap {
    if ((this.__RouterOutletMap_107 == null)) { (this.__RouterOutletMap_107 = new import84.RouterOutletMap()); }
    return this.__RouterOutletMap_107;
  }
  get _NgModuleFactoryLoader_108():import85.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_108 == null)) { (this.__NgModuleFactoryLoader_108 = new import85.SystemJsNgModuleLoader(this._Compiler_64,this.parent.get(import85.SystemJsNgModuleLoaderConfig,(null as any)))); }
    return this.__NgModuleFactoryLoader_108;
  }
  get _ROUTES_109():any[] {
      if ((this.__ROUTES_109 == null)) { (this.__ROUTES_109 = [[
        {
          path: '',
          component: import128.DefaultComponent
        }
        ,
        {
          path: 'send_email',
          component: import129.EmailComponent
        }
        ,
        {
          path: 'contacts',
          component: import130.ContactComponent
        }
        ,
        {
          path: 'groups',
          component: import131.GroupComponent
        }
        ,
        {
          path: 'servers',
          component: import132.EmailServerComponent
        }
        ,
        {
          path: 'user_roles',
          component: import133.UserRoleComponent
        }
        ,
        {
          path: 'user_accounts',
          component: import134.UserAccountComponent
        }
        ,
        {
          path: 'user_groups',
          component: import135.UserGroupComponent
        }
        ,
        {
          path: 'dashboard',
          component: import136.DashboardComponent
        }
        ,
        {
          path: 'appLogin',
          component: import137.LoginComponent
        }
        ,
        {
          path: 'changePassword',
          component: import138.ChangePasswordComponent
        }
        ,
        {
          path: 'analytics',
          component: import139.AnalyticsComponent
        }

      ]
    ]); }
    return this.__ROUTES_109;
  }
  get _Router_110():any {
    if ((this.__Router_110 == null)) { (this.__Router_110 = import36.setupRouter(this._ApplicationRef_63,this._UrlSerializer_106,this._RouterOutletMap_107,this._Location_105,this,this._NgModuleFactoryLoader_108,this._Compiler_64,this._ROUTES_109,this._ROUTER_CONFIGURATION_103,this.parent.get(import140.UrlHandlingStrategy,(null as any)),this.parent.get(import141.RouteReuseStrategy,(null as any)))); }
    return this.__Router_110;
  }
  get _ActivatedRoute_111():any {
    if ((this.__ActivatedRoute_111 == null)) { (this.__ActivatedRoute_111 = import36.rootRoute(this._Router_110)); }
    return this.__ActivatedRoute_111;
  }
  get _PreloadAllModules_115():import86.PreloadAllModules {
    if ((this.__PreloadAllModules_115 == null)) { (this.__PreloadAllModules_115 = new import86.PreloadAllModules()); }
    return this.__PreloadAllModules_115;
  }
  get _ROUTER_INITIALIZER_116():any {
    if ((this.__ROUTER_INITIALIZER_116 == null)) { (this.__ROUTER_INITIALIZER_116 = import36.getBootstrapListener(this._RouterInitializer_58)); }
    return this.__ROUTER_INITIALIZER_116;
  }
  get _APP_BOOTSTRAP_LISTENER_117():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_117 == null)) { (this.__APP_BOOTSTRAP_LISTENER_117 = [this._ROUTER_INITIALIZER_116]); }
    return this.__APP_BOOTSTRAP_LISTENER_117;
  }
  get _UserRoleService_118():import87.UserRoleService {
    if ((this.__UserRoleService_118 == null)) { (this.__UserRoleService_118 = new import87.UserRoleService(this._Http_89)); }
    return this.__UserRoleService_118;
  }
  get _LoginService_119():import88.LoginService {
    if ((this.__LoginService_119 == null)) { (this.__LoginService_119 = new import88.LoginService(this._Http_89)); }
    return this.__LoginService_119;
  }
  get _UserGroupService_120():import89.UserGroupService {
    if ((this.__UserGroupService_120 == null)) { (this.__UserGroupService_120 = new import89.UserGroupService(this._Http_89)); }
    return this.__UserGroupService_120;
  }
  get _UserAccountService_121():import90.UserAccountService {
    if ((this.__UserAccountService_121 == null)) { (this.__UserAccountService_121 = new import90.UserAccountService(this._Http_89)); }
    return this.__UserAccountService_121;
  }
  get _ContactService_122():import91.ContactService {
    if ((this.__ContactService_122 == null)) { (this.__ContactService_122 = new import91.ContactService(this._Http_89)); }
    return this.__ContactService_122;
  }
  get _GroupService_123():import92.GroupService {
    if ((this.__GroupService_123 == null)) { (this.__GroupService_123 = new import92.GroupService(this._Http_89)); }
    return this.__GroupService_123;
  }
  get _CommonService_124():import93.CommonService {
    if ((this.__CommonService_124 == null)) { (this.__CommonService_124 = new import93.CommonService(this._ContactService_122,this._GroupService_123)); }
    return this.__CommonService_124;
  }
  get _ContactGroupService_125():import94.ContactGroupService {
    if ((this.__ContactGroupService_125 == null)) { (this.__ContactGroupService_125 = new import94.ContactGroupService(this._Http_89)); }
    return this.__ContactGroupService_125;
  }
  get _EmailServerService_126():import95.EmailServerService {
    if ((this.__EmailServerService_126 == null)) { (this.__EmailServerService_126 = new import95.EmailServerService(this._Http_89)); }
    return this.__EmailServerService_126;
  }
  get _EmailService_127():import96.EmailService {
    if ((this.__EmailService_127 == null)) { (this.__EmailService_127 = new import96.EmailService(this._Http_89)); }
    return this.__EmailService_127;
  }
  get _EmailServerPropertiesService_128():import97.EmailServerPropertiesService {
    if ((this.__EmailServerPropertiesService_128 == null)) { (this.__EmailServerPropertiesService_128 = new import97.EmailServerPropertiesService(this._Http_89)); }
    return this.__EmailServerPropertiesService_128;
  }
  get _GoogleChartsLoaderService_129():import98.GoogleChartsLoaderService {
    if ((this.__GoogleChartsLoaderService_129 == null)) { (this.__GoogleChartsLoaderService_129 = new import98.GoogleChartsLoaderService()); }
    return this.__GoogleChartsLoaderService_129;
  }
  get _GlobalService_130():import99.GlobalService {
    if ((this.__GlobalService_130 == null)) { (this.__GlobalService_130 = new import99.GlobalService()); }
    return this.__GlobalService_130;
  }
  get _AuthorizationService_131():import100.AuthorizationService {
    if ((this.__AuthorizationService_131 == null)) { (this.__AuthorizationService_131 = new import100.AuthorizationService(this._GlobalService_130)); }
    return this.__AuthorizationService_131;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._InternalFormsSharedModule_3 = new import5.InternalFormsSharedModule();
    this._FormsModule_4 = new import6.FormsModule();
    this._HttpModule_5 = new import7.HttpModule();
    this._JsonpModule_6 = new import7.JsonpModule();
    this._MdRippleModule_7 = new import8.MdRippleModule();
    this._MdButtonModule_8 = new import9.MdButtonModule();
    this._MdCardModule_9 = new import10.MdCardModule();
    this._MdCheckboxModule_10 = new import11.MdCheckboxModule();
    this._MdLineModule_11 = new import12.MdLineModule();
    this._MdGridListModule_12 = new import13.MdGridListModule();
    this._MdInputModule_13 = new import14.MdInputModule();
    this._MdListModule_14 = new import15.MdListModule();
    this._MdProgressBarModule_15 = new import16.MdProgressBarModule();
    this._MdProgressCircleModule_16 = new import17.MdProgressCircleModule();
    this._MdSidenavModule_17 = new import18.MdSidenavModule();
    this._PortalModule_18 = new import19.PortalModule();
    this._MdTabsModule_19 = new import20.MdTabsModule();
    this._MdToolbarModule_20 = new import21.MdToolbarModule();
    this._RtlModule_21 = new import22.RtlModule();
    this._A11yModule_22 = new import23.A11yModule();
    this._MdButtonToggleModule_23 = new import24.MdButtonToggleModule();
    this._OverlayModule_24 = new import25.OverlayModule();
    this._MdDialogModule_25 = new import26.MdDialogModule();
    this._MdIconModule_26 = new import27.MdIconModule();
    this._MdMenuModule_27 = new import28.MdMenuModule();
    this._MdRadioModule_28 = new import29.MdRadioModule();
    this._MdSliderModule_29 = new import30.MdSliderModule();
    this._MdSlideToggleModule_30 = new import31.MdSlideToggleModule();
    this._MdSnackBarModule_31 = new import32.MdSnackBarModule();
    this._MdTooltipModule_32 = new import33.MdTooltipModule();
    this._StyleCompatibilityModule_33 = new import34.StyleCompatibilityModule();
    this._MaterialRootModule_34 = new import35.MaterialRootModule();
    this._ROUTER_FORROOT_GUARD_35 = import36.provideForRootGuard(this.parent.get(import142.Router,(null as any)));
    this._RouterModule_36 = new import36.RouterModule(this._ROUTER_FORROOT_GUARD_35);
    this._EmailAppRoutingModule_37 = new import37.EmailAppRoutingModule();
    this._SharedModule_38 = new import38.SharedModule();
    this._PaginatorModule_39 = new import39.PaginatorModule();
    this._InputTextModule_40 = new import40.InputTextModule();
    this._DataTableModule_41 = new import41.DataTableModule();
    this._ButtonModule_42 = new import42.ButtonModule();
    this._PickListModule_43 = new import43.PickListModule();
    this._DialogModule_44 = new import44.DialogModule();
    this._PanelModule_45 = new import45.PanelModule();
    this._GrowlModule_46 = new import46.GrowlModule();
    this._MultiSelectModule_47 = new import47.MultiSelectModule();
    this._ListboxModule_48 = new import48.ListboxModule();
    this._TabViewModule_49 = new import49.TabViewModule();
    this._DropdownModule_50 = new import50.DropdownModule();
    this._SecurityModule_51 = new import51.SecurityModule();
    this._EmailModule_52 = new import52.EmailModule();
    this._Ng2GoogleChartsModule_53 = new import53.Ng2GoogleChartsModule();
    this._AppModule_54 = new import1.AppModule();
    this._ErrorHandler_57 = import4.errorHandler();
    this._RouterInitializer_58 = new import36.RouterInitializer(this);
    this._APP_INITIALIZER_59 = [import36.getAppInitializer(this._RouterInitializer_58)];
    this._ApplicationInitStatus_60 = new import55.ApplicationInitStatus(this._APP_INITIALIZER_59);
    this._Testability_61 = new import56.Testability(this.parent.get(import124.NgZone));
    this._ApplicationRef__62 = new import57.ApplicationRef_(this.parent.get(import124.NgZone),this.parent.get(import143.Console),this,this._ErrorHandler_57,this,this._ApplicationInitStatus_60,this.parent.get(import56.TestabilityRegistry,(null as any)),this._Testability_61);
    this._DomSharedStylesHost_70 = new import61.DomSharedStylesHost(this._DOCUMENT_66);
    this._NoPreloading_112 = new import86.NoPreloading();
    this._PreloadingStrategy_113 = this._NoPreloading_112;
    this._RouterPreloader_114 = new import86.RouterPreloader(this._Router_110,this._NgModuleFactoryLoader_108,this._Compiler_64,this,this._PreloadingStrategy_113);
    return this._AppModule_54;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_3; }
    if ((token === import6.FormsModule)) { return this._FormsModule_4; }
    if ((token === import7.HttpModule)) { return this._HttpModule_5; }
    if ((token === import7.JsonpModule)) { return this._JsonpModule_6; }
    if ((token === import8.MdRippleModule)) { return this._MdRippleModule_7; }
    if ((token === import9.MdButtonModule)) { return this._MdButtonModule_8; }
    if ((token === import10.MdCardModule)) { return this._MdCardModule_9; }
    if ((token === import11.MdCheckboxModule)) { return this._MdCheckboxModule_10; }
    if ((token === import12.MdLineModule)) { return this._MdLineModule_11; }
    if ((token === import13.MdGridListModule)) { return this._MdGridListModule_12; }
    if ((token === import14.MdInputModule)) { return this._MdInputModule_13; }
    if ((token === import15.MdListModule)) { return this._MdListModule_14; }
    if ((token === import16.MdProgressBarModule)) { return this._MdProgressBarModule_15; }
    if ((token === import17.MdProgressCircleModule)) { return this._MdProgressCircleModule_16; }
    if ((token === import18.MdSidenavModule)) { return this._MdSidenavModule_17; }
    if ((token === import19.PortalModule)) { return this._PortalModule_18; }
    if ((token === import20.MdTabsModule)) { return this._MdTabsModule_19; }
    if ((token === import21.MdToolbarModule)) { return this._MdToolbarModule_20; }
    if ((token === import22.RtlModule)) { return this._RtlModule_21; }
    if ((token === import23.A11yModule)) { return this._A11yModule_22; }
    if ((token === import24.MdButtonToggleModule)) { return this._MdButtonToggleModule_23; }
    if ((token === import25.OverlayModule)) { return this._OverlayModule_24; }
    if ((token === import26.MdDialogModule)) { return this._MdDialogModule_25; }
    if ((token === import27.MdIconModule)) { return this._MdIconModule_26; }
    if ((token === import28.MdMenuModule)) { return this._MdMenuModule_27; }
    if ((token === import29.MdRadioModule)) { return this._MdRadioModule_28; }
    if ((token === import30.MdSliderModule)) { return this._MdSliderModule_29; }
    if ((token === import31.MdSlideToggleModule)) { return this._MdSlideToggleModule_30; }
    if ((token === import32.MdSnackBarModule)) { return this._MdSnackBarModule_31; }
    if ((token === import33.MdTooltipModule)) { return this._MdTooltipModule_32; }
    if ((token === import34.StyleCompatibilityModule)) { return this._StyleCompatibilityModule_33; }
    if ((token === import35.MaterialRootModule)) { return this._MaterialRootModule_34; }
    if ((token === import36.ROUTER_FORROOT_GUARD)) { return this._ROUTER_FORROOT_GUARD_35; }
    if ((token === import36.RouterModule)) { return this._RouterModule_36; }
    if ((token === import37.EmailAppRoutingModule)) { return this._EmailAppRoutingModule_37; }
    if ((token === import38.SharedModule)) { return this._SharedModule_38; }
    if ((token === import39.PaginatorModule)) { return this._PaginatorModule_39; }
    if ((token === import40.InputTextModule)) { return this._InputTextModule_40; }
    if ((token === import41.DataTableModule)) { return this._DataTableModule_41; }
    if ((token === import42.ButtonModule)) { return this._ButtonModule_42; }
    if ((token === import43.PickListModule)) { return this._PickListModule_43; }
    if ((token === import44.DialogModule)) { return this._DialogModule_44; }
    if ((token === import45.PanelModule)) { return this._PanelModule_45; }
    if ((token === import46.GrowlModule)) { return this._GrowlModule_46; }
    if ((token === import47.MultiSelectModule)) { return this._MultiSelectModule_47; }
    if ((token === import48.ListboxModule)) { return this._ListboxModule_48; }
    if ((token === import49.TabViewModule)) { return this._TabViewModule_49; }
    if ((token === import50.DropdownModule)) { return this._DropdownModule_50; }
    if ((token === import51.SecurityModule)) { return this._SecurityModule_51; }
    if ((token === import52.EmailModule)) { return this._EmailModule_52; }
    if ((token === import53.Ng2GoogleChartsModule)) { return this._Ng2GoogleChartsModule_53; }
    if ((token === import1.AppModule)) { return this._AppModule_54; }
    if ((token === import119.LOCALE_ID)) { return this._LOCALE_ID_55; }
    if ((token === import54.NgLocalization)) { return this._NgLocalization_56; }
    if ((token === import144.ErrorHandler)) { return this._ErrorHandler_57; }
    if ((token === import36.RouterInitializer)) { return this._RouterInitializer_58; }
    if ((token === import55.APP_INITIALIZER)) { return this._APP_INITIALIZER_59; }
    if ((token === import55.ApplicationInitStatus)) { return this._ApplicationInitStatus_60; }
    if ((token === import56.Testability)) { return this._Testability_61; }
    if ((token === import57.ApplicationRef_)) { return this._ApplicationRef__62; }
    if ((token === import57.ApplicationRef)) { return this._ApplicationRef_63; }
    if ((token === import58.Compiler)) { return this._Compiler_64; }
    if ((token === import120.APP_ID)) { return this._APP_ID_65; }
    if ((token === import145.DOCUMENT)) { return this._DOCUMENT_66; }
    if ((token === import123.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_67; }
    if ((token === import60.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_68; }
    if ((token === import60.EventManager)) { return this._EventManager_69; }
    if ((token === import61.DomSharedStylesHost)) { return this._DomSharedStylesHost_70; }
    if ((token === import146.AnimationDriver)) { return this._AnimationDriver_71; }
    if ((token === import62.DomRootRenderer)) { return this._DomRootRenderer_72; }
    if ((token === import57.NgProbeToken)) { return this._NgProbeToken_73; }
    if ((token === import147.RootRenderer)) { return this._RootRenderer_74; }
    if ((token === import63.DomSanitizer)) { return this._DomSanitizer_75; }
    if ((token === import148.Sanitizer)) { return this._Sanitizer_76; }
    if ((token === import64.AnimationQueue)) { return this._AnimationQueue_77; }
    if ((token === import65.ViewUtils)) { return this._ViewUtils_78; }
    if ((token === import149.IterableDiffers)) { return this._IterableDiffers_79; }
    if ((token === import150.KeyValueDiffers)) { return this._KeyValueDiffers_80; }
    if ((token === import61.SharedStylesHost)) { return this._SharedStylesHost_81; }
    if ((token === import66.Title)) { return this._Title_82; }
    if ((token === import67.RadioControlRegistry)) { return this._RadioControlRegistry_83; }
    if ((token === import68.BrowserXhr)) { return this._BrowserXhr_84; }
    if ((token === import69.ResponseOptions)) { return this._ResponseOptions_85; }
    if ((token === import151.XSRFStrategy)) { return this._XSRFStrategy_86; }
    if ((token === import70.XHRBackend)) { return this._XHRBackend_87; }
    if ((token === import71.RequestOptions)) { return this._RequestOptions_88; }
    if ((token === import152.Http)) { return this._Http_89; }
    if ((token === import72.BrowserJsonp)) { return this._BrowserJsonp_90; }
    if ((token === import73.JSONPBackend)) { return this._JSONPBackend_91; }
    if ((token === import152.Jsonp)) { return this._Jsonp_92; }
    if ((token === import74.MdLiveAnnouncer)) { return this._MdLiveAnnouncer_93; }
    if ((token === import75.InteractivityChecker)) { return this._InteractivityChecker_94; }
    if ((token === import76.MdUniqueSelectionDispatcher)) { return this._MdUniqueSelectionDispatcher_95; }
    if ((token === import77.OverlayContainer)) { return this._OverlayContainer_96; }
    if ((token === import78.ViewportRuler)) { return this._ViewportRuler_97; }
    if ((token === import79.OverlayPositionBuilder)) { return this._OverlayPositionBuilder_98; }
    if ((token === import80.Overlay)) { return this._Overlay_99; }
    if ((token === import26.MdDialog)) { return this._MdDialog_100; }
    if ((token === import81.MdIconRegistry)) { return this._MdIconRegistry_101; }
    if ((token === import32.MdSnackBar)) { return this._MdSnackBar_102; }
    if ((token === import36.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_103; }
    if ((token === import127.LocationStrategy)) { return this._LocationStrategy_104; }
    if ((token === import82.Location)) { return this._Location_105; }
    if ((token === import83.UrlSerializer)) { return this._UrlSerializer_106; }
    if ((token === import84.RouterOutletMap)) { return this._RouterOutletMap_107; }
    if ((token === import153.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_108; }
    if ((token === import154.ROUTES)) { return this._ROUTES_109; }
    if ((token === import142.Router)) { return this._Router_110; }
    if ((token === import155.ActivatedRoute)) { return this._ActivatedRoute_111; }
    if ((token === import86.NoPreloading)) { return this._NoPreloading_112; }
    if ((token === import86.PreloadingStrategy)) { return this._PreloadingStrategy_113; }
    if ((token === import86.RouterPreloader)) { return this._RouterPreloader_114; }
    if ((token === import86.PreloadAllModules)) { return this._PreloadAllModules_115; }
    if ((token === import36.ROUTER_INITIALIZER)) { return this._ROUTER_INITIALIZER_116; }
    if ((token === import120.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_117; }
    if ((token === import87.UserRoleService)) { return this._UserRoleService_118; }
    if ((token === import88.LoginService)) { return this._LoginService_119; }
    if ((token === import89.UserGroupService)) { return this._UserGroupService_120; }
    if ((token === import90.UserAccountService)) { return this._UserAccountService_121; }
    if ((token === import91.ContactService)) { return this._ContactService_122; }
    if ((token === import92.GroupService)) { return this._GroupService_123; }
    if ((token === import93.CommonService)) { return this._CommonService_124; }
    if ((token === import94.ContactGroupService)) { return this._ContactGroupService_125; }
    if ((token === import95.EmailServerService)) { return this._EmailServerService_126; }
    if ((token === import96.EmailService)) { return this._EmailService_127; }
    if ((token === import97.EmailServerPropertiesService)) { return this._EmailServerPropertiesService_128; }
    if ((token === import98.GoogleChartsLoaderService)) { return this._GoogleChartsLoaderService_129; }
    if ((token === import99.GlobalService)) { return this._GlobalService_130; }
    if ((token === import100.AuthorizationService)) { return this._AuthorizationService_131; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__62.ngOnDestroy();
    this._DomSharedStylesHost_70.ngOnDestroy();
    this._RouterPreloader_114.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);