/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../../../src/app/security/security.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/forms/src/directives';
import * as import4 from '@angular/forms/src/form_providers';
import * as import5 from '@angular/http/src/http_module';
import * as import6 from '@angular/material/core/ripple/ripple';
import * as import7 from '@angular/material/button/button';
import * as import8 from '@angular/material/card/card';
import * as import9 from '@angular/material/checkbox/checkbox';
import * as import10 from '@angular/material/core/line/line';
import * as import11 from '@angular/material/grid-list/grid-list';
import * as import12 from '@angular/material/input/input';
import * as import13 from '@angular/material/list/list';
import * as import14 from '@angular/material/progress-bar/progress-bar';
import * as import15 from '@angular/material/progress-circle/progress-circle';
import * as import16 from '@angular/material/sidenav/sidenav';
import * as import17 from '@angular/material/core/portal/portal-directives';
import * as import18 from '@angular/material/tabs/tabs';
import * as import19 from '@angular/material/toolbar/toolbar';
import * as import20 from '@angular/material/core/rtl/dir';
import * as import21 from '@angular/material/core/a11y/index';
import * as import22 from '@angular/material/button-toggle/button-toggle';
import * as import23 from '@angular/material/core/overlay/overlay-directives';
import * as import24 from '@angular/material/dialog/dialog';
import * as import25 from '@angular/material/icon/icon';
import * as import26 from '@angular/material/menu/menu';
import * as import27 from '@angular/material/radio/radio';
import * as import28 from '@angular/material/slider/slider';
import * as import29 from '@angular/material/slide-toggle/slide-toggle';
import * as import30 from '@angular/material/snack-bar/snack-bar';
import * as import31 from '@angular/material/tooltip/tooltip';
import * as import32 from '@angular/material/core/compatibility/style-compatibility';
import * as import33 from '@angular/material/module';
import * as import34 from 'primeng/components/common/shared';
import * as import35 from 'primeng/components/paginator/paginator';
import * as import36 from 'primeng/components/inputtext/inputtext';
import * as import37 from 'primeng/components/datatable/datatable';
import * as import38 from 'primeng/components/button/button';
import * as import39 from 'primeng/components/picklist/picklist';
import * as import40 from 'primeng/components/dialog/dialog';
import * as import41 from 'primeng/components/panel/panel';
import * as import42 from 'primeng/components/growl/growl';
import * as import43 from 'primeng/components/multiselect/multiselect';
import * as import44 from 'primeng/components/listbox/listbox';
import * as import45 from 'primeng/components/tabview/tabview';
import * as import46 from 'primeng/components/dropdown/dropdown';
import * as import47 from '@angular/common/src/localization';
import * as import48 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import49 from '@angular/http/src/backends/browser_xhr';
import * as import50 from '@angular/http/src/base_response_options';
import * as import51 from '@angular/http/src/backends/xhr_backend';
import * as import52 from '@angular/http/src/base_request_options';
import * as import53 from '@angular/http/src/backends/browser_jsonp';
import * as import54 from '@angular/http/src/backends/jsonp_backend';
import * as import55 from '@angular/material/core/gestures/MdGestureConfig';
import * as import56 from '@angular/material/core/a11y/live-announcer';
import * as import57 from '@angular/material/core/a11y/interactivity-checker';
import * as import58 from '@angular/material/core/coordination/unique-selection-dispatcher';
import * as import59 from '@angular/material/core/overlay/overlay-container';
import * as import60 from '@angular/material/core/overlay/position/viewport-ruler';
import * as import61 from '@angular/material/core/overlay/position/overlay-position-builder';
import * as import62 from '@angular/material/core/overlay/overlay';
import * as import63 from '@angular/material/icon/icon-registry';
import * as import64 from '../../../../src/app/security/user-role/user-role.service';
import * as import65 from '../../../../src/app/security/login/login.service';
import * as import66 from '../../../../src/app/security/user-group/user-group.service';
import * as import67 from '../../../../src/app/security/user-account/user-account.service';
import * as import68 from '@angular/core/src/di/injector';
import * as import69 from '../../../node_modules/@angular/material/dialog/dialog-container.ngfactory';
import * as import70 from '../../../node_modules/@angular/material/snack-bar/snack-bar-container.ngfactory';
import * as import71 from '../../../node_modules/@angular/material/snack-bar/simple-snack-bar.ngfactory';
import * as import72 from '../../../node_modules/@angular/material/tooltip/tooltip.ngfactory';
import * as import73 from '@angular/core/src/i18n/tokens';
import * as import74 from '@angular/core/src/application_ref';
import * as import75 from '@angular/http/src/interfaces';
import * as import76 from '@angular/http/src/http';
import * as import77 from '@angular/platform-browser/src/dom/events/hammer_gestures';
class SecurityModuleInjector extends import0.NgModuleInjector<import1.SecurityModule> {
  _CommonModule_0:import2.CommonModule;
  _InternalFormsSharedModule_1:import3.InternalFormsSharedModule;
  _FormsModule_2:import4.FormsModule;
  _HttpModule_3:import5.HttpModule;
  _JsonpModule_4:import5.JsonpModule;
  _MdRippleModule_5:import6.MdRippleModule;
  _MdButtonModule_6:import7.MdButtonModule;
  _MdCardModule_7:import8.MdCardModule;
  _MdCheckboxModule_8:import9.MdCheckboxModule;
  _MdLineModule_9:import10.MdLineModule;
  _MdGridListModule_10:import11.MdGridListModule;
  _MdInputModule_11:import12.MdInputModule;
  _MdListModule_12:import13.MdListModule;
  _MdProgressBarModule_13:import14.MdProgressBarModule;
  _MdProgressCircleModule_14:import15.MdProgressCircleModule;
  _MdSidenavModule_15:import16.MdSidenavModule;
  _PortalModule_16:import17.PortalModule;
  _MdTabsModule_17:import18.MdTabsModule;
  _MdToolbarModule_18:import19.MdToolbarModule;
  _RtlModule_19:import20.RtlModule;
  _A11yModule_20:import21.A11yModule;
  _MdButtonToggleModule_21:import22.MdButtonToggleModule;
  _OverlayModule_22:import23.OverlayModule;
  _MdDialogModule_23:import24.MdDialogModule;
  _MdIconModule_24:import25.MdIconModule;
  _MdMenuModule_25:import26.MdMenuModule;
  _MdRadioModule_26:import27.MdRadioModule;
  _MdSliderModule_27:import28.MdSliderModule;
  _MdSlideToggleModule_28:import29.MdSlideToggleModule;
  _MdSnackBarModule_29:import30.MdSnackBarModule;
  _MdTooltipModule_30:import31.MdTooltipModule;
  _StyleCompatibilityModule_31:import32.StyleCompatibilityModule;
  _MaterialRootModule_32:import33.MaterialRootModule;
  _SharedModule_33:import34.SharedModule;
  _PaginatorModule_34:import35.PaginatorModule;
  _InputTextModule_35:import36.InputTextModule;
  _DataTableModule_36:import37.DataTableModule;
  _ButtonModule_37:import38.ButtonModule;
  _PickListModule_38:import39.PickListModule;
  _DialogModule_39:import40.DialogModule;
  _PanelModule_40:import41.PanelModule;
  _GrowlModule_41:import42.GrowlModule;
  _MultiSelectModule_42:import43.MultiSelectModule;
  _ListboxModule_43:import44.ListboxModule;
  _TabViewModule_44:import45.TabViewModule;
  _DropdownModule_45:import46.DropdownModule;
  _SecurityModule_46:import1.SecurityModule;
  __NgLocalization_47:import47.NgLocaleLocalization;
  __RadioControlRegistry_48:import48.RadioControlRegistry;
  __BrowserXhr_49:import49.BrowserXhr;
  __ResponseOptions_50:import50.BaseResponseOptions;
  __XSRFStrategy_51:any;
  __XHRBackend_52:import51.XHRBackend;
  __RequestOptions_53:import52.BaseRequestOptions;
  __Http_54:any;
  __BrowserJsonp_55:import53.BrowserJsonp;
  __JSONPBackend_56:import54.JSONPBackend_;
  __Jsonp_57:any;
  __HAMMER_GESTURE_CONFIG_58:import55.MdGestureConfig;
  __MdLiveAnnouncer_59:import56.MdLiveAnnouncer;
  __InteractivityChecker_60:import57.InteractivityChecker;
  __MdUniqueSelectionDispatcher_61:import58.MdUniqueSelectionDispatcher;
  __OverlayContainer_62:import59.OverlayContainer;
  __ViewportRuler_63:import60.ViewportRuler;
  __OverlayPositionBuilder_64:import61.OverlayPositionBuilder;
  __Overlay_65:import62.Overlay;
  __MdDialog_66:import24.MdDialog;
  __MdIconRegistry_67:import63.MdIconRegistry;
  __MdSnackBar_68:import30.MdSnackBar;
  __UserRoleService_69:import64.UserRoleService;
  __LoginService_70:import65.LoginService;
  __UserGroupService_71:import66.UserGroupService;
  __UserAccountService_72:import67.UserAccountService;
  constructor(parent:import68.Injector) {
    super(parent,[
      import69.MdDialogContainerNgFactory,
      import70.MdSnackBarContainerNgFactory,
      import71.SimpleSnackBarNgFactory,
      import72.TooltipComponentNgFactory
    ]
    ,([] as any[]));
  }
  get _NgLocalization_47():import47.NgLocaleLocalization {
    if ((this.__NgLocalization_47 == null)) { (this.__NgLocalization_47 = new import47.NgLocaleLocalization(this.parent.get(import73.LOCALE_ID))); }
    return this.__NgLocalization_47;
  }
  get _RadioControlRegistry_48():import48.RadioControlRegistry {
    if ((this.__RadioControlRegistry_48 == null)) { (this.__RadioControlRegistry_48 = new import48.RadioControlRegistry()); }
    return this.__RadioControlRegistry_48;
  }
  get _BrowserXhr_49():import49.BrowserXhr {
    if ((this.__BrowserXhr_49 == null)) { (this.__BrowserXhr_49 = new import49.BrowserXhr()); }
    return this.__BrowserXhr_49;
  }
  get _ResponseOptions_50():import50.BaseResponseOptions {
    if ((this.__ResponseOptions_50 == null)) { (this.__ResponseOptions_50 = new import50.BaseResponseOptions()); }
    return this.__ResponseOptions_50;
  }
  get _XSRFStrategy_51():any {
    if ((this.__XSRFStrategy_51 == null)) { (this.__XSRFStrategy_51 = import5._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_51;
  }
  get _XHRBackend_52():import51.XHRBackend {
    if ((this.__XHRBackend_52 == null)) { (this.__XHRBackend_52 = new import51.XHRBackend(this._BrowserXhr_49,this._ResponseOptions_50,this._XSRFStrategy_51)); }
    return this.__XHRBackend_52;
  }
  get _RequestOptions_53():import52.BaseRequestOptions {
    if ((this.__RequestOptions_53 == null)) { (this.__RequestOptions_53 = new import52.BaseRequestOptions()); }
    return this.__RequestOptions_53;
  }
  get _Http_54():any {
    if ((this.__Http_54 == null)) { (this.__Http_54 = import5.httpFactory(this._XHRBackend_52,this._RequestOptions_53)); }
    return this.__Http_54;
  }
  get _BrowserJsonp_55():import53.BrowserJsonp {
    if ((this.__BrowserJsonp_55 == null)) { (this.__BrowserJsonp_55 = new import53.BrowserJsonp()); }
    return this.__BrowserJsonp_55;
  }
  get _JSONPBackend_56():import54.JSONPBackend_ {
    if ((this.__JSONPBackend_56 == null)) { (this.__JSONPBackend_56 = new import54.JSONPBackend_(this._BrowserJsonp_55,this._ResponseOptions_50)); }
    return this.__JSONPBackend_56;
  }
  get _Jsonp_57():any {
    if ((this.__Jsonp_57 == null)) { (this.__Jsonp_57 = import5.jsonpFactory(this._JSONPBackend_56,this._RequestOptions_53)); }
    return this.__Jsonp_57;
  }
  get _HAMMER_GESTURE_CONFIG_58():import55.MdGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_58 == null)) { (this.__HAMMER_GESTURE_CONFIG_58 = new import55.MdGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_58;
  }
  get _MdLiveAnnouncer_59():import56.MdLiveAnnouncer {
    if ((this.__MdLiveAnnouncer_59 == null)) { (this.__MdLiveAnnouncer_59 = new import56.MdLiveAnnouncer(this.parent.get(import56.LIVE_ANNOUNCER_ELEMENT_TOKEN,(null as any)))); }
    return this.__MdLiveAnnouncer_59;
  }
  get _InteractivityChecker_60():import57.InteractivityChecker {
    if ((this.__InteractivityChecker_60 == null)) { (this.__InteractivityChecker_60 = new import57.InteractivityChecker()); }
    return this.__InteractivityChecker_60;
  }
  get _MdUniqueSelectionDispatcher_61():import58.MdUniqueSelectionDispatcher {
    if ((this.__MdUniqueSelectionDispatcher_61 == null)) { (this.__MdUniqueSelectionDispatcher_61 = new import58.MdUniqueSelectionDispatcher()); }
    return this.__MdUniqueSelectionDispatcher_61;
  }
  get _OverlayContainer_62():import59.OverlayContainer {
    if ((this.__OverlayContainer_62 == null)) { (this.__OverlayContainer_62 = new import59.OverlayContainer()); }
    return this.__OverlayContainer_62;
  }
  get _ViewportRuler_63():import60.ViewportRuler {
    if ((this.__ViewportRuler_63 == null)) { (this.__ViewportRuler_63 = new import60.ViewportRuler()); }
    return this.__ViewportRuler_63;
  }
  get _OverlayPositionBuilder_64():import61.OverlayPositionBuilder {
    if ((this.__OverlayPositionBuilder_64 == null)) { (this.__OverlayPositionBuilder_64 = new import61.OverlayPositionBuilder(this._ViewportRuler_63)); }
    return this.__OverlayPositionBuilder_64;
  }
  get _Overlay_65():import62.Overlay {
    if ((this.__Overlay_65 == null)) { (this.__Overlay_65 = new import62.Overlay(this._OverlayContainer_62,this,this._OverlayPositionBuilder_64,this.parent.get(import74.ApplicationRef),this)); }
    return this.__Overlay_65;
  }
  get _MdDialog_66():import24.MdDialog {
    if ((this.__MdDialog_66 == null)) { (this.__MdDialog_66 = new import24.MdDialog(this._Overlay_65,this)); }
    return this.__MdDialog_66;
  }
  get _MdIconRegistry_67():import63.MdIconRegistry {
    if ((this.__MdIconRegistry_67 == null)) { (this.__MdIconRegistry_67 = new import63.MdIconRegistry(this._Http_54)); }
    return this.__MdIconRegistry_67;
  }
  get _MdSnackBar_68():import30.MdSnackBar {
    if ((this.__MdSnackBar_68 == null)) { (this.__MdSnackBar_68 = new import30.MdSnackBar(this._Overlay_65,this._MdLiveAnnouncer_59)); }
    return this.__MdSnackBar_68;
  }
  get _UserRoleService_69():import64.UserRoleService {
    if ((this.__UserRoleService_69 == null)) { (this.__UserRoleService_69 = new import64.UserRoleService(this._Http_54)); }
    return this.__UserRoleService_69;
  }
  get _LoginService_70():import65.LoginService {
    if ((this.__LoginService_70 == null)) { (this.__LoginService_70 = new import65.LoginService(this._Http_54)); }
    return this.__LoginService_70;
  }
  get _UserGroupService_71():import66.UserGroupService {
    if ((this.__UserGroupService_71 == null)) { (this.__UserGroupService_71 = new import66.UserGroupService(this._Http_54)); }
    return this.__UserGroupService_71;
  }
  get _UserAccountService_72():import67.UserAccountService {
    if ((this.__UserAccountService_72 == null)) { (this.__UserAccountService_72 = new import67.UserAccountService(this._Http_54)); }
    return this.__UserAccountService_72;
  }
  createInternal():import1.SecurityModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._InternalFormsSharedModule_1 = new import3.InternalFormsSharedModule();
    this._FormsModule_2 = new import4.FormsModule();
    this._HttpModule_3 = new import5.HttpModule();
    this._JsonpModule_4 = new import5.JsonpModule();
    this._MdRippleModule_5 = new import6.MdRippleModule();
    this._MdButtonModule_6 = new import7.MdButtonModule();
    this._MdCardModule_7 = new import8.MdCardModule();
    this._MdCheckboxModule_8 = new import9.MdCheckboxModule();
    this._MdLineModule_9 = new import10.MdLineModule();
    this._MdGridListModule_10 = new import11.MdGridListModule();
    this._MdInputModule_11 = new import12.MdInputModule();
    this._MdListModule_12 = new import13.MdListModule();
    this._MdProgressBarModule_13 = new import14.MdProgressBarModule();
    this._MdProgressCircleModule_14 = new import15.MdProgressCircleModule();
    this._MdSidenavModule_15 = new import16.MdSidenavModule();
    this._PortalModule_16 = new import17.PortalModule();
    this._MdTabsModule_17 = new import18.MdTabsModule();
    this._MdToolbarModule_18 = new import19.MdToolbarModule();
    this._RtlModule_19 = new import20.RtlModule();
    this._A11yModule_20 = new import21.A11yModule();
    this._MdButtonToggleModule_21 = new import22.MdButtonToggleModule();
    this._OverlayModule_22 = new import23.OverlayModule();
    this._MdDialogModule_23 = new import24.MdDialogModule();
    this._MdIconModule_24 = new import25.MdIconModule();
    this._MdMenuModule_25 = new import26.MdMenuModule();
    this._MdRadioModule_26 = new import27.MdRadioModule();
    this._MdSliderModule_27 = new import28.MdSliderModule();
    this._MdSlideToggleModule_28 = new import29.MdSlideToggleModule();
    this._MdSnackBarModule_29 = new import30.MdSnackBarModule();
    this._MdTooltipModule_30 = new import31.MdTooltipModule();
    this._StyleCompatibilityModule_31 = new import32.StyleCompatibilityModule();
    this._MaterialRootModule_32 = new import33.MaterialRootModule();
    this._SharedModule_33 = new import34.SharedModule();
    this._PaginatorModule_34 = new import35.PaginatorModule();
    this._InputTextModule_35 = new import36.InputTextModule();
    this._DataTableModule_36 = new import37.DataTableModule();
    this._ButtonModule_37 = new import38.ButtonModule();
    this._PickListModule_38 = new import39.PickListModule();
    this._DialogModule_39 = new import40.DialogModule();
    this._PanelModule_40 = new import41.PanelModule();
    this._GrowlModule_41 = new import42.GrowlModule();
    this._MultiSelectModule_42 = new import43.MultiSelectModule();
    this._ListboxModule_43 = new import44.ListboxModule();
    this._TabViewModule_44 = new import45.TabViewModule();
    this._DropdownModule_45 = new import46.DropdownModule();
    this._SecurityModule_46 = new import1.SecurityModule();
    return this._SecurityModule_46;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_1; }
    if ((token === import4.FormsModule)) { return this._FormsModule_2; }
    if ((token === import5.HttpModule)) { return this._HttpModule_3; }
    if ((token === import5.JsonpModule)) { return this._JsonpModule_4; }
    if ((token === import6.MdRippleModule)) { return this._MdRippleModule_5; }
    if ((token === import7.MdButtonModule)) { return this._MdButtonModule_6; }
    if ((token === import8.MdCardModule)) { return this._MdCardModule_7; }
    if ((token === import9.MdCheckboxModule)) { return this._MdCheckboxModule_8; }
    if ((token === import10.MdLineModule)) { return this._MdLineModule_9; }
    if ((token === import11.MdGridListModule)) { return this._MdGridListModule_10; }
    if ((token === import12.MdInputModule)) { return this._MdInputModule_11; }
    if ((token === import13.MdListModule)) { return this._MdListModule_12; }
    if ((token === import14.MdProgressBarModule)) { return this._MdProgressBarModule_13; }
    if ((token === import15.MdProgressCircleModule)) { return this._MdProgressCircleModule_14; }
    if ((token === import16.MdSidenavModule)) { return this._MdSidenavModule_15; }
    if ((token === import17.PortalModule)) { return this._PortalModule_16; }
    if ((token === import18.MdTabsModule)) { return this._MdTabsModule_17; }
    if ((token === import19.MdToolbarModule)) { return this._MdToolbarModule_18; }
    if ((token === import20.RtlModule)) { return this._RtlModule_19; }
    if ((token === import21.A11yModule)) { return this._A11yModule_20; }
    if ((token === import22.MdButtonToggleModule)) { return this._MdButtonToggleModule_21; }
    if ((token === import23.OverlayModule)) { return this._OverlayModule_22; }
    if ((token === import24.MdDialogModule)) { return this._MdDialogModule_23; }
    if ((token === import25.MdIconModule)) { return this._MdIconModule_24; }
    if ((token === import26.MdMenuModule)) { return this._MdMenuModule_25; }
    if ((token === import27.MdRadioModule)) { return this._MdRadioModule_26; }
    if ((token === import28.MdSliderModule)) { return this._MdSliderModule_27; }
    if ((token === import29.MdSlideToggleModule)) { return this._MdSlideToggleModule_28; }
    if ((token === import30.MdSnackBarModule)) { return this._MdSnackBarModule_29; }
    if ((token === import31.MdTooltipModule)) { return this._MdTooltipModule_30; }
    if ((token === import32.StyleCompatibilityModule)) { return this._StyleCompatibilityModule_31; }
    if ((token === import33.MaterialRootModule)) { return this._MaterialRootModule_32; }
    if ((token === import34.SharedModule)) { return this._SharedModule_33; }
    if ((token === import35.PaginatorModule)) { return this._PaginatorModule_34; }
    if ((token === import36.InputTextModule)) { return this._InputTextModule_35; }
    if ((token === import37.DataTableModule)) { return this._DataTableModule_36; }
    if ((token === import38.ButtonModule)) { return this._ButtonModule_37; }
    if ((token === import39.PickListModule)) { return this._PickListModule_38; }
    if ((token === import40.DialogModule)) { return this._DialogModule_39; }
    if ((token === import41.PanelModule)) { return this._PanelModule_40; }
    if ((token === import42.GrowlModule)) { return this._GrowlModule_41; }
    if ((token === import43.MultiSelectModule)) { return this._MultiSelectModule_42; }
    if ((token === import44.ListboxModule)) { return this._ListboxModule_43; }
    if ((token === import45.TabViewModule)) { return this._TabViewModule_44; }
    if ((token === import46.DropdownModule)) { return this._DropdownModule_45; }
    if ((token === import1.SecurityModule)) { return this._SecurityModule_46; }
    if ((token === import47.NgLocalization)) { return this._NgLocalization_47; }
    if ((token === import48.RadioControlRegistry)) { return this._RadioControlRegistry_48; }
    if ((token === import49.BrowserXhr)) { return this._BrowserXhr_49; }
    if ((token === import50.ResponseOptions)) { return this._ResponseOptions_50; }
    if ((token === import75.XSRFStrategy)) { return this._XSRFStrategy_51; }
    if ((token === import51.XHRBackend)) { return this._XHRBackend_52; }
    if ((token === import52.RequestOptions)) { return this._RequestOptions_53; }
    if ((token === import76.Http)) { return this._Http_54; }
    if ((token === import53.BrowserJsonp)) { return this._BrowserJsonp_55; }
    if ((token === import54.JSONPBackend)) { return this._JSONPBackend_56; }
    if ((token === import76.Jsonp)) { return this._Jsonp_57; }
    if ((token === import77.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_58; }
    if ((token === import56.MdLiveAnnouncer)) { return this._MdLiveAnnouncer_59; }
    if ((token === import57.InteractivityChecker)) { return this._InteractivityChecker_60; }
    if ((token === import58.MdUniqueSelectionDispatcher)) { return this._MdUniqueSelectionDispatcher_61; }
    if ((token === import59.OverlayContainer)) { return this._OverlayContainer_62; }
    if ((token === import60.ViewportRuler)) { return this._ViewportRuler_63; }
    if ((token === import61.OverlayPositionBuilder)) { return this._OverlayPositionBuilder_64; }
    if ((token === import62.Overlay)) { return this._Overlay_65; }
    if ((token === import24.MdDialog)) { return this._MdDialog_66; }
    if ((token === import63.MdIconRegistry)) { return this._MdIconRegistry_67; }
    if ((token === import30.MdSnackBar)) { return this._MdSnackBar_68; }
    if ((token === import64.UserRoleService)) { return this._UserRoleService_69; }
    if ((token === import65.LoginService)) { return this._LoginService_70; }
    if ((token === import66.UserGroupService)) { return this._UserGroupService_71; }
    if ((token === import67.UserAccountService)) { return this._UserAccountService_72; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const SecurityModuleNgFactory:import0.NgModuleFactory<import1.SecurityModule> = new import0.NgModuleFactory(SecurityModuleInjector,import1.SecurityModule);